<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Currency;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Html\Footer;

/** @var Footer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);

$block->setCacheKey('footer_currency_' . $currencyViewModel->getCurrentCurrencyCode());
?>

<template x-portal="document.getElementById('footer-portal')">
    <div class="contents">
        <footer
            class="footer rounded-t-2xl md:bg-secondary-400"
            x-cloak
            :class="{ 'hidden': $store.main.isMobile && '<?= $block->getIsHomePage() ?>' !== '1' }"
        >
            <div class="flex w-full flex-col items-stretch gap-5 pb-5 md:gap-8 md:py-8">
                <hr class="divider md:hidden">
                <?php if ($block->getIsCmsBlockAvailable('footer')): ?>
                    <?= $block->getBlockHtml('satoshi-footer') ?>
                <?php endif; ?>
                <div
                    class="content-wrapper mx-auto  flex w-full flex-col items-center gap-5 md:flex-row-reverse md:justify-between md:gap-7">
                    <div class="flex flex-wrap justify-center gap-5 text-center md:order-1">
                        <?= $block->getBlockHtml('store-switcher') ?>
                        <?= $block->getBlockHtml('store-language-switcher') ?>
                        <?= $block->getBlockHtml('currency-switcher') ?>
                    </div>
                    <?= $block->getChildHtml('copyright') ?>
                </div>
            </div>
        </footer>
    </div>
</template>
