<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$cssClass = $block->getCssClass() ?: 'content-wrapper mx-auto';
?>

<?php if (trim((string)$block->getPageHeading())): ?>
    <div class="<?= $cssClass ?>">
        <h1 class="text-text-500 text-xxl mb-5" <?= $block->getAddBaseAttribute() ?>>
            <?= $escaper->escapeHtml($block->getPageHeading()) ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
