<?php

declare(strict_types=1);

/** @var Template $block */

use Magento\Framework\View\Element\Template;

$pageTitle = $block->getPage()?->getTitle();
$pageContent = $block->getPage()?->getContent();
?>

<article class="content-wrapper mx-auto">
    <h1 class="mb-7 text-center text-4xl text-text-500" itemprop="headline"><?= $this->escapeHtml($pageTitle) ?></h1>

    <div class="rte animate-on-transition" itemprop="articleBody">
        <?= $pageContent ?>
    </div>
</article>
