<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Template $template */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div
  :inert="$store.main.isMobile ? $store.popup.currentPopup !== 'wishlist' : !$store.resizable.isVisible('wishlist-desktop')"
  x-data="
    {
      get wishlistItems() { return $store.wishlist.wishlistItems },
      get isWishlistEmpty() { return !$store.wishlist.wishlistItems.length },
      get isRemoveContent() { return !$store.wishlist.wishlistItems.length }
    }
  "
  class="contents"
>
  <div
      class="flex flex-col gap-5 rounded-md p-5 md:w-[--wishlist-width] bg-bg-500 md:gap-0 md:px-0 md:py-0 max-md:py-0 [.popup\_\_main_&]:px-2"
  >
    <div
      class="flex items-center justify-between md:h-[--initial-height] md:min-h-14 md:rounded-md max-md:pb-4 md:px-6 sticky top-0 z-10 bg-bg-500"
    >
      <h1 class="flex items-center text-lg text-text-500 md:text-md">
        <span class="button__icon mr-4 text-[1.5rem] max-md:hidden">
          <?= $hyvaicons->renderHtml('bookmark-empty', attributes: ['title' => $escaper->escapeHtml(__('Wishlist'))]) ?>
        </span>

        <?= $escaper->escapeHtml(__('Saved items')) ?>
      </h1>
      <template x-if="!isWishlistEmpty">
        <div
          class="delay-800 mr-1 flex justify-center align-middle transition-all duration-300"
          :class="{'opacity-0': isWishlistEmpty}"
        >
          <a
            href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
            x-element-transition-trigger
            class="link link--ghost"
          >
            <?= $escaper->escapeHtml(__('View wishlist')) ?>
            <span
              x-text="`(${wishlistItems.length})`"
              class="mr-1"
            ></span>
          </a>
        </div>
      </template>
    </div>

    <div
      class="max-h-0 pb-0 opacity-0"
      :class="
        {
          'opacity-0 max-h-0 pb-0': !isWishlistEmpty,
          'opacity-1 max-h-80 pb-4 md:px-6': isWishlistEmpty,
          'hidden': !isRemoveContent
        }
      "
    >
      <p>
        <?= $escaper->escapeHtml(__('You did not add any products to wishlist yet!')) ?>
      </p>
    </div>
    <div
      class="transition-opacity duration-300"
      :class="
        {
          'opacity-0': isWishlistEmpty,
          'opacity-1': !isWishlistEmpty,
          'hidden': isRemoveContent
        }
      "
      @transitionend="isRemoveContent = isWishlistEmpty"
    >
      <div class="contents">
        <?= $template->render('Magento_Theme::html/header/wishlist/wishlist-items.phtml') ?>
      </div>
    </div>
  </div>
</div>
