<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\ReviewRenderer;

/** @var ViewModelRegistry $viewModels */
/** @var ReviewRenderer $block */
/** @var Escaper $escaper */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);

$rating = $block->getRatingSummary();
$ratingSteps = 5;
$starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
$starFragment = $rating / 100 * $ratingSteps - $starsFilled;
$starsEmpty = floor($ratingSteps - $starsFilled - $starFragment);
$primaryColor = 'var(--color-primary-600)';
$secondaryColor = '#cbd5e0';
$reviewCount = $block->getReviewsCount();
$productName = $block->getProduct()->getName();
$productId = $block->getProduct()->getId();
$uniqueId = $productId . uniqid();
?>
<?php if ($block->isReviewEnabled()): ?>
    <button
        x-data="Rating"
        @keyup.enter="scrollToRatings()"
        @click="scrollToRatings()"
        class="rating-summary flex"
        :class="{'cursor-pointer' : reviewsSection}"
        <?php if (!$rating): ?>
            title="<?= $escaper->escapeHtmlAttr(__('Be the first to review this product')) ?>"
        <?php endif; ?>
        <?php if ($reviewCount): ?>
            itemprop="aggregateRating"
            itemscope
            itemtype="http://schema.org/AggregateRating"
        <?php endif; ?>
            :tabindex="reviewsSection ? '0' : '-1'"
            :aria-label="reviewsSection
            ? '<?= $escaper->escapeJs(__('%1 rating. %2 out of %3 stars. Click to go to reviews.', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>'
            : '<?= $escaper->escapeJs(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>'
        "
            :role="reviewsSection ? 'button' : 'img'"
    >
        <?php if ($reviewCount): ?>
            <span class="hidden" itemprop="ratingValue"><?= $starsFilled + $starFragment; ?></span>
            <span class="hidden" itemprop="reviewCount"><?= (int)$reviewCount; ?></span>
        <?php endif; ?>
        <?php if ($rating): ?>
            <?php $i = 0; ?>
            <?php while ($i < $starsFilled): ?>
                <?= $hyvaicons->renderHtml('star', 'text-primary-500 text-xl') ?>
                <?php $i++; ?>
            <?php endwhile; ?>
            <?php if ($starFragment): ?>
                <svg
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                    style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"
                    class="text-xl"
                >
                    <defs>
                        <linearGradient id="partialFill<?= /* @noEscape */
                        $block->getProduct()->getId() ?>">
                            <stop offset="0%" stop-color="<?= /** @noEscape */
                            $primaryColor ?>"/>
                            <stop offset="<?= $starFragment * 100 ?>%" stop-color="<?= /** @noEscape */
                            $primaryColor ?>"/>
                            <stop offset="<?= $starFragment * 100 ?>%" stop-color="<?= /** @noEscape */
                            $secondaryColor ?>"/>
                            <stop offset="100%" stop-color="<?= /** @noEscape */
                            $secondaryColor ?>"/>
                        </linearGradient>
                    </defs>
                    <g fill="url(#partialFill<?= (int)$block->getProduct()->getId() ?>)">
                        <path d="M19.799 9.774a1.025 1.025 0 0 0-.957-.667h-4.144a.34.34 0 0 1-.322-.227L12.89 4.664a1.021 1.021 0 0 0-1.913 0l-.004.01L9.488 8.88a.34.34 0 0 1-.32.227H5.021a1.021 1.021 0 0 0-.656 1.805l3.53 2.927a.34.34 0 0 1 .105.37l-1.483 4.446a1.021 1.021 0 0 0 1.573 1.147l3.64-2.669a.34.34 0 0 1 .402 0l3.638 2.668a1.021 1.021 0 0 0 1.574-1.146l-1.483-4.449a.34.34 0 0 1 .106-.37l3.536-2.93a1.021 1.021 0 0 0 .295-1.132Z"/>
                    </g>
                </svg>
            <?php endif; ?>
            <?php $i = 0; ?>
            <?php while ($i < $starsEmpty): ?>
                <?= $hyvaicons->renderHtml('star', 'text-secondary-700 text-xl') ?>
                <?php $i++; ?>
            <?php endwhile; ?>
        <?php else: ?>
            <?php $i = 0; ?>
            <?php while ($i < $ratingSteps): ?>
                <?= $hyvaicons->renderHtml('star', 'text-secondary-700 text-xl') ?>
                <?php $i++; ?>
            <?php endwhile; ?>
        <?php endif; ?>
    </button>
<?php endif; ?>
