<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;
use Satoshi\Theme\ViewModel\LanguageSelector;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LanguageSelector $languageViewModel */

$languageViewModel = $viewModels->require(LanguageSelector::class);
$languages = $languageViewModel->getAvailableLanguages();
$currentLanguageCode = $languageViewModel->getCurrentLanguageCode();

$options = [];
foreach ($languages as $key => $language) {
    $options[] = [
        'value' => $escaper->escapeHtml($key),
        'label' => $escaper->escapeHtml($language['name'] ?? ''),
        'on_click' => "document.querySelector('[name=language_code]').value = '$key'; document.querySelector('#localization_form').submit();",
        'is_active' => $key === $currentLanguageCode,
    ];
}

$currentLabel = __($languages[$currentLanguageCode]['name'] ?? '');
?>

<?php if (count($options) > 1): ?>
    <form method="post"
          action="<?= $template->getUrl('satoshi_theme/language/updateDefaultStore') ?>"
          id="localization_form" accept-charset="UTF-8" class="shopify-localization-form">
        <?= $template->getBlockHtml('formkey') ?>
        <input type="hidden" name="language_code" value="<?= $currentLanguageCode ?>">

        <?=
        $template
            ->setData([
                'id' => 'language-selector',
                'label' => $escaper->escapeHtml($currentLabel),
                'options' => $options,
                'placement' => 'top',
            ])
            ->render('Magento_Theme::html/components/dropdown.phtml');
        ?>
    </form>
<?php endif; ?>
