<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$title = $block->getChildBlock('page.main.title')? $block->getChildBlock('page.main.title')->getPageHeading() : __('404');
$content = $block->getChildHtml('cms_page') ?? $block->getChildHtml('cms_noroute');
?>

<div class="content-wrapper mx-auto flex h-full flex-col items-center justify-center gap-5">
    <p class="text-[80px] leading-none">
        <?= $title ?>
    </p>

    <div class="rte">
        <?= $content ?>
    </div>
</div>
