<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Product\RadioPriceRenderer;
use Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio;
use Magento\Framework\Escaper;

/** @var Radio $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var RadioPriceRenderer $radioPriceRenderer */
$radioPriceRenderer = $viewModels->require(RadioPriceRenderer::class);

$option = $block->getOption();
$selections = $option->getSelections();
$default = $option->getDefaultSelection();
list($defaultQty, $canChangeQty) = $block->getDefaultValues();

$optionId = $option->getId();
$activeSelectOptions = [];

$product = $block->getProduct();
$productId = $product->getId();

$isPopup = $block->getData('is_popup');
?>
<div class="flex justify-between items-center gap-3">
    <?php if ($block->showSingle()): ?>
        <input type="hidden"
               id="bundle-option-<?= (int)$optionId ?>-<?= (int)$selections[0]->getSelectionId() ?>"
               name="bundle_option[<?= (int)$optionId ?>]"
               form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
               value="<?= (int)$selections[0]->getSelectionId() ?>"
               checked
               data-option-id="<?= (int)$optionId ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>"
               data-selection-id="<?= (int)$selections[0]->getSelectionId() ?>"
        />
        <span><?= /* @noEscape */
            $radioPriceRenderer->getSelectionTitlePrice($selections[0]) ?></span>
        <?= /* @noEscape */
        $block->getTierPriceRenderer()->renderTierPrice($selections[0]) ?>
        <?php if ((int)$selections[0]->getSelectionId()) {
            array_push($activeSelectOptions, (int)$selections[0]->getSelectionId());
        } ?>
    <?php else: ?>

        <!-- Radio group -->
        <div role="radiogroup"
             aria-label="<?= $escaper->escapeHtmlAttr(__('%1 options', $option->getTitle())) ?>"
        >
            <?php if (!$option->getRequired()): ?>
                <div class="mb-2">
                    <label class="radio mb-0 w-full py-1"
                           for="bundle-option-<?= (int)$optionId ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>">
                        <input type="radio"
                               id="bundle-option-<?= (int)$optionId ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>"
                               name="bundle_option[<?= (int)$optionId ?>]"
                               form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
                               class="radio__input"
                               :checked="activeSelectOptions['<?= (int)$optionId ?>'] == ''"
                               value=""
                               x-on:change="
                            activeSelectOptions['<?= (int)$optionId ?>'] = [$event.target.value];
                            $nextTick(() => {calculateTotalPrice()});
                      "
                        />

                        <span class="radio__control h-5 w-5" aria-hidden="true"></span>
                        <span class="radio__label ml-3"><?= $escaper->escapeHtml(__('None')) ?>
                    </label>
                </div>
            <?php endif; ?>

            <?php foreach ($selections as $selection): ?>
                <?php $selectionId = $selection->getSelectionId(); ?>
                <?php $optionSelectionId = $optionId . '-' . $selectionId ?>
                <label
                    class="radio mb-0 w-full py-1"
                    for="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>"
                >
                    <input type="radio"
                           id="bundle-option-<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>"
                           name="bundle_option[<?= (int)$optionId ?>]"
                           form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
                           class="radio__input"
                        <?= $option->getRequired() ? 'required' : '' ?>
                           :checked="activeSelectOptions['<?= (int)$optionId ?>'] == '<?= (int)$selectionId ?>'"
                        <?php if (!$selection->isSaleable()): ?>
                            disabled
                        <?php endif; ?>
                           value="<?= (int)$selectionId ?>"
                           data-option-id="<?= $escaper->escapeHtmlAttr($optionSelectionId) ?>-<?= $isPopup ? 'mobile' : 'desktop' ?>"
                           x-on:change="
                              activeSelectOptions['<?= (int)$optionId ?>'] = [$event.target.value];
                              $nextTick(() => {calculateTotalPrice()});
                            "
                    />
                    <span class="radio__control h-5 w-5" aria-hidden="true"></span>
                    <span class="radio__label ml-3"><?= /* @noEscape */
                        $radioPriceRenderer->getSelectionTitlePrice($selection) ?></span>
                </label>

                <div class="text-sm my-2">
                    <?= /* @noEscape */
                    $block->getTierPriceRenderer()->renderTierPrice($selection) ?>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>


    <!-- Quantity control -->
    <div class="contents">
        <label for="bundle-option-<?= (int)$optionId ?>-qty-input-<?= $isPopup ? 'mobile' : 'desktop' ?>"
               class="sr-only tracking-widest">
            <?= $escaper->escapeHtml(__('Quantity')) ?>
        </label>

        <input
            aria-describedby="option-label-<?= (int)$optionId ?>"
            id="bundle-option-<?= (int)$optionId ?>-qty-input-<?= $isPopup ? 'mobile' : 'desktop' ?>"
            form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
            name="bundle_option_qty[<?= (int)$optionId ?>]"
            class="input__field flex-shrink-0 basis-14 text-center bg-transparent h-9 px-3 disabled:opacity-75"
            type="number"
            min="0"
            value="<?= $escaper->escapeHtmlAttr($defaultQty) ?>"
            :value="getQtyValue(<?= (int)$optionId ?>)"
            x-on:change="
                setQtyValue(<?= (int)$optionId ?>, $event.target.value);
                calculateTotalPrice($dispatch)"
            <?php if (!$canChangeQty): ?> disabled <?php endif; ?>
            :disabled="getQtyDisabled(<?= (int)$optionId ?>)"
        />
    </div>
</div>
<?php
/**
 * Set the initial values on activeSelectOptions
 * Because we can't tell which options are selected when configuring a product that is in
 * the cart (through checkout/cart/configure) in the main Alpine component
 */
?>
<div class="hidden"
     @set-selected-options.window="activeSelectOptions['<?= (int)$optionId ?>'] = <?= $escaper->escapeHtmlAttr(json_encode($activeSelectOptions)) ?>">
</div>
