<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Reorder\Sidebar;

/** @var Escaper $escaper */
/** @var Sidebar $block */
/** @var ViewModelRegistry $viewModels  */
/** @var Customer $customer */
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$customer = $viewModels->require(Customer::class);

if (! $customer->customerLoggedIn()) {
    return '';
}

?>

<div x-data="RecentOrders('<?= $escaper->escapeJs(__("Cannot add product to cart.")) ?>')"
    @private-content-loaded.window="receiveReorderData($event.detail.data)"
    class="hidden mb-7"
    :class="{ 'hidden': !itemCount }"
    :aria-hidden="!itemCount"
    id="recent-orders-sidebar"
>
    <div class="bg-bg-400 rounded-md">
        <h2 class="text-text-500 text-lg font-bold p-4" id="block-reorder-heading">
            <?= $escaper->escapeHtml(__('Recently Ordered')) ?>
        </h2>
        <div class="p-4 border-t border-bg-600">
            <form method="post"
                action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
                id="reorder-validate-detail"
                aria-labelledby="block-reorder-heading"
            >
                <template x-if="itemCount">
                    <div>
                        <ol id="cart-sidebar-reorder" class="px-4 flex flex-col gap-3">
                            <template x-for="product in reorderItems" :key="product.product_sku">
                                <li>
                                    <label class="flex items-center gap-3" :for="checkboxId + product.product_sku">
                                        <input
                                            type="checkbox"
                                            name="order_items[]"
                                            :id="checkboxId + product.product_sku"
                                            :value="product.id"
                                            :aria-label="product.is_saleable
                                                ? hyva.str('<?= $escaper->escapeJs(__('Select product "%1" to reorder')) ?>', product.name)
                                                : hyva.str('<?= $escaper->escapeJs(__('Product "%1" is not salable')) ?>', product.name)
                                            "
                                            :disabled="!product.is_saleable"
                                            class="checkbox__input"
                                            @change="onCheckboxesChange($event)"
                                        >
                                            <span class="checkbox__control" aria-hidden="true">
                                                <?= $hyvaicons->renderHtml('checkmark') ?>
                                            </span>
                                            <a
                                                x-element-transition-trigger
                                                class="checkbox__label ml-0 hover:underline truncate"
                                                :href="product.url"
                                                :aria-describedby="!product.is_saleable || checkboxId + product.product_sku"
                                                x-text="product.name"
                                            ></a>
                                    </label>
                                </li>
                            </template>
                        </ol>

                        <div id="cart-sidebar-reorder-advice-container"></div>
                    </div>
                </template>
            </form>
        </div>
    </div>

    <div class="mt-5">
        <template x-if="errorMessage">
            <p class="field-error -mt-3 mb-3">
                <span class="messages" x-html="errorMessage"></span>
            </p>
        </template>

        <template x-if="isShowAddToCart">
            <button
                type="button"
                @click.prevent="addToCart('<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>')"
                class="button button--filled-primary max-md:w-full"
                :class="{'button--disabled': isLoading || !isCheckedItems()}"
                :disabled="isLoading || !isCheckedItems()"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to cart selected products from list')) ?>"
                data-addto="cart"
            >
            <span x-text="isLoading ?
                '<?= $escaper->escapeHtml(__('Adding...')) ?>' :
                '<?= $escaper->escapeHtml(__('Add to Cart')) ?>'"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </template>
        <a
            x-element-transition-trigger
            href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>#recentOrders"
            class="button button--ghost-primary max-md:w-full max-md:mt-4"
            aria-label="<?= $escaper->escapeHtmlAttr(__('View all recent orders')) ?>"
        >
            <?= $escaper->escapeHtml(__('View All')); ?>
        </a>
    </div>
</div>
