<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ReviewList;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ReviewList $viewModelCustomerReviews */
$viewModelCustomerReviews = $viewModels->require(ReviewList::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var StoreConfig $viewModelStoreConfig */
$viewModelStoreConfig = $viewModels->require(StoreConfig::class);

$productUrlSuffix = $viewModelStoreConfig->getStoreConfig('catalog/seo/product_url_suffix');
$baseUrl = $block->getBaseUrl();
$customerReviewsQuery = $viewModelCustomerReviews->getCustomerReviewsGraphQlQuery();
$storeCode = $viewModelStore->getStoreCode();
$ratingSteps = 5;

/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);

?>

<div id="content"
     x-data="ReviewList({
         baseUrl: '<?= $escaper->escapeHtmlAttr($baseUrl) ?>',
         productUrlSuffix: '<?= $escaper->escapeHtmlAttr($productUrlSuffix) ?>',
         storeCode: '<?= $escaper->escapeHtmlAttr($viewModelStore->getStoreCode()) ?>',
         customerReviewsQuery: `<?= $escaper->escapeHtmlAttr('{customer {' . $customerReviewsQuery . '}}'); ?>`
     })"
     @private-content-loaded.window="onPrivateContentLoaded(event.detail.data)">
    <template x-if="errors.length" x-for="(error, index) in errors" :key="index">
        <p :key="index" x-text="error" class="text error mb-3"></p>
    </template>
    <template x-if="!isLoading && !(reviews && reviews.length)">
        <p><?= $escaper->escapeHtml(__('You have submitted no reviews.')) ?></p>
    </template>
    <template x-if="reviews && reviews.length">
        <div>
            <template x-for="(review, index) in reviews" :key="index">
                <div class="mb-5 card p-5 rounded-xl bg-bg-400">
                    <div class="flex gap-5 lg:gap-5 flex-row mb-3">
                        <div class="flex-shrink-0 h-20 w-16 md:h-40 md:w-32 rounded-xl overflow-hidden bg-[--fade-in-bg]">
                            <img :src="review.product && review.product.image && review.product.image.url"
                                 :alt="review.product && review.product.image && review.product.image.label"
                                 class="w-full h-full object-cover mix-blend-darken"/>
                        </div>
                        <div>
                            <p class="font-bold text-lg mb-1">
                                <a :href="review.product && review.product.url_key && (
                                '<?= $escaper->escapeJs($baseUrl) ?>' +
                                 review.product.url_key  +
                                 '<?= $escaper->escapeJs($productUrlSuffix) ?>'
                               )"
                                   x-text="review.product && review.product.name">
                                </a>
                            </p>
                            <p class="mb-3">
                                <?= $escaper->escapeHtml(__('Created at')) ?>
                                <span x-text="review &&
                                review.created_at &&
                                new Date(review.created_at).toLocaleDateString()"
                                ></span>
                            </p>
                            <template x-for="(item, index) in review.ratings_breakdown" :key="index">
                                <div class="flex gap-4 mb-3 items-center">
                                    <div class="flex">
                                        <template x-for="i in <?= $escaper->escapeJs($ratingSteps) ?>">
                                            <div>
                                                <template x-if="i <= item.value">
                                                    <?= $hyvaicons->renderHtml('star', 'text-primary-500 text-xl'); ?>
                                                </template>
                                                <template x-if="i > item.value">
                                                    <?= $hyvaicons->renderHtml('star', 'text-secondary-700 text-xl'); ?>
                                                </template>
                                            </div>
                                        </template>
                                    </div>
                                    <div>
                                        <p x-text="Number(item.value).toFixed(1)" class="text-primary-600"></p>
                                    </div>
                                </div>
                            </template>
                            <div class="hidden lg:block mt-1">
                                <p class="font-bold lg:text-lg mb-3" x-text="review.summary"></p>
                                <p x-text="review.text"></p>
                            </div>
                        </div>
                    </div>
                    <div class="mt-1 lg:hidden">
                        <p class="font-bold text-lg mb-3" x-text="review.summary"></p>
                        <p x-text="review.text"></p>
                    </div>
                </div>
            </template>
        </div>
    </template>
    <template x-if="pageInfo && pageInfo.page_size && pageInfo.total_pages && pageInfo.total_pages > currentPage">
        <template x-if="totalPagesObject.length > 1">
            <div class="my-7 flex flex-col items-center">
                <a
                    @click.prevent="setCurrentPage(currentPage + 1)"
                    class="button btn--size-lg button--ghost-primary w-full cursor-pointer text-center lg:w-auto"
                    href="#" title="<?= $escaper->escapeHtmlAttr(__('Load more')) ?>"
                >
                    <?= __('Load more') ?>
                    <?= $hyvaicons->renderHtml('chevron', 'button__icon button__icon--right top-[1px] text-lg rotate-90'); ?>
                </a>
            </div>
        </template>
    </template>
</div>
