<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

?>
<!-- Inject satoshi custom js logic -->
<script type="module"
        src="<?= $escaper->escapeUrl($block->getViewFileUrl('assets/app.js')) ?>"
        defer
        crossorigin
></script>
<!-- Inject alpinejs through cdn -->
<script type="module"
        src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.0/dist/cdn.min.js"
        defer
></script>