<?php
declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar as Block;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Block $block */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);

$sortOptions = [];
foreach ($block->getAvailableOrders() ?? [] as $key => $option) {
    $value = $escaper->escapeHtml($key);
    $name = $escaper->escapeHtml($option);

    $ascendingLabel = match ($value) {
        'price' => "{$name}, low to high",
        'name' => 'Alphabetically, A-Z',
        default => "{$name}, ascending",
    };

    $descendingLabel = match ($value) {
        'price' => "{$name}, high to low",
        'name' => 'Alphabetically, Z-A',
        default => "{$name}, descending",
    };

    $sortOptions[] = ['value' => $value, 'name' => $ascendingLabel, 'dir' => 'asc'];
    $sortOptions[] = ['value' => $value, 'name' => $descendingLabel, 'dir' => 'desc'];
}

$defaultSort = $sortOptions[0]['value'] ?? $block->getCurrentOrder();
$defaultSortDir = 'asc';
$sortByLabel = 'Sort By';
$sortByLabelForFilter = str_replace(' ', '-', strtolower($escaper->escapeHtml($sortByLabel)));
$currentOrder = $block->getCurrentOrder();
$currentDirection = $block->getCurrentDirection();

?>

<form
    class="filter-form"
    id="FilterForm"
    x-show="$store.main.isMobile ? !isTopLevel : true"
    x-data="{isTopLevel: true}"
>
    <fieldset
        class="flex-1 md:border-t md:border-bg-600 md:py-5"
        x-init="initOption(
            <?= $escaper->escapeHtml(json_encode($sortOptions)) ?>,
            '<?= $escaper->escapeHtml($defaultSort) ?>',
            '<?= $defaultSortDir ?>',
            '<?= $block->getCurrentOrder() ?>',
            '<?= $block->getCurrentDirection() ?>'
        )"
        x-show="$store.main.isMobile ? currentName == '<?= $escaper->escapeHtml(__($sortByLabel)) ?>' : true"
    >
        <legend class="sr-only"><?= __($sortByLabel) ?></legend>

        <div
            class="group hidden h-11 w-full cursor-pointer items-center rounded-md py-3 md:flex md:px-2"
            x-ref="AccordionButton"
            @click="isTopLevel = !isTopLevel"
        >
            <h2 class="grow text-left text-text-500"><?= __($sortByLabel) ?></h2>
            <button type="button"
                    class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable"
                    :aria-label="'<?= __($sortByLabel) ?>'">
            <span
                class="transition-transform duration-300 -rotate-90"
                :class="!isTopLevel ? '!rotate-90' : ''"
                x-ref="AccordionIcon"
            >
                <?= $hyvaicons->renderHtml('chevron') ?>
            </span>
            </button>
        </div>

        <div x-cloak x-show="isTopLevel" x-ref="AccordionPanel" class="overflow-hidden md:px-2"
             :class="{
                'transition-none': $store.main.isReducedMotion,
                'transition': !$store.main.isReducedMotion,
            }"
        >
            <div class="md:pb-3 md:pt-2">
                <div class="flex flex-col gap-4 py-3" id="filter-<?= $sortByLabelForFilter ?>">
                    <div role="radiogroup" aria-label="<?= __('products.facets.sort_button') ?>">
                        <?php foreach ($sortOptions as $option): ?>
                            <?php
                            $value = $option['value'];
                            $name = $option['name'];
                            $dir = $option['dir'];
                            ?>
                            <div class="relative h-11 w-full">
                                <label
                                    class="radio mb-0 h-full w-full py-1"
                                    for="sort-<?= $value ?>-<?= $dir ?>"
                                >
                                    <input
                                        type="radio"
                                        class="radio__input"
                                        id="sort-<?= $value ?>-<?= $dir ?>"
                                        name="product_list_order"
                                        value="<?= $value ?>"
                                        :checked="'<?= $block->getCurrentDirection() ?>' === '<?= $dir ?>' && '<?= $block->getCurrentOrder() ?>' === '<?= $value ?>'"
                                        @change="setSortDir('<?= $dir ?>'); updateFilters()"
                                        aria-label="<?= $name ?>"
                                    >
                                    <span class="radio__control" aria-hidden="true"></span>
                                    <span class="radio__label text-md"><?= $name ?></span>
                                </label>
                            </div>
                        <?php endforeach; ?>
                        <input
                            type="hidden"
                            name="product_list_dir"
                            :value="this.sortDir"
                            aria-hidden="true"
                        />
                    </div>
                </div>

                <button
                    x-show="!getIsFilterValueSelected('product_list_order', '<?= $defaultSort ?>') || !getIsFilterValueSelected('product_list_dir', '<?= $defaultSortDir ?>')"
                    type="button"
                    class="link link--primary mt-4 hidden md:inline-block"
                    @click="setSortDir('<?= $defaultSortDir ?>'); resetCurrent('filter-<?= $sortByLabelForFilter ?>')"
                >
                    <?= __('Reset') ?>
                </button>
            </div>
        </div>
    </fieldset>
</form>
