<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;
use Satoshi\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$productId = $block->getProductId();
$attributeId = $block->getAttributeId();
$formId = $block->getFormId();

if (!$productId || !$attributeId) {
    return '';
}

$isPopup = $block->getData('is_popup') ?? false;

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

?>

<template x-if="optionIsEnabled(<?= (int)$attributeId ?>, item.id)">
    <label
        :for="`attribute-option-<?= (int)$productId ?>-${item.id}-<?= $isPopup ? 'mobile' : 'desktop' ?>`"
        class="button button--size-sm select-none transition-all ease-in-out relative bg-bg-500 has-[input:focus]:focus-ring"
        :class="{
            'button--outline-primary button--disabled': !optionIsActive(<?= (int)$attributeId ?>, item.id),
            'button--outline-primary border-2 bg-bg-700': selectedValues[<?= (int)$attributeId ?>] === item.id,
            'button--outline-secondary': selectedValues[<?= (int)$attributeId ?>] !== item.id,
        }"
        aria-label="getSwatchText(<?= (int)$attributeId ?>, item.id)"
        :aria-checked="selectedValues[<?= (int)$attributeId ?>] ? (selectedValues[<?= (int)$attributeId ?>] === item.id ? 'true' : 'false') : (index === 0)"
        :style="getSwatchBackgroundStyle(<?= (int)$attributeId ?>, item.id)"
        <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
            @mouseenter.self="activeTooltipItem = {
                attribute: '<?= (int)$attributeId ?>',
                item: item.id,
                index
            }; tooltipPositionElement = $event.target;"
            @mouseleave.self="activeTooltipItem = false"
        <?php endif; ?>
        x-data="{ show: false }"
        x-init="$nextTick(() => { show = true })"
        x-show="show"
        x-transition
    >
        <input
            :id="`attribute-option-<?= (int)$productId ?>-${item.id}-<?= $isPopup ? 'mobile' : 'desktop' ?>`"
            :value="item.id"
            name="super_attribute[<?= (int)$attributeId ?>]"
            class="-z-10 absolute opacity-0 [&:disabled]:cursor-not-allowed"
            type="radio"
            :required="getAllowedAttributeOptions(<?= (int)$attributeId ?>).filter(attributeOption => selectedValues[attributeOption]).length === 0"
            :aria-label="getSwatchText(<?= (int)$attributeId ?>, item.id)"
            aria-describedby="attribute-label-<?= $escaper->escapeHtmlAttr($productId . '-' . $attributeId) ?>"
            form="<?= $escaper->escapeHtmlAttr($formId) ?>"
            @change="optionIsActive(<?= (int)$attributeId ?>, item.id) && changeOption(<?= (int)$attributeId ?>, item.id)"
            role="radio"
            :tabindex="selectedValues[<?= (int)$attributeId ?>] ? (selectedValues[<?= (int)$attributeId ?>] === item.id ? '0' : '-1') : (index === 0) - 1"
            x-a11y-radio
            :disabled="!optionIsActive(<?= (int)$attributeId ?>, item.id)"
        >
        <template x-if="isTextSwatch(<?= (int)$attributeId ?>, item.id)">
            <span class="line-clamp-2 text-wrap text-sm md:text-md"
                  :class="{ 'line-through': !optionIsActive(<?= (int)$attributeId ?>, item.id) }"
                  x-html="getSwatchText(<?= (int)$attributeId ?>, item.id)"></span>
        </template>
        <template x-if="!isTextSwatch(<?= (int)$attributeId ?>, item.id)">
            <div class="contents">
                <div class="absolute inset-0 flex opacity-0 items-center justify-center transition-opacity" :class="{ '!opacity-100': !isTextSwatch(<?= (int)$attributeId ?>, item.id) && !optionIsActive(<?= (int)$attributeId ?>, item.id) }">
                    <div class="relative w-full h-full">
                        <div class="absolute top-1/2 left-1/2 w-3/4 h-0.5 bg-bg-400 transform -translate-x-1/2 -translate-y-1/2 rotate-45 rounded-full"></div>
                        <div class="absolute top-1/2 left-1/2 w-3/4 h-0.5 bg-bg-400 transform -translate-x-1/2 -translate-y-1/2 -rotate-45 rounded-full"></div>
                    </div>
                </div>
                <span
                    class="absolute flex size-full items-center justify-center text-lg text-primary-500 opacity-0"
                    :class="{
                        '!opacity-100': selectedValues[<?= (int)$attributeId ?>] === item.id,
                    }"
                >
                    <?= $hyvaicons->renderHtml('checkmark', 'stroke-bg-400 stroke-1 drop-shadow-lg') ?>
                </span>
            </div>
        </template>
    </label>
</template>
