<?php

declare(strict_types=1);

use Magento\Checkout\Block\Onepage\Success;
use Magento\Framework\Escaper;

/** @var Success $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()): ?>
    <a href="<?= $escaper->escapeUrl($block->getPrintUrl()) ?>"
       target="_blank"
       rel="noopener"
       class="button button--filled-primary"
       x-element-transition-trigger
    >
        <?= $escaper->escapeHtml(__('Print receipt')) ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php endif;?>
