<?php

use Satoshi\Theme\Block\Template;

/** @var Template $template */

$title = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Title')->getPageHeading();
?>

<div class="md:content-wrapper mt-[72px] h-[calc(100vh-72px)] overflow-y-scroll md:mx-auto">
  <?=
    $template
      ->setData([
        'isCartPage' => true,
        'title' => trim((string)$title) ? $escaper->escapeHtml($title) : null
      ])
      ->render('Magento_Theme::html/header/cart/minicart-overlay.phtml')
  ?>
</div>