<?php

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Cart $block */
/** @var Escaper $escaper */
/** @var Template $template */

$title = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Title')->getPageHeading();
?>

<div class="cart-main md:content-wrapper mt-[72px] md:mx-auto md:pb-10 max-md:min-h-[calc(100vh-106px)]">
  <?=
    $template
      ->setData([
        'isCartPage' => true,
        'title' => trim((string)$title) ? $escaper->escapeHtml($title) : null
      ])
      ->render('Magento_Theme::html/header/cart/minicart-overlay.phtml')
  ?>
</div>
