<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Template $template */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$isCartPage = $block->getData('isCartPage');
$title = $block->getData('title');
?>

<div
    <?php if (!$isCartPage) : ?>
        :inert="$store.main.isMobile ? $store.popup.currentPopup !== 'cart' : !$store.resizable.isVisible('cart-desktop')"
    <?php endif; ?>
    x-data="{
        get cartItems() { return $store.cart.cartItems },
        get isCartEmpty() { return !$store.cart.cartItems.length },
        get isRemoveContent() { return !$store.cart.cartItems.length },
        isTotalsExpanded: false
    }"
    class="contents"
>
    <div
        class="flex flex-col gap-5 rounded-md p-5 <?= $isCartPage ? '' : 'md:w-[--minicart-width] bg-bg-500' ?> md:gap-0 md:px-0 md:py-0 max-md:py-0 [.popup\_\_main_&]:px-2">
        <div
            class="flex items-center justify-between bg-bg-500 md:h-[--initial-height] md:min-h-14 md:rounded-md max-md:pb-4 <?= $isCartPage ? 'md:gap-4 md:flex-row-reverse md:justify-end' : 'md:px-6 sticky top-0 z-20' ?>">
            <h1 class="flex items-center text-lg text-text-500 <?= $isCartPage ? '' : 'md:text-md' ?>">
                <?php if (!$isCartPage) : ?>
                    <span class="button__icon mr-4 text-[1.5rem] max-md:hidden">
                        <?= $hyvaicons->renderHtml('cart-empty') ?>
                    </span>
                <?php endif; ?>

                <?= $title ?? __('Shopping cart') ?>
            </h1>
            <template x-if="!isCartEmpty">
                <div
                    class="delay-800 mr-1 flex justify-center align-middle transition-all duration-300 <?= $isCartPage ? 'hidden' : '' ?>"
                    :class="{'opacity-0': isCartEmpty}"
                >
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                        x-element-transition-trigger
                        class="link link--ghost"
                    >
                        <?= __('View cart') ?>
                        <span
                            x-text="`(${cartItems.reduce((total, item) => total + Number(item.qty), 0)})`"
                            class="mr-1"
                        ></span>
                    </a>
                </div>
            </template>
        </div>

        <div
            class="max-h-0 pb-0 opacity-0"
            :class="{
                'opacity-0 max-h-0 pb-0': !isCartEmpty,
                'opacity-1 max-h-80 pb-4 md:px-6': isCartEmpty,
                'hidden': !isRemoveContent
            }"
        >
            <p>
                <?= __('You did not add any products to cart yet!') ?>
            </p>
        </div>
        <div
            class="transition-opacity duration-300"
            :class="{
                'opacity-0': isCartEmpty,
                'opacity-1': !isCartEmpty,
                'hidden': isRemoveContent
            }"
            @transitionend="isRemoveContent = isCartEmpty"
        >
            <div class="contents <?= $isCartPage ? 'md:flex md:justify-between md:gap-5 md:pt-4' : '' ?>">
                <?=
                $template
                    ->setData(['isCartPage' => $isCartPage])
                    ->render('Magento_Theme::html/header/cart/minicart-items.phtml')
                ?>
                <div class="<?= !$isCartPage ? 'h-[140px]' : '' ?>"></div>

                <?php if (!$isCartPage) : ?>
                    <template
                        x-portal="$store.main.isMobile ? document.getElementById('popup-fixed-content-portal') : document.getElementById('cart-desktop-fixed')"
                    >
                        <div
                            :inert="$store.main.isMobile ? $store.popup.currentPopup !== 'cart' : !$store.resizable.isVisible('cart-desktop')"
                            class="contents"
                            x-show="!$store.main.isMobile || $store.popup.currentPopup === 'cart'"
                        >
                            <div
                                class="relative px-4 md:rounded-b-md max-md:px-3"
                                x-show="!isCartEmpty"
                            >
                                <?=
                                $template
                                    ->setData(['isCartPage' => $isCartPage])
                                    ->render('Magento_Theme::html/header/cart/minicart-totals.phtml')
                                ?>
                            </div>
                        </div>
                    </template>
                <?php else : ?>
                    <div id="cart-totals" class="contents">
                        <template
                            x-portal="$store.main.isMobile ? document.querySelector('body') : document.getElementById('cart-totals')">
                            <div
                                class="relative px-4 md:rounded-b-md max-md:px-3 max-md:fixed bottom-0 left-0 right-0 md:w-[--minicart-width] md:h-full md:border md:rounded-sm"
                                x-show="!isCartEmpty"
                            >
                                <?=
                                $template
                                    ->setData(['isCartPage' => $isCartPage])
                                    ->render('Magento_Theme::html/header/cart/minicart-totals.phtml')
                                ?>
                            </div>
                        </template>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
