<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div
    class="transition-preview"
    x-data="TransitionPreview()"
    :class="{
        'transition-preview--active': isActive,
        'is-transition': $store['transition'].isPreviewAnimating,
    }"
    style="--scroll-progress: 0; --offset-top: 400;"
    :style="{
        '--offset-top': offsetTop,
    }"
    x-ref="preview"
>
    <div
        class="transition-preview__wrapper"
        @click="(e) => {
            if ($refs.transitionContent.contains(e.target)) return;
            if ($refs.transitionBg === e.target) return;

            hidePreview();
        }"
    >
        <div class="content-wrapper relative mx-auto">
            <div x-ref="transitionBg" class="transition-preview__bg"></div>
        </div>
        <div
            x-ref="scrollContainer"
            :aria-hidden="!isActive"
            class="transition-preview__scroll"
            x-a11y-trap.watch="isActive"
        >
            <div class="content-wrapper relative mx-auto">
                <div class="transition-preview__content" x-ref="transitionContent">
                    <div id="PreviewContent"></div>
                    <div class="content-wrapper pointer-events-none fixed bottom-0 left-1/2 z-50 -translate-x-1/2">
                        <div
                            class="flex h-56 w-full items-end justify-center bg-gradient-to-t from-[--color-background-500] via-transparent to-transparent py-10 text-4xl opacity-[calc(1-var(--scroll-progress))]"
                        >
                            <div
                                class="animate-[bounce_2s_infinite] text-2xl text-text-50"
                                :class="{
                                    'animate-none': $store.main.isReducedMotion
                                }"
                            >
                                <div class="flex flex-col items-center [&>svg]:text-4xl">
                                    <?= $hyvaicons->renderHtml('scroll-mouse'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
