<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>
<div
    x-data="PasswordValidation(
    {
        zxcvbnScriptUrl: '<?= $escaper->escapeJs($block->getViewFileUrl('js/zxcvbn.js')) ?>',
        strengthLabels: {
            noPassword: '<?= $escaper->escapeJs(__('No Password')) ?>',
            weak: '<?= $escaper->escapeJs(__('Weak')) ?>',
            medium: '<?= $escaper->escapeJs(__('Medium')) ?>',
            strong: '<?= $escaper->escapeJs(__('Strong')) ?>',
            veryStrong: '<?= $escaper->escapeJs(__('Very Strong')) ?>'
        },
        validationMessage: '<?= $escaper->escapeJs(__('The password must include at least %1 or more of: uppercase (A-Z), lowercase (a-z), number, and symbol.')) ?>'
    })"
></div>
