<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Recent;
use Magento\Sales\Helper\Reorder;
use Magento\Sales\Model\Order;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Recent $block */
/** @var ViewModelRegistry $viewModels */

/** @var ViewModelRegistry $viewModels */
$hyvaicons = $viewModels->require(SvgIcons::class);
/** @var Order[] $orders */
$orders = $block->getOrders();
$count = count($orders);

$extraActions = [];
if ($extraActionTitleBlocks = $block->getLayout()->getChildBlocks('order-list-extra-action-titles')) {
    foreach ($extraActionTitleBlocks as $alias => $extraActionTitleBlock) {
        $extraActions[$alias] = $extraActionTitleBlock->toHtml();
    }
    $extraActions = array_filter($extraActions, function ($output, string $alias) use ($block): bool {
        return trim($output) && $block->getLayout()->getChildBlock('order-list-extra-action-buttons', $alias);
    }, ARRAY_FILTER_USE_BOTH);
}
?>
<?php if ($count > 0): ?>
    <div
        class="mt-8"
        x-data="{ tabIndex: -1 }"
    >
        <div class="mb-5 flex flex-col md:flex-row gap-4 md:justify-between md:items-center">
            <h2
                id="recentOrders"
                class="text-text-500 text-lg font-bold"
                @focus="tabIndex = 0;"
                @blur="tabIndex = -1"
                :tabindex="tabIndex"
            ><?= $escaper->escapeHtml(__('Recent Orders')) ?></h2>
            <a
                class="text-primary-500 hover:text-primary-700 transition-colors"
                href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
                aria-label="<?= $escaper->escapeHtmlAttr(__('View all orders')) ?>"
                x-element-transition-trigger
            ><?= $escaper->escapeHtml(__('View all orders')) ?></a>
        </div>

        <div class="space-y-5 break-words">
            <?= $block->getChildHtml() ?>
            <?php foreach ($orders as $order): ?>
                <div class="bg-bg-400 grid lg:grid-cols-6 gap-4 p-5 rounded-xl">
                    <div class="grid grid-cols-2 lg:flex lg:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Order')) ?>
                        </div>
                        <div id="order<?= $escaper->escapeHtmlAttr($order->getRealOrderId()) ?>">
                            #<?= $escaper->escapeHtml($order->getRealOrderId()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 lg:flex lg:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Date')) ?>
                        </div>
                        <div>
                            <?php
                            $date = $order->getCreatedAt();
                            $formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
                            $formattedDate = $block->formatDate($date, $formatLong);
                            if (!$block->getDateFormat()) {
                                try {
                                    $formattedDate = (new DateTime($date))->format('M d, Y');
                                } catch (Exception $e) {
                                    $formattedDate = $block->formatDate($date, $formatLong);
                                }
                            }
                            ?>
                            <span aria-hidden="true">
                                <?= $escaper->escapeHtmlAttr($formattedDate); ?>
                            </span>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 lg:flex lg:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Ship to')) ?>
                        </div>
                        <div>
                            <?= $order->getShippingAddress() ? $escaper->escapeHtml($order->getShippingAddress()->getName()) : '&nbsp;' ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 lg:flex lg:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Order total')) ?>
                        </div>
                        <div>
                            <?= /* @noEscape */
                            $order->formatPrice($order->getGrandTotal()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 lg:flex lg:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Status')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($order->getStatusLabel()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 lg:flex lg:flex-col md:items-end gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('View')) ?>
                            <?php if ($this->helper(Reorder::class)->isAllow()): ?>
                                / <?= $escaper->escapeHtml(__('Reorder')) ?>
                            <?php endif; ?>
                            <?php foreach ($extraActions as $extraActionTitle): ?>
                                / <?= /** @noEscape */
                                $extraActionTitle ?>
                            <?php endforeach; ?>
                        </div>
                        <div class="flex gap-5 items-center">
                            <?php // 'received' is an order status added in Magento_AsyncOrder in Adobe Commerce ?>
                            <?php // The condition will always return 'true' in Magento Open Source ?>
                            <?php if ($order->getStatus() !== 'received'): ?>
                                <a
                                    class="text-primary-500 w-5 h-5"
                                    title="<?= $escaper->escapeHtmlAttr(__('View Order')) ?>"
                                    href="<?= $escaper->escapeUrl($block->getViewUrl($order)) ?>"
                                    x-element-transition-trigger
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                                >
                                    <?= $hyvaicons->renderHtml('eye', 'w-full h-full', attributes: ['title' => 'View']) ?>
                                </a>

                                <?php if ($this->helper(Reorder::class)->canReorder($order->getEntityId())): ?>
                                    <?php $formData = json_decode(
                                        $this->helper(PostHelper::class)->getPostData(
                                            $block->getReorderUrl($order)
                                        ),
                                        true
                                    ) ?>
                                    <form
                                        action="<?= $escaper->escapeUrl($formData['action']) ?>"
                                        method="post"
                                        class="inline-flex items-center"
                                        x-data="RecentOrders"
                                        @submit.prevent="onReorder($event)"
                                    >
                                        <?= $block->getBlockHtml('formkey'); ?>
                                        <input type="hidden" name="data" value='<?= /* @noEscape */
                                        json_encode($formData['data']) ?>'>
                                        <button
                                            title="<?= $escaper->escapeHtmlAttr(__('Reorder')) ?>"
                                            type="submit"
                                            class="text-transparent w-5 h-5"
                                            :class="{ 'button--disabled animate-spin': isLoading }"
                                            :disabled="isLoading"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Reorder') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                                        >
                                            <?= $hyvaicons->renderHtml('reload', 'w-full h-full', attributes: ['title' => 'Reorder']) ?>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <button
                                        type="button"
                                        disabled
                                        class="text-transparent w-5 h-5 opacity-50"
                                    >
                                        <?= $hyvaicons->renderHtml('reload', 'w-full h-full', attributes: ['title' => '', 'aria-hidden' => 'true']) ?>
                                    </button>
                                <?php endif ?>
                                <?php foreach (array_keys($extraActions) as $alias): ?>
                                    <?php $button = $block->getLayout()->getChildBlock('order-list-extra-action-buttons', $alias) ?>
                                    <?= $button->assign('order', $order)->setData('order', $order)->toHtml() ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
