<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var ViewModelRegistry $viewModels */
/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div
    class="align-start animate-on-transition mb-8 flex flex-col"
>
    <button class="flex items-center justify-between"
            type="button"
            x-ref="AccordionButton"
            :aria-expanded="isExpanded"
            aria-controls="attributes_panel"
            aria-labelledby="attributes_label"
    <span class="text-base font-bold leading-tight">
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
    </span>
    <span x-ref="AccordionIcon" class="button button--outline-secondary icon-button icon-button--size-xs">
        <?= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
    </span>
    </button>
</div>
