<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var ViewModelRegistry $viewModels */
/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div x-data="Accordion('true', 300)" x-effect="$store.information.isExpanded = isExpanded"
     class="align-start animate-on-transition mb-8 flex flex-col px-4 md:p-0"
>
    <button class="flex items-center justify-between"
            id="controlsAccordionItemOne" type="button"
            aria-controls="accordionItemOne"
            x-ref="AccordionButton"
            :aria-expanded="isExpanded"
    <span class="text-base font-bold leading-tight">
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
    </span>
    <span x-ref="AccordionIcon" class="button button--outline-secondary icon-button icon-button--size-xs">
        <?= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
    </span>
    </button>
</div>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.store('information', {
            isExpanded: true
        });
    });
</script>
