<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()) {
    return;
}

$cssClasses = $block->getData('css_classes') ?? 'prose';

?>
<div class="border-black border-b">
    <div x-ref="AccordionPanel"
         :inert="!isExpanded"
         class="overflow-hidden"
         x-cloak
         id="description_panel"
         role="region"
         aria-labelledby="description_label"
    >
        <div class="rte mt-3 overflow-hidden text-text-100 contrast-more:text-secondary-700">
            <?= $productViewModel->productAttributeHtml($product, $product->getDescription(), 'description') ?>
        </div>
    </div>
</div>
