<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div
     class="align-start animate-on-transition mb-8 flex flex-col border-none"
>
    <button class="flex items-center justify-between"
            type="button"
            x-ref="AccordionButton"
            :aria-expanded="isExpanded"
            aria-controls="description_panel"
            aria-labelledby="description_label"
    <span class="text-base font-bold leading-tight">
                <?= $escaper->escapeHtml(__('Description')) ?> /
                <?= $escaper->escapeHtml($product->getName()) ?>
            </span>
    <span x-ref="AccordionIcon" class="button button--outline-secondary icon-button icon-button--size-xs">
        <?= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
    </span>
    </button>
</div>
