<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var SvgIcons $hyvaicons */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */

$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()) {
    return;
}

$cssClasses = $block->getData('css_classes') ?? 'prose';

?>
<div class="align-start animate-on-transition mb-8 flex flex-col px-4 md:p-0" x-data="Accordion('true', 300)">
    <button
        class="group flex items-center justify-between text-start"
        x-ref="AccordionButton"
        type="button"
        :aria-expanded="isExpanded"
        aria-controls="attributes_panel"
        aria-labelledby="attributes_label"
    >
        <p class="text-base font-semibold leading-tight text-text-500">
            <?= $escaper->escapeHtml(__('Description')) ?> /
            <?= $escaper->escapeHtml($product->getName()) ?>
        </p>
        <span x-ref="AccordionIcon" class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable">
            <?= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
        </span>
    </button>
    <div
        x-ref="AccordionPanel"
        :inert="!isExpanded"
        role="region"
        class="overflow-hidden"
        id="description_panel"
        aria-labelledby="description_label"
        x-cloak
    >
        <div class="rte mt-3 overflow-hidden">
            <?= $productViewModel->productAttributeHtml($product, $product->getDescription(), 'description') ?>
        </div>
    </div>
</div>
