<?php

declare(strict_types=1);

/** @var Details $block */
/** @var Escaper $escaper */

use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

$titleRenderer = $block->getChildBlock('product.section.title.renderer');
$defaultTitleTemplate = $titleRenderer->getTemplate();

?>
<div class="grid grid-cols-1 gap-8">
    <?php
    foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName) {
        $sectionBlock  = $block->getLayout()->getBlock($sectionName);
        $sectionHtml   = (string) $sectionBlock->toHtml();
        $titleTemplate = $sectionBlock->getData('title_template') ?? $defaultTitleTemplate;

        if (empty(trim($sectionHtml))) {
            continue;
        }
        ?>
        <section x-data="Accordion('true', 300)" id="<?= $escaper->escapeHtmlAttr($sectionBlock->getNameInLayout()) ?>">
            <?=
            $titleRenderer->setTemplate($titleTemplate)
                ->assign('sectionBlock', $sectionBlock)
                ->toHtml()
            ?>
            <div class="card w-full">
                <?= /** @noEscape  */ $sectionHtml ?>
            </div>
        </section>
    <?php } ?>
</div>
