<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Downloadable\Block\Catalog\Product\Samples;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Samples $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<?php if ($block->hasSamples()): ?>
    <div class="flex justify-between items-center mb-3">
        <h2 class="font-semibold text-text-500">
            <?= $escaper->escapeHtml($block->getSamplesTitle()) ?>
        </h2>
        <button
            type="button"
            class="button button--outline-secondary icon-button icon-button--size-xs md:hidden"
            aria-label="<?= __('Close') ?>"
            @click.prevent="hideProductActions()"
        >
            <?= $hyvaicons->renderHtml('close') ?>
        </button>
    </div>

    <?php $samples = $block->getSamples() ?>
    <div class="flex flex-col gap-3 mb-5">
        <?php foreach ($samples as $sample): ?>
            <a href="<?= $escaper->escapeHtml($block->getSampleUrl($sample)) ?>"
                download
                <?= $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '' ?>
                class="flex gap-2 items-center">
                <?= $heroicons->documentDownloadHtml(); ?>
                <?= $escaper->escapeHtml($sample->getTitle()) ?>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
