<?php
declare(strict_types=1);

use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Helper\Address as AddressHelper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Company $block */

$validationClass = $this->helper(AddressHelper::class)->getAttributeValidationClass('company') ?: '';
?>

<?= $template
    ->setData([
        'type' => 'text',
        'name' => 'company',
        'id' => 'company',
        'label' => 'Company',
        'value' => $block->getCompany(),
        'placeholder' => 'Enter your company name',
        'class' => $validationClass,
        'attributes' => $block->isRequired() ? 'required' : '',
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>
