<?php
declare(strict_types=1);

use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var Company $block */

$validationClass = $this->helper(AddressHelper::class)->getAttributeValidationClass('company');
?>

<?= $template
    ->setData([
        'type' => 'text',
        'name' => 'company',
        'id' => 'company',
        'label' => 'Company',
        'value' => $block->getCompany(),
        'placeholder' => 'Enter your company name',
        'required' => $block->isRequired(),
        'class' => 'form-input ' . $validationClass,
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>
