<?php

declare(strict_types=1);

use Magento\Customer\Block\Widget\Gender;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Gender $block */

?>

<?= $template
    ->setData([
        'type' => 'select',
        'name' => $block->getFieldName('gender'),
        'id' => $block->getFieldId('gender'),
        'label' => $block->getStoreLabel('gender'),
        'value' => $block->getGender(),
        'options' => array_column($block->getGenderOptions(), 'label', 'value'),
        'attributes' => $block->isRequired() ? 'required' : '',
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>
