<?php

declare(strict_types=1);

use Magento\Customer\Block\Widget\Name;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Name $block */
/** @var Escaper $escaper */

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>

<?php if ($prefix): ?>
    <?= $template
        ->setData([
            'type' => $block->getPrefixOptions() === false ? 'text' : 'select',
            'name' => $block->getFieldName('prefix'),
            'id' => $block->getFieldId('prefix'),
            'label' => $block->getStoreLabel('prefix'),
            'value' => $block->getObject()->getPrefix(),
            'placeholder' => $block->getStoreLabel('prefix'),
            'required' => $block->isPrefixRequired(),
            'class' => 'form-input ' . $block->getAttributeValidationClass('prefix'),
            'additional_attributes' => $block->isPrefixRequired() ? 'required' : '',
            'options' => $block->getPrefixOptions(),
        ])
        ->render('Magento_Customer::html/_form-field.phtml');
    ?>
<?php endif; ?>

<?= $template
    ->setData([
        'type' => 'text',
        'name' => $block->getFieldName('firstname'),
        'id' => $block->getFieldId('firstname'),
        'label' => $block->getStoreLabel('firstname'),
        'value' => $block->getObject()->getFirstname(),
        'placeholder' => $block->getStoreLabel('firstname'),
        'required' => true,
        'class' => 'form-input ' . $block->getAttributeValidationClass('firstname'),
        'additional_attributes' => '@input.debounce="onChange"',
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>

<?php if ($middle): ?>
    <?= $template
        ->setData([
            'type' => 'text',
            'name' => $block->getFieldName('middlename'),
            'id' => $block->getFieldId('middlename'),
            'label' => $block->getStoreLabel('middlename'),
            'value' => $block->getObject()->getMiddlename(),
            'placeholder' => $block->getStoreLabel('middlename'),
            'required' => $block->isMiddlenameRequired(),
            'class' => 'form-input ' . $block->getAttributeValidationClass('middlename'),
            'additional_attributes' => '@input.debounce="onChange"',
        ])
        ->render('Magento_Customer::html/_form-field.phtml');
    ?>
<?php endif; ?>

<?= $template
    ->setData([
        'type' => 'text',
        'name' => $block->getFieldName('lastname'),
        'id' => $block->getFieldId('lastname'),
        'label' => $block->getStoreLabel('lastname'),
        'value' => $block->getObject()->getLastname(),
        'placeholder' => $block->getStoreLabel('lastname'),
        'required' => true,
        'class' => 'form-input ' . $block->getAttributeValidationClass('lastname'),
        'additional_attributes' => '@input.debounce="onChange"',
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>

<?php if ($suffix): ?>
    <?= $template
        ->setData([
            'type' => $block->getSuffixOptions() === false ? 'text' : 'select',
            'name' => $block->getFieldName('suffix'),
            'id' => $block->getFieldId('suffix'),
            'label' => $block->getStoreLabel('suffix'),
            'value' => $block->getObject()->getSuffix(),
            'placeholder' => $block->getStoreLabel('suffix'),
            'required' => $block->isSuffixRequired(),
            'class' => 'form-input ' . $block->getAttributeValidationClass('suffix'),
            'options' => $block->getSuffixOptions() ?: [],
        ])
        ->render('Magento_Customer::html/_form-field.phtml');
    ?>
<?php endif; ?>
