<?php
declare(strict_types=1);

use Magento\Customer\Block\Widget\Name;
use Magento\Framework\Escaper;

/** @var Name $block */
/** @var Escaper $escaper */

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>
<?php if ($prefix): ?>
    <div class="field field-reserved">
        <label class="sr-only tracking-widest" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>">
            <span><?= $escaper->escapeHtml($block->getStoreLabel('prefix')) ?></span>
        </label>
        <div>
            <?php if ($block->getPrefixOptions() === false): ?>
                <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                       name="<?= $escaper->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                    <?= $block->isPrefixRequired() ? ' required' : '' ?>
                       value="<?= $escaper->escapeHtmlAttr($block->getObject()->getPrefix()) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                       placeholder="<?= $block->getStoreLabel('prefix') ?>"
                       class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                    <?= $block->isPrefixRequired() ? ' required' : '' ?>
                >
            <?php else: ?>
                <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                    <?= $block->isPrefixRequired() ? ' required' : '' ?>
                        title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                    <?= $block->isPrefixRequired() ? ' required' : '' ?> >
                    <?php foreach ($block->getPrefixOptions() as $option): ?>
                        <option value="<?= $escaper->escapeHtmlAttr($option) ?>"
                            <?php if ($block->getObject()->getPrefix() == $option): ?>
                                selected="selected"
                            <?php endif; ?>>
                            <?= $escaper->escapeHtml(__($option)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
    <div class="field field-reserved">
        <label class="sr-only tracking-widest" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('firstname')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('firstname')) ?>
            </span>
        </label>
        <div>
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
                   required
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('firstname')) ?>"
                   placeholder="<?= $block->getStoreLabel('firstname') ?>"
                   class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                   @input.debounce="onChange"
                <?= ($block->getAttributeValidationClass('firstname') == 'required-entry') ? ' required' : '' ?>
            >
        </div>
    </div>
<?php if ($middle): ?>
    <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
    <div class="field field-reserved">
        <label class="sr-only tracking-widest" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('middlename')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('middlename')) ?>
            </span>
        </label>
        <div>
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getMiddlename()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('middlename')) ?>"
                   placeholder="<?= $block->getStoreLabel('middlename') ?>"
                   class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                   @input.debounce="onChange"
                <?= $isMiddlenameRequired ? ' required' : '' ?>
            >
        </div>
    </div>
<?php endif; ?>
    <div class="field field-reserved">
        <label class="sr-only tracking-widest" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('lastname')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('lastname')) ?>
            </span>
        </label>
        <div>
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
                   required
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('lastname')) ?>"
                   placeholder="<?= $block->getStoreLabel('lastname') ?>"
                   class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                   @input.debounce="onChange"
                <?= ($block->getAttributeValidationClass('lastname') == 'required-entry') ? ' required' : '' ?>
            >
        </div>
    </div>
<?php if ($suffix): ?>
    <div class="field field-reserved">
        <label class="sr-only tracking-widest" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('suffix')) ?>
            </span>
        </label>
        <div>
            <?php if ($block->getSuffixOptions() === false): ?>
                <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                       name="<?= $escaper->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                       value="<?= $escaper->escapeHtmlAttr($block->getObject()->getSuffix()) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                       placeholder="<?= $block->getStoreLabel('suffix') ?>"
                       class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                    <?= $block->isSuffixRequired() ? ' required' : '' ?>
                >
            <?php else: ?>
                <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                        title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                    <?= $block->isSuffixRequired() ? ' required' : '' ?>
                >
                    <?php foreach ($block->getSuffixOptions() as $option): ?>
                        <option value="<?= $escaper->escapeHtmlAttr($option) ?>"
                            <?php if ($block->getObject()->getSuffix() == $option): ?>
                                selected="selected"
                            <?php endif; ?>
                        >
                            <?= $escaper->escapeHtml(__($option)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
