<?php
declare(strict_types=1);

use Magento\Customer\Block\Widget\Telephone;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Telephone $block */

?>

<?= $template
    ->setData([
        'type' => 'tel',
        'name' => 'telephone',
        'id' => 'telephone',
        'label' => __('Phone Number'),
        'value' => $block->getTelephone(),
        'placeholder' => __('Enter your phone number'),
        'class' => $block->getAttributeValidationClass('telephone') ?: '',
        'attributes' => ($block->isRequired() ? 'required ' : '') . 'data-validate=\'{"telephone": true}\' @input.debounce="onChange"',
    ])
    ->render('Magento_Customer::html/_form-field.phtml');
?>
