<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Eav\Model\Entity\Attribute $attribute */
/** @var \Magento\CatalogSearch\Helper\Data $catalogSearchHelper */
$catalogSearchHelper = $block->getData('catalogSearchHelper');

$code = $attribute->getAttributeCode();
$maxQueryLength = $catalogSearchHelper->getMaxQueryLength();
?>
<div>
    <input type="text"
           name="<?= $escaper->escapeHtmlAttr($code) ?>"
           id="<?= $escaper->escapeHtmlAttr($code) ?>"
           value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute)) ?>"
           title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
           placeholder="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
           class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
           maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>"
    />
</div>