<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var SvgIcons $hyvaicons */

$wishlistViewModel = $viewModels->require(Wishlist::class);
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<?php if ($wishlistViewModel->isEnabled()): ?>
    <div
        x-data="Wishlist"
        @private-content-loaded.window="receiveWishlistData($event.detail.data)"
    >
        <template x-if="itemCount">
            <div class="mt-8">
                <h2 class="mb-5" id="wishlist-sidebar">
                    <strong
                        class="text-text-500 text-lg font-bold leading-6 mr-3"
                    ><?= $escaper->escapeHtml(__('My wish list')) ?></strong><span class="font-medium leading-5 capitalize" x-html="wishlistCountLabel"></span>
                </h2>
                <ul class="flex flex-col gap-5 mb-5 p-5 rounded-xl bg-bg-400" aria-labelledby="wishlist-sidebar">
                    <template x-for="product in wishlistItems">
                        <li class="flex items-start">
                            <a
                                :href="product.product_url"
                                class="block mb-3 w-12 h-14 shrink-0 mr-4 rounded-xl overflow-hidden bg-[--fade-in-bg]"
                                tabindex="-1"
                                aria-hidden="true"
                                x-element-transition-trigger
                            >
                                <img
                                    :src="product.image.src"
                                    alt=""
                                    loading="lazy"
                                    class="mix-blend-darken object-center max-h-full object-cover h-full w-full"
                                >
                            </a>
                            <div class="w-[calc(100%-102px)]">
                                <strong class="block text-text-500 leading-5 font-bold mb-1 overflow-hidden text-ellipsis text-nowrap">
                                    <a
                                        :href="product.product_url"
                                        x-element-transition-trigger
                                        :title="product.product_name"
                                        x-html="product.product_name"
                                    ></a>
                                </strong>
                                <div class="font-normal mb-4 [&_.price]:text-text-400" x-html="product.product_price"></div>
                                <template x-if="product.product_is_saleable_and_visible">
                                    <div>
                                        <template x-if="!product.product_has_required_options">
                                            <button
                                                type="button"
                                                @click.prevent='setActionBtnText(`add-to-cart-${product.product_id}`); addToCartFromWishlistSidebar(product.add_to_cart_params, product.product_sku)'
                                                class="button button--filled-primary"
                                                :aria-label="hyva.str('<?= $escaper->escapeJs(__('Add to Cart %1'))  ?>', product.product_name)"
                                                data-addto="cart"
                                                :class="isLoading && 'button--disabled'"
                                                :disabled="isLoading"
                                            >
                                                <span x-text="isLoading && actionBtnText === `add-to-cart-${product.product_id}` ?
                                                      '<?= $escaper->escapeHtml(__('Adding...')) ?>' :
                                                      '<?= $escaper->escapeHtml(__('Add to Cart')) ?>'">
                                                      <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                </span>
                                            </button>
                                        </template>
                                    </div>
                                </template>
                            </div>
                            <button
                                type="button"
                                @click.prevent="removeFromWishlistSidebar(product.delete_item_params)"
                                :aria-label="hyva.str('<?= $escaper->escapeJs(__('Remove product "%1" from My Wish List')) ?>', product.product_name)"
                                class="h-[30px] w-[30px] ml-auto inline-flex items-center justify-center text-primary-bg rounded-lg border"
                                :class="isLoading && 'button--disabled'"
                                :disabled="isLoading"
                            >
                                <?= $hyvaicons->renderHtml('close', 'text-lg', attributes: ['title' => $escaper->escapeHtmlAttr(__('remove'))]); ?>
                            </button>
                        </li>
                    </template>
                </ul>
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Wish List page')); ?>"
                    class="button button--outline-primary bg-bg-400 max-md:w-full"
                    x-element-transition-trigger
                >
                    <?= $escaper->escapeHtml(__('Go to wish list')); ?>
                </a>
            </div>
        </template>
    </div>
<?php endif ?>
