<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Customer\Wishlist;
use Magento\Wishlist\Helper\Data as WishlistHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Wishlist $block */

$wishlistHelper = $this->helper(WishlistHelper::class);
$successMessage = $block->getSuccessMessage();
$errorMessage = $block->getErrorMessage();
?>

<?php if ($wishlistHelper->isAllow()): ?>
    <div class="toolbar wishlist-toolbar"><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form id="wishlist-view-form"
          x-data="WishListPage(
              <?= $escaper->escapeHtmlAttr($block->getAddAllToCartParams()) ?>
          )"
          action="
          <?= $escaper->escapeUrl(
              $block->getUrl(
                  'wishlist/index/update',
                  ['wishlist_id' => $block->getWishlistInstance()->getId()]
              )
          ) ?>"
          method="post"
          @submit.prevent="updateWishList(event)"
    >
        <?php if ($successMessage): ?>
            <div class="text-green-700 mb-3">
                <span><?= $successMessage; ?></span>
            </div>
        <?php elseif ($errorMessage): ?>
            <div class="field-error mb-3">
                <span class="messages"><?= $escaper->escapeHtml($errorMessage); ?></span>
            </div>
        <?php endif; ?>

        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()): ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else: ?>
            <div class="message info empty">
                <span>
                    <?= $escaper->escapeHtml(__('You have no items in your wish list.')) ?>
                </span>
            </div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
        <div class="flex gap-4 flex-col md:flex-row flex-wrap mt-5">
            <?= $block->getChildHtml('control_buttons') ?>

            <a class="button button--ghost-primary"
               href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
               x-element-transition-trigger
            >
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </form>
    <div class="toolbar wishlist-toolbar">
        <?= $block->getChildHtml('wishlist_item_pager') ?>
    </div>
<?php endif ?>
