<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var SvgIcons $hyvaicons */

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');

$hyvaicons = $viewModels->require(SvgIcons::class);
$title = $block->getData('title') ?? __('Join Our Newsletter.');
$subtitle = $block->getData('subtitle');
$buttonLabel = $block->getData('button_label') ?? __('Subscribe');
$isWrapped = $block->getData('wrapped') == 'true';
?>

<div
    class="md:max-w-screen-sm mx-auto flex flex-col items-stretch gap-5 rounded-md border-1 border-transparent px-5 py-6 md:min-w-[35%] md:gap-4 md:p-7 h-fit <?= $isWrapped ? 'bg-secondary-500 md:bg-bg-600' : '' ?>">
    <h2 class="text-lg"><?= $escaper->escapeHtml($title) ?></h2>
    <?php if (!empty($subtitle)): ?>
        <p class="text-text-500"><?= $escaper->escapeHtml($subtitle) ?></p>
    <?php endif; ?>
    <form
        class="flex flex-col gap-3 items-stretch md:gap-4"
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        x-data="Newsletter('<?= __('Something went wrong with the subscription.') ?>')"
        @submit.prevent="function($event) {
            // do not rename $form, the variable is the expected name in the recaptcha output
            const $form = $event.target;

            <?= $recaptcha ? $escaper->escapeHtmlAttr($recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER)) : '' ?>

            if (this.errors === 0) {
                this.submitForm();
            }
        }"
        id="newsletter-validate-detail"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Subscribe to Newsletter')) ?>"
    >
        <div>
            <label for="newsletter-subscribe" class="sr-only tracking-widest"><?= $escaper->escapeHtml(__('Email address')) ?></label>
            <input
                autocomplete="email"
                autocorrect="off"
                autocapitalize="off"
                id="newsletter-subscribe"
                type="email"
                name="email"
                class="input__field input__field--outline bg-bg-500 md:px-5 md:py-4"
                :class="{
                    'border-error': displayErrorMessage
                }"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Email address')) ?>"
                aria-required="true"
                required
                :autofocus="displayErrorMessage"
                :aria-invalid="displayErrorMessage"
                :aria-describedby="displayErrorMessage ? 'error_newsletter' : successMessage ? 'success_newsletter' : undefined"
            >
            <template x-if="displayErrorMessage">
                <p class="field-error">
                    <template x-for="errorMessage in errorMessages">
                        <span class="messages" x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>

        <?= $block->getBlockHtml('formkey') ?>

        <?php if ($recaptcha && $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER)): ?>
            <div
                id="newsletter-recaptcha-container"
                class="origin-top-left scale-[0.8] max-w-[245px] sm:scale-100 sm:max-w-none md:scale-[0.65] lg:scale-90 xl:scale-100"
            >
                <?= $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER); ?>
            </div>
        <?php endif; ?>

        <button
            type="submit"
            class="button button--filled-primary w-full"
            :class="{
                'button--disabled': isLoading
            }"
            :disabled="isLoading"
        >
            <?= $escaper->escapeHtml($buttonLabel) ?>
        </button>
        <span
            class="newsletter-form__message newsletter-form__message--success form__message"
            id="success_newsletter"
            tabindex="-1"
            autofocus
            x-show="successMessage"
            x-cloak
        >
            <?= $hyvaicons->renderHtml('success', 'inline'); ?>
            <span x-html="successMessage"></span>
        </span>
        <?php if($recaptcha && $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER)): ?>
            <div class="mt-3 text-sm">
                <?= $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) ?>
            </div>
        <?php endif; ?>
    </form>
</div>
