<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() &&
    $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit"
            name="save_and_share"
            title="<?= $escaper->escapeHtmlAttr(__('Share Wish List')) ?>"
            class="button button--outline-primary"
            :class="isLoading && 'button--disabled'"
            :disabled="isLoading"
            @click='setBtnText("share-wishlist")'
    >
        <span x-text="isLoading && btnText === 'share-wishlist' ?
            '<?= $escaper->escapeHtml(__('Sharing...')) ?>' :
            '<?= $escaper->escapeHtml(__('Share Wish List')) ?>'">
            <?= $escaper->escapeHtml(__('Share Wish List')) ?>
        </span>
    </button>
<?php endif;?>
