<?php

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() &&
    $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button
        type="submit"
        name="save_and_share"
        title="<?= $escaper->escapeHtmlAttr(__('Share wish list')) ?>"
        class="button button--outline-primary bg-bg-400"
    >
        <span>
            <?= $escaper->escapeHtml(__('Share wish list')) ?>
        </span>
    </button>
<?php endif;?>
