<?php

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button
        type="button"
        @click.prevent="addAllItemsToCart()"
        data-role="all-tocart"
        title="<?= $escaper->escapeHtmlAttr(__('Add all to cart')) ?>"
        class="button button--filled-primary"
    >
        <span><?= $escaper->escapeHtml(__('Add all to cart')) ?></span>
    </button>
<?php endif;?>
