<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button
        type="button"
        @click.prevent='setActionBtnText("add-all-to-cart"); addAllItemsToCart()'
        data-role="all-tocart"
        title="<?= $escaper->escapeHtmlAttr(__('Add all to cart')) ?>"
        class="button button--filled-primary"
        :class="isLoading ? 'button--disabled' : ''"
        :disabled="isLoading"
    >
        <span x-text="isLoading && actionBtnText === 'add-all-to-cart' ?
            '<?= $escaper->escapeHtml(__('Adding...')) ?>' :
            '<?= $escaper->escapeHtml(__('Add All to Cart')) ?>'">
            <?= $escaper->escapeHtml(__('Add All to Cart')) ?>
        </span>
    </button>
<?php endif; ?>
