<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit"
            name="do"
            title="<?= $escaper->escapeHtmlAttr(__('Update Wish List')) ?>"
            class="button button--outline-primary"
            :class="isLoading && 'button--disabled'"
            :disabled="isLoading"
            @click='setBtnText("update-wish-list")'
    >
        <span x-text="isLoading && btnText === 'update-wish-list' ?
            '<?= $escaper->escapeHtml(__('Updating...')) ?>' :
            '<?= $escaper->escapeHtml(__('Update Wish List')) ?>'">
            <?= $escaper->escapeHtml(__('Update Wish List')) ?>
        </span>
    </button>
<?php endif;?>
