<?php

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button
        type="submit"
        name="do"
        title="<?= $escaper->escapeHtmlAttr(__('Update wish list')) ?>"
        class="button button--outline-primary bg-bg-400"
    >
        <span><?= $escaper->escapeHtml(__('Update wish list')) ?></span>
    </button>
<?php endif;?>
