<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');

$formId = 'user_forgotpassword';

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="container mx-auto flex h-full items-center px-5 mt-16">
    <div class="mx-auto mb-16 w-[412px] max-w-full">
        <div class="flex items-center w-full justify-center" aria-labelledby="block-customer-login-heading">
            <form action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
                  method="post"
                  class="w-full"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  x-data="initPasswordForm()"
                  @submit.prevent="submitForm();">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>"/>
                <?= $block->getChildHtml('form_fields_before') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                <fieldset class="fieldset">
                    <div class="flex w-full flex-col items-center">
                        <h2 class="font-bold text-lg">Reset your password</h2>
                        <h5 class="mt-3">We will send you an email to reset your password</h5>
                    </div>
                    <div class="field email required mt-6">
                        <label for="email_address" class="label hidden">
                            <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                        </label>
                        <div class="control">
                            <input type="email"
                                   placeholder="Email address"
                                   name="email"
                                   alt="email"
                                   id="email_address"
                                   class="h-[44px] rounded-[0.5rem] w-full border px-5 py-4 border-text-50 contrast-more:border-secondary-700 contrast-more:placeholder-secondary-700"
                                   autocomplete="<?= $isAutocompleteEnabled ? 'username' : 'off' ?>"
                                   required
                                   value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                                class="rounded-[0.5rem] mt-8 w-full rounded-[--buttons-radius] bg-primary-bg px-6 py-4 text-white"
                            <?php if ($forgotPasswordButtonViewModel->disabled()): ?> disabled data-recaptcha-btn<?php endif; ?>
                        >
                            <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                    <div class="flex justify-center mt-5">
                        <a class="underline"
                           href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"><span><?= $escaper->escapeHtml(__('Cancel')) ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function initPasswordForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            submitForm() {
                const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>

                if (this.errors === 0) {
                    $form.submit();
                }
            }
        }
    }
</script>
