<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');

$formId = 'user_forgotpassword';

$errorMessage = $block->getErrorMessage();

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>

<div class="container mx-auto flex h-full md:items-center px-5 items-center" x-data="Authentication">
    <div class="mx-auto mb-16 w-[412px] max-w-full">
        <div class="flex items-center w-full justify-center" aria-labelledby="block-customer-login-heading">
            <form action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
                  method="post"
                  class="w-full"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  @submit.prevent="submitForgotPasswordForm('<?= $escaper->escapeJs($formId) ?>');">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>"/>
                <?= $block->getChildHtml('form_fields_before') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                <fieldset class="fieldset">
                    <div class="text-center">
                        <h2 class="text-left md:text-center mb-3 font-lg md:font-bold w-full text-xxl md:mb-4"><?= __('Reset your password') ?></h2>
                        <p class="mb-7 text-md text-text-500 sm:text-center"><?= __('We will send you an email to reset your password') ?></p>
                    </div>
                    <div class="field email required mt-6">
                        <label for="email_address" class="label hidden">
                            <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                        </label>
                        <div class="control">
                            <input type="email"
                                   placeholder="Email address"
                                   name="email"
                                   alt="email"
                                   id="email_address"
                                   class="input__field input__field--outline bg-bg-500 px-5 py-4"
                                   autocomplete="<?= $isAutocompleteEnabled ? 'username' : 'off' ?>"
                                   required
                                   value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>">
                        </div>
                    </div>
                    <?php if ($errorMessage): ?>
                        <div class="text-red-600 mt-3">
                            <?= $errorMessage ?>
                        </div>
                    <?php endif; ?>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                                class="button button--filled-primary mt-7 mb-6 w-full py-4" <?php if ($forgotPasswordButtonViewModel->disabled()): ?> disabled data-recaptcha-btn<?php endif; ?>>
                            <span><?= $escaper->escapeHtml(__('Reset My Password')) ?></span>
                        </button>
                    </div>
                    <div class="w-full text-center tracking-widest">
                        <a class="link link--primary" href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"
                           x-element-transition-trigger>
                            <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
