<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template as Block;
use Satoshi\Theme\Block\Template;

/** @var Block $block */
/** @var Template $template */
/** @var Escaper $escaper */

$slides = $block->getData('slides') ?? '';
$gap = (int)$block->getData('gap') ?? 16;
$slidesAmountInViewArray = $block->getData('slides_amount_in_view') ?? [
    'xs' => 1,
    'sm' => 2,
    'md' => 3,
    'lg' => 4,
    'xl' => 5,
    'xxl' => 6
];
$class = $block->getData('class') ?? '';
$title = $block->getData('title') ?? '';
$id = $block->getData('id') ? $block->getData('id') . '-slider' : '';
$customActions = $block->getData('custom_actions') ?? '';
$isFullPage = (bool)$block->getData('is_full_page');
$isHeaderDisabled = (bool)$block->getData('is_header_disabled');
$isActionsDisabled = (bool)$block->getData('is_actions_disabled');
$isCustomSliderXData = (bool)$block->getData('is_custom_slider_x_data');
$isScrollbarHidden = (bool)$block->getData('is_scrollbar_hidden');
$isAutoPlay = (bool)$block->getData('is_auto_play');
$autoplaySpeed = (int)$block->getData('autoplay_speed') ?? 0;

$convertedSlidesAmountInView = array_reduce(array_keys($slidesAmountInViewArray), fn ($carry, $key) => $carry . " --slide-count-$key: {$slidesAmountInViewArray[$key]};", '');
?>

<div
    class="slider <?= $isFullPage ? 'slider--full-width' : '' ?> <?= $class ?>"
    x-init="
        configureAndStart({
            slidesAmountInView: <?= $escaper->escapeUrl(json_encode($slidesAmountInViewArray)) ?>,
            gap: <?= $gap ?>,
            isAutoplay: '<?= $isAutoPlay ?>',
            autoplaySpeed: <?= $autoplaySpeed ?>
        })
    "
    <?= $isCustomSliderXData ? '' : 'x-data="Slider()"' ?>
    <?= $id ? "id='$id'" : '' ?>
    style="--slide-gap: <?= $gap ?>px; <?= $convertedSlidesAmountInView ?>"
>
    <?php if (!$isHeaderDisabled && ($title || !$isActionsDisabled)): ?>
        <div class="slider__header">
            <?php if ($title): ?>
                <h1 class="slider__title"><?= $title ?></h1>
            <?php endif; ?>
            <div class="slider__actions">
                <div x-show="!isPrevBtnDisabled || !isNextBtnDisabled"
                     class="whitespace-nowrap"
                     x-transition
                     x-cloak
                >
                    <?php if ($customActions): ?>
                        <template x-if="!$store.main.isMobile">
                            <?= $customActions ?>
                        </template>
                    <?php endif; ?>
                    <?php if (!$isActionsDisabled): ?>
                        <?= $template->render('Magento_Catalog::html/slider-buttons.phtml') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div
        class="slider__slides <?= $isScrollbarHidden ? 'scrollbar-hidden pb-0' : '' ?> <?= $isHeaderDisabled ? 'pt-0' : '' ?>"
        x-ref="slider"
        @scroll="handleManualScroll"
    >
        <?= $slides ?>
    </div>

    <?php if ($customActions): ?>
        <template x-if="$store.main.isMobile">
            <?= $customActions ?>
        </template>
    <?php endif; ?>
</div>
