<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Satoshi\Theme\Block\Template;

/** @var Template $block */
/** @var Template $template */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div>
    <form
        class="fixed left-0 z-20 w-full rounded-t-md bg-bg-500 px-5 md:sticky md:w-[--search-width] md:border-b-1 md:border-transparent md:bg-transparent md:px-2 md:pt-0 md:transition-all md:delay-150 md:duration-300 max-md:top-0 max-md:pb-3 max-md:pt-[18px]"
        role="search"
        :class="{
            'md:bg-bg-500 md:border-bg-600': getIsSearchActive(),
            'md:bg-transparent md:border-transparent': !getIsSearchActive(),
            'md:max-w-24': !$store.resizable.isVisible('search-desktop')
        }"
        action="/catalogsearch/result"
        method="GET"
        @submit.prevent="goToSearchPage('/catalogsearch/result')"
    >
        <div class="relative isolate flex w-full md:min-h-[56px] md:items-center">
            <label
                for="searchInput"
                class="sr-only tracking-widest"
            >
                <?= __('Search') ?>
            </label>
            <input
                type="search"
                placeholder="<?= __('Search') ?>"
                class="input__field input__field--filled hover:bg-transparent border-none focus-visible:input__field--outline md:input__field--ghost md:focus-visible:input__field--ghost pr-11 placeholder:text-text-500 md:order-2 md:px-2 md:placeholder:text-primary-500 md:focus-visible:border-transparent md:focus-visible:shadow-none md:focus-visible:outline-0"
                x-model="searchTermInput"
                @input.debounce.500ms="setSearchTerm"
                name="q"
                id="searchInput"
                x-ref="searchInput"
                :tabindex="
                    $store.main.isMobile ?
                        ($store.popup.currentPopup === 'menu' ? 0 : -1) :
                        ($store.resizable.isVisible('search-desktop') ? 0 : -1)
                "
                :class="{
                    'md:hidden': !$store.resizable.isVisible('search-desktop')
                }"
                x-a11y-trap-target.initial="$store.resizable.isVisible('search-desktop')"
                x-a11y-trap-target.start="getIsSearchActive()"
            >
            <div
                class="max-md:icon-button--size-md md:button md:icon-button md:icon-button--size-lg md:order-1 md:text-primary-500 max-md:pointer-events-none max-md:absolute max-md:right-0 max-md:top-0 max-md:z-10 max-md:flex max-md:items-center max-md:justify-center max-md:px-0 max-md:text-lg max-md:text-text-500"
                x-show="!$store.main.isMobile || !searchTerm"
                :class="{
                    'md:hidden': !$store.resizable.isVisible('search-desktop')
                }"
            >
                <?= $hyvaicons->renderHtml('search'); ?>
            </div>
            <button
                type="button"
                class="icon-button--size-md absolute bottom-0 right-0 top-0 z-10 m-auto flex items-center justify-center px-0 text-xxl text-text-500"
                aria-label="<?= __('Clear search') ?>"
                x-show="!!searchTerm"
                @click="resetSearchTerm"
                :tabindex="$store.resizable.isVisible('search-desktop') ? 0 : -1"
                :class="{
                    'md:hidden': !$store.resizable.isVisible('search-desktop')
                }"
            >
                <?= $hyvaicons->renderHtml('close', attributes: ['title' => 'Clear']); ?>
            </button>
        </div>
    </form>

    <div
        x-show="getIsSearchActive()"
        class="flex flex-col gap-3 overflow-x-hidden pt-2 transition-opacity duration-0 md:inset-x-0 md:top-full md:max-h-[calc(100dvh-125px)] md:rounded-t-none md:pt-0 md:duration-300 md:rounded-none"
        x-transition:enter="md:delay-450"
        x-transition:enter-start="md:opacity-0"
        x-transition:enter-end="md:opacity-100"
        x-transition:leave="md:duration-0"
        x-transition:leave-start="md:opacity-100"
        x-transition:leave-end="md:opacity-0"
        :class="{
            'md:hidden': !$store.resizable.isVisible('search-desktop')
        }"
    >
        <div class="max-md:mt-[50px]">
            <?= $template->render('Magento_Theme::html/header/search/search-suggestions.phtml') ?>
            <?= $template->render('Magento_Theme::html/header/search/search-categories.phtml') ?>
            <?= $template->render('Magento_Theme::html/header/search/search-products.phtml') ?>
        </div>
        <div
            class="transition-opacity duration-300 md:sticky md:bottom-0 md:z-10 md:w-full md:rounded-b-md md:bg-bg-500"
            id="search-actions"
            x-show="!isLoading"
            x-transition.opacity
            x-transition:leave.duration.300ms
            x-transition:enter.delay.300ms
            :class="{ 'opacity-0': isLoading, 'md:opacity-100': !isLoading}"
        ></div>
    </div>
</div>
