<?php

use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

?>

<button tabindex="0" class="md:button--filled-white button ghost-primary icon-button icon-button--size-lg md:m-2 contrast-more:md:border contrast-more:md:border-secondary-700" aria-label="<?= $escaper->escapeHtml(__('Open search')) ?>" @keydown.space.prevent="$store.resizable.show('search-desktop')" @keydown.enter.prevent="$store.resizable.show('search-desktop')" x-a11y-trap-element="$store.transition.isPreviewActive && !$store.resizable.isVisible()">
  <?= $hyvaicons->renderHtml('search') ?>
</button>