<script>
  const computeRatio = () => {
    const smallestViewportHeightElem = document.createElement('div');
    smallestViewportHeightElem.style.position = 'fixed';
    smallestViewportHeightElem.style.top = '0';
    smallestViewportHeightElem.style.left = '0';
    smallestViewportHeightElem.style.width = '100vw';
    smallestViewportHeightElem.style.height = '100svh';
    smallestViewportHeightElem.style.visibility = 'hidden';
    smallestViewportHeightElem.style.pointerEvents = 'none';
    document.documentElement.appendChild(smallestViewportHeightElem);

    // measure once
    const screenHeight = smallestViewportHeightElem.offsetHeight;
    const screenWidth = smallestViewportHeightElem.offsetWidth;

    smallestViewportHeightElem.remove();

    document.documentElement.style.setProperty(
      '--product-aspect-ratio',
        (screenWidth / (screenHeight - 155)).toString(),
    );
  };

  window.addEventListener('resize', computeRatio);
  computeRatio();
</script>
