<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductListItem;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$productListItemViewModel = $viewModels->require(ProductListItem::class);

$eagerLoadImagesCount = (int)($block->getData('eager_load_images_count') ?? 3);
$productCollection = $block->getLoadedProductCollection();

?>
<?php if (!$productCollection->count()): ?>
    <div class="flex w-full flex-col gap-5 py-5 md:items-start">
        <p class="">
            <b class="text-secondary-700"><?= __('Oops!') ?></b>
            <?= __('We could not find any products matching your selection.') ?>
        </p>
        <button type="button" class="button button--outline-secondary" @click="resetAll">
            <?= __('Reset selection') ?>
        </button>
    </div>
<?php else: ?>
    <section tabindex="-1"
             id="ProductGridContainer"
             class="content-wrapper animate-on-transition mx-auto"
             x-ref="ProductGridContainer"
             x-data="ProductList('')"
             key="ProductList-all"
    >
        <div class="flex md:items-start">
            <div class="flex-grow">
                <div
                    data-content-wrapper
                    id="product-grid"
                    class="mb-5 grid gap-6 transition-opacity duration-100 ease-linear md:mb-16 grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5"
                    :class="
                        {
                            'opacity-0': isLoadingProducts,
                        }
                    "
                >
                    <!-- pagination-content -->
                    <?php
                    /** @var Product $product */
                    foreach (array_values($productCollection->getItems()) as $i => $product):
                        if ($i < $eagerLoadImagesCount) {
                            $product->setData('image_custom_attributes', ['loading' => 'eager', 'fetchpriority' => 'high']);
                        }
                        ?>
                        <?= $productListItemViewModel->getItemHtml(
                        $product,
                        $block,
                        'grid',
                        ReviewRendererInterface::SHORT_VIEW,
                        'category_page_grid',
                        false
                    ); ?>
                    <?php endforeach; ?>
                    <!-- end-pagination-content -->
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
