<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Modal;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$modalViewModel = $viewModels->require(Modal::class);

$ccNumberView = $escaper->escapeHtml($block->getNumberLast4Digits());

$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<div class="grid md:grid-cols-4">
    <div class="grid grid-cols-2 md:grid-cols-1 mb-4 md:mb-0">
        <div class="md:hidden font-bold">
            <?= $escaper->escapeHtml(__('Card Number')) ?>
        </div>
        <span><?= /* @noEscape */
            $ccNumberView ?></span>
    </div>
    <div class="grid grid-cols-2 md:grid-cols-1 mb-4 md:mb-0">
        <div class="md:hidden font-bold">
            <?= $block->escapeHtml(__('Expiration Date')) ?>
        </div>
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </div>
    <div class="grid grid-cols-2 md:grid-cols-1 mb-4 md:mb-0">
        <div class="md:hidden font-bold">
            <?= $block->escapeHtml(__('Type')) ?>
        </div>
        <img src="<?= /* @noEscape */
        $block->getIconUrl() ?>"
             width="<?= /* @noEscape */
             $block->getIconWidth() ?>"
             height="<?= /* @noEscape */
             $block->getIconHeight() ?>"
             alt="card-icon"
        >
    </div>
    <div class="grid grid-cols-2 md:grid-cols-1 mb-4 md:mb-0">
        <div class="md:hidden font-bold">
            <?= $block->escapeHtml(__('Actions')) ?>
        </div>
        <div class="flex md:justify-end" x-data="hyva.modal()">
            <form class="form"
                  action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
                  method="post"
                  x-ref="form">
                <?= $block->getBlockHtml('formkey') ?>
                <input
                    name="<?= /* @noEscape */
                    PaymentTokenInterface::PUBLIC_HASH ?>"
                    value="<?= $escaper->escapeHtmlAttr($block->getToken()->getPublicHash()) ?>"
                    type="hidden"/>

                <?php $message = $escaper->escapeHtml(__('Are you sure you want to delete this card: %1?', $ccNumberView)) ?>
                <?php $confirmation = $modalViewModel->confirm($message) ?>
                <button type="button"
                        @click="<?= /** @noEscape */
                        $confirmation->getShowJs() ?>.then(ok => ok && $refs.form.submit())">
                    <?= $hyvaicons->renderHtml('trash', 'text-xl text-primary-700'); ?>
                </button>
                <?= /** @noEscape */ $confirmation ?>
            </form>
        </div>
    </div>
</div>
