<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$filters = $block->getData('filters') ?? [];
$selectedSort = $block->getData('selected_sort') ?? [];
?>
<div>
    <div class="min-h-9"></div>

    <template x-portal="document.getElementById('popup-fixed-content-portal')">
        <div class="overflow-x-scroll overscroll-x-contain pl-3" x-show="$store.main.isMobile && $store.popup.currentPopup === 'bottom-filters'">
            <div class="flex items-center gap-3">
                <button
                    type="button"
                    class="button button--filled-primary button--size-sm shrink-0"
                    @click="showFilters"
                >
                    <?= $escaper->escapeHtml(__('Filter')) ?>
                    <span class="ml-3 text-lg">
                        <?= $hyvaicons->renderHtml('filter'); ?>
                    </span>
                </button>

                <?php if (!count($filters) && !count($selectedSort)): ?>
                    <p class="shrink-0 grow pr-3 text-center">
                        <?= $escaper->escapeHtml(__('The selected filters will appear here.')) ?>
                    </p>
                <?php else: ?>
                    <div class="flex gap-3">
                        <?php if (count($selectedSort)): ?>
                            <a
                                @click="removeSort()"
                                class="button button--outline-secondary button--size-sm shrink-0"
                                title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Remove sort %1 by: %2', $selectedSort['name'], $selectedSort['dir'])) ?>"
                            >
                                <span class="mr-2"><?= $escaper->escapeHtml(__('Sort')) ?>:</span>
                                <span><?= $escaper->escapeHtml($selectedSort['name']) ?></span>
                                <span class="ml-3 text-lg">
                                    <?= $hyvaicons->renderHtml('close'); ?>
                                </span>
                            </a>
                        <?php endif; ?>

                        <?php foreach ($filters as $filter): ?>
                            <?php
                            $filterName = $filter->getName();
                            $filterLabel = $block->stripTags($filter->getLabel());
                            ?>
                            <a
                                href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                                class="button button--outline-secondary button--size-sm shrink-0"
                                title="<?= /* @noEscape */
                                $escaper->escapeHtmlAttr(__('Remove active %1 filter: %2', $filterName, $filterLabel)) ?>"
                                x-element-transition-trigger
                            >
                                <span class="mr-2"><?= $escaper->escapeHtml(__($filterName)) ?>:</span>
                                <span><?= $escaper->escapeHtml($filterLabel) ?></span>
                                <span class="ml-3 text-lg">
                                    <?= $hyvaicons->renderHtml('close'); ?>
                                </span>
                            </a>
                        <?php endforeach; ?>

                        <div class="sticky bottom-0 right-0 top-0 z-10 h-9 shrink-0 basis-20 bg-gradient-to-l from-bg-500 to-transparent pointer-events-none"></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </template>
</div>
