import persist from "@alpinejs/persist";
import morph from "@alpinejs/morph";

import ElementTransition from "@satoshi/src/plugins/Transition";
import ElementIntersection from "@satoshi/src/plugins/Intersect";
import Pagination from "@satoshi/src/plugins/Pagination";
import Accessibility from "@satoshi/src/plugins/Accessibility";
import Portal from "@satoshi/src/plugins/Portal";
import StickyScroll from "@satoshi/src/plugins/StickyScroll";

import { PopupStore } from "@satoshi/src/store/Popup";
import { ResizableStore } from "@satoshi/src/store/Resizable";
import { Main } from "@satoshi/src/store/Main";
import { CartStore } from "@satoshi/src/store/Cart";
import { WishlistStore } from "@satoshi/src/store/Wishlist";
import { AccountStore } from "@satoshi/src/store/Account";

import { BeforeAfter } from "@satoshi/src/data/BeforeAfter";
import { TransitionPreview } from "@satoshi/src/data/TransitionPreview";
import { ProductList } from "@satoshi/src/data/ProductList";
import { Filters } from "@satoshi/src/data/Filters";
import { ProductPage } from "@satoshi/src/data/ProductPage";
import { DownloadableProduct } from "@satoshi/src/data/DownloadableProduct";
import { RecentOrders } from "@satoshi/src/data/RecentOrders";
import { Dropdown } from "@satoshi/src/data/Dropdown";
import { Search } from "@satoshi/src/data/Search";
import { Shipping } from "@satoshi/src/data/Shipping";
import { Accordion } from "@satoshi/src/data/Accordion";
import { Address } from "@satoshi/src/data/Address";
import { AddressEdit } from "@satoshi/src/data/AddressEdit";
import { RangeSlider } from "@satoshi/src/data/RangeSlider";
import { Slider } from "@satoshi/src/data/Slider";
import { CountdownTimer } from "@satoshi/src/data/CountdownTimer";
import { TransitionImage } from "@satoshi/src/data/TransitionImage";
import { Authentication } from "@satoshi/src/data/Authentication";
import { Gallery } from "@satoshi/src/data/Gallery";
import { Newsletter } from "@satoshi/src/data/Newsletter";
import { ReviewForm } from "@satoshi/src/data/ReviewForm";
import { Form } from "@satoshi/src/data/Form";
import { Rating } from "@satoshi/src/data/Rating";
import { BundlePrice } from "@satoshi/src/data/BundlePrice";
import { CatalogPrice } from "@satoshi/src/data/CatalogPrice";
import { ReviewList } from "@satoshi/src/data/ReviewList";
import { AccountInformation } from "@satoshi/src/data/AccountInformation";
import { Recaptcha } from "@satoshi/src/data/Recaptcha";
import { PasswordValidation } from "@satoshi/src/data/PasswordValidation";
import { BundleOptions } from "@satoshi/src/data/BundleOptions";
import { ShareWishlist } from "@satoshi/src/data/ShareWishlist";
import { Wishlist } from "@satoshi/src/data/Wishlist";
import { ImageZoom } from "@satoshi/src/data/Image";

document.addEventListener("alpine:init", () => {
    Alpine.plugin(Portal);
    Alpine.plugin(StickyScroll);
    Alpine.plugin(persist);
    Alpine.plugin(morph);
    Alpine.plugin(ElementTransition);
    Alpine.plugin(ElementIntersection);
    Alpine.plugin(Pagination);
    Alpine.plugin(Accessibility);

    Alpine.store("popup", PopupStore);
    Alpine.store("main", Main);
    Alpine.store("resizable", ResizableStore);
    Alpine.store("cart", CartStore);
    Alpine.store("wishlist", WishlistStore);
    Alpine.store("account", AccountStore);

    Alpine.data("TransitionPreview", TransitionPreview);
    Alpine.data("BeforeAfter", BeforeAfter);
    Alpine.data("ProductList", ProductList);
    Alpine.data("Filters", Filters);
    Alpine.data("ProductPage", ProductPage);
    Alpine.data("DownloadableProduct", DownloadableProduct);
    Alpine.data("RecentOrders", RecentOrders);
    Alpine.data("Dropdown", Dropdown);
    Alpine.data("Search", Search);
    Alpine.data("Shipping", Shipping);
    Alpine.data("Accordion", Accordion);
    Alpine.data("Address", Address);
    Alpine.data("AddressEdit", AddressEdit);
    Alpine.data("RangeSlider", RangeSlider);
    Alpine.data("Slider", Slider);
    Alpine.data("CountdownTimer", CountdownTimer);
    Alpine.data("TransitionImage", TransitionImage);
    Alpine.data("Authentication", Authentication);
    Alpine.data("Gallery", Gallery);
    Alpine.data("Newsletter", Newsletter);
    Alpine.data("ReviewForm", ReviewForm);
    Alpine.data("Form", Form);
    Alpine.data("Rating", Rating);
    Alpine.data("BundlePrice", BundlePrice);
    Alpine.data("CatalogPrice", CatalogPrice);
    Alpine.data("ReviewList", ReviewList);
    Alpine.data("AccountInformation", AccountInformation);
    Alpine.data("Recaptcha", Recaptcha);
    Alpine.data("PasswordValidation", PasswordValidation);
    Alpine.data("BundleOptions", BundleOptions);
    Alpine.data("ShareWishlist", ShareWishlist);
    Alpine.data("Wishlist", Wishlist);
    Alpine.data("ImageZoom", ImageZoom);
});
