<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Catalog\Block\Product\View\BaseImage;
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Framework\Escaper;
use Magento\GroupedProduct\Block\Product\View\Type\Grouped;

/**
 * @var BaseImage $block
 * @var Grouped $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$block->setPreconfiguredValue();
$product = $block->getProduct();
$associatedProducts = $block->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts) > 0;

?>
<?php if ($hasAssociatedProducts): ?>
    <div class="flex justify-between items-center mb-3">
        <h2 class="font-semibold text-text-500">
            <?= $escaper->escapeHtml(__('Product Set')) ?>
        </h2>
        <button
            type="button"
            class="button button--outline-secondary icon-button icon-button--size-xs md:hidden"
            aria-label="<?= __('Close') ?>"
            @click.prevent="hideProductActions()"
        >
            <?= $hyvaicons->renderHtml('close') ?>
        </button>
    </div>

    <div class="flex flex-col gap-5 mt-3 md:mb-7">
        <?php foreach ($associatedProducts as $item): ?>
            <div class="flex justify-between items-center">
                <!-- Label & Price -->
                <label
                    class="text-base text-text-500 flex-grow"
                    for="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                >
                    <?= $escaper->escapeHtml($item->getName()) ?>
                    <?php if ($block->getCanShowProductPrice($product)): ?>
                        <?php if ($block->getCanShowProductPrice($item)): ?>
                            <?= /* @noEscape */
                            $block->getProductPrice($item) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </label>

                <!-- Quantity control -->
                <?php if ($product->isSaleable()): ?>
                    <?php if ($item->isSaleable()): ?>
                        <div class="contents"
                             x-data="{value: <?= (int)$escaper->escapeHtmlAttr($item->getQty() * 1) ?>}">
                            <button
                                type="button"
                                class="animate-on-transition button button--outline-secondary icon-button select-none icon-button--size-sm me-2"
                                aria-label="<?= __('Decrease quantity') ?>"
                                @click.prevent.stop="() => {
                                    value--;
                                    Alpine.nextTick(() => {
                                        validateGroupedProduct();
                                    })
                                }"
                            >
                                <span class="sr-only">
                                    <?= __('Decrease quantity for %1', $product->getName()) ?>
                                </span>
                                <?= $hyvaicons->renderHtml('minus'); ?>
                            </button>

                            <label for="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                                   class="sr-only tracking-widest">
                                <?= __('Quantity') ?>
                            </label>
                            <input type="number"
                                   min="0"
                                   name="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                                   id="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                                   value="0"
                                   :value="value"
                                   title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                   class="animate-on-transition input__field flex-shrink-0 basis-14 text-center bg-transparent h-9 px-3 me-2"
                                   :class=" { 'border-red-500 focus:border-red-500 focus:ring-red-500': !isGroupValid }"
                                   @input.debounce="validateGroupedProduct()"
                                   aria-label="<?= __('Quantity') ?>"
                            />

                            <button
                                type="button"
                                class="animate-on-transition button button--outline-secondary icon-button select-none icon-button--size-sm"
                                aria-label="<?= __('Increase quantity') ?>"
                                @click.prevent.stop="() => {
                                    value++;
                                    Alpine.nextTick(() => {
                                        validateGroupedProduct();
                                    })
                                }"
                            >
                                <span class="sr-only">
                                  <?= __('Increase quantity') ?>
                                </span>
                                <?= $hyvaicons->renderHtml('plus'); ?>
                            </button>
                        </div>
                    <?php else: ?>
                        <div class="stock unavailable"
                             title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
                        >
                            <?= $escaper->escapeHtml(__('Out of stock')) ?>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <?php if ($block->getCanShowProductPrice($product)
                && $block->getCanShowProductPrice($item)
                && trim($block->getProductPriceHtml(
                    $item,
                    TierPrice::PRICE_CODE
                ))): ?>
                <div class="flex pt-2 w-full items-center">
                    <?= $block->getProductPriceHtml(
                        $item,
                        TierPrice::PRICE_CODE
                    ) ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <?= $escaper->escapeHtml(__('No options of this product are available.')) ?>
<?php endif; ?>
