// import Alpine from "alpinejs";
import "../theme/app.scss";

import persist from "@alpinejs/persist";
import morph from "@alpinejs/morph";

import ElementTransition from "./plugins/Transition";
import ElementIntersection from "./plugins/Intersect";
import Pagination from "./plugins/Pagination";
import Accessibility from "./plugins/Accessibility.js";
import Portal from "./plugins/Portal";
import StickyScroll from "./plugins/StickyScroll";

import { PopupStore } from "./store/Popup";
import { ResizableStore } from "./store/Resizable";
import { Main } from "./store/Main";
import { CartStore } from "./store/Cart";
import { WishlistStore } from "./store/Wishlist";
import { AccountStore } from "./store/Account";

import { BeforeAfter } from "./data/BeforeAfter";
import { TransitionPreview } from "./data/TransitionPreview";
import { ProductList } from "./data/ProductList";
import { Filters } from "./data/Filters";
import { ProductPage } from "./data/ProductPage";
import { DownloadableProduct } from "./data/DownloadableProduct";
import { RecentOrders } from "./data/RecentOrders";
import { Dropdown } from "./data/Dropdown";
import { Search } from "./data/Search";
import { Shipping } from "./data/Shipping.js";
import { Accordion } from "./data/Accordion";
import { Address } from "./data/Address";
import { AddressEdit } from "./data/AddressEdit";
import { RangeSlider } from "./data/RangeSlider";
import { Slider } from "./data/Slider";
import { CountdownTimer } from "./data/CountdownTimer";
import { TransitionImage } from "./data/TransitionImage";
import { Authentication } from "./data/Authentication";
import { Gallery } from "./data/Gallery.ts";
import { Newsletter } from "./data/Newsletter";
import { ReviewForm } from "./data/ReviewForm.ts";
import { Form } from "./data/Form";
import { Rating } from "./data/Rating";
import { BundlePrice } from "./data/BundlePrice";
import { CatalogPrice } from "./data/CatalogPrice";
import { ReviewList } from "./data/ReviewList.ts";
import { AccountInformation } from "./data/AccountInformation";
import { Recaptcha } from "./data/Recaptcha";
import { PasswordValidation } from "./data/PasswordValidation";
import { BundleOptions } from "./data/BundleOptions";
import { ShareWishlist } from "./data/ShareWishlist";
import { Wishlist } from "./data/Wishlist";
import { ImageZoom } from "./data/Image";

document.addEventListener("alpine:init", () => {
  Alpine.plugin(Portal);
  Alpine.plugin(StickyScroll);
  Alpine.plugin(persist);
  Alpine.plugin(morph);
  Alpine.plugin(ElementTransition);
  Alpine.plugin(ElementIntersection);
  Alpine.plugin(Pagination);
  Alpine.plugin(Accessibility);

  Alpine.store("popup", PopupStore);
  Alpine.store("main", Main);
  Alpine.store("resizable", ResizableStore);
  Alpine.store("cart", CartStore);
  Alpine.store("wishlist", WishlistStore);
  Alpine.store("account", AccountStore);

  Alpine.data("TransitionPreview", TransitionPreview);
  Alpine.data("BeforeAfter", BeforeAfter);
  Alpine.data("ProductList", ProductList);
  Alpine.data("Filters", Filters);
  Alpine.data("ProductPage", ProductPage);
  Alpine.data("DownloadableProduct", DownloadableProduct);
  Alpine.data("RecentOrders", RecentOrders);
  Alpine.data("Dropdown", Dropdown);
  Alpine.data("Search", Search);
  Alpine.data("Shipping", Shipping);
  Alpine.data("Accordion", Accordion);
  Alpine.data("Address", Address);
  Alpine.data("AddressEdit", AddressEdit);
  Alpine.data("RangeSlider", RangeSlider);
  Alpine.data("Slider", Slider);
  Alpine.data("CountdownTimer", CountdownTimer);
  Alpine.data("TransitionImage", TransitionImage);
  Alpine.data("Authentication", Authentication);
  Alpine.data("Gallery", Gallery);
  Alpine.data("Newsletter", Newsletter);
  Alpine.data("ReviewForm", ReviewForm);
  Alpine.data("Form", Form);
  Alpine.data("Rating", Rating);
  Alpine.data("BundlePrice", BundlePrice);
  Alpine.data("CatalogPrice", CatalogPrice);
  Alpine.data("ReviewList", ReviewList);
  Alpine.data("AccountInformation", AccountInformation);
  Alpine.data("Recaptcha", Recaptcha);
  Alpine.data("PasswordValidation", PasswordValidation);
  Alpine.data("BundleOptions", BundleOptions);
  Alpine.data("ShareWishlist", ShareWishlist);
  Alpine.data("Wishlist", Wishlist);
  Alpine.data("ImageZoom", ImageZoom);
});
