<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var \Satoshi\Theme\Block\Template $template */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Template $block */
$isCartPage = $block->getData('isCartPage');

?>
<div class="contents"
     x-data="{
        excludingTaxMessage: '<?= $escaper->escapeJs(__('Excl. Tax')) ?>',
        includingTaxMessage: '<?= $escaper->escapeJs(__('Incl. Tax')) ?>',
        get cartTotals() { return $store.cart.cartTotals }
    }"
>
    <div class="absolute left-0 right-0 top-0 origin-bottom -translate-y-[2.5rem] transition-all duration-700 motion-reduce:transition-none md:mb-0 md:w-full <?= $isCartPage ? 'md:relative md:translate-y-0 md:pointer-events-auto' : '' ?>"
         :class="{
            '-translate-y-full': isTotalsExpanded,
            '-translate-y-[2.5rem] pointer-events-none': !isTotalsExpanded
        }"
        <?php if (!$isCartPage): ?>
            :style="{
                'clip-path': isTotalsExpanded ? 'inset(0 0 0 0)' : 'inset(0 0 50% 0)'
            }"
        <?php endif; ?>
    >
        <div class="pointer-events-none <?= $isCartPage ? 'md:hidden' : '' ?> relative top-0 h-10 bg-gradient-to-t from-[#00000010] via-transparent to-transparent"
        ></div>
        <div class="flex flex-col gap-4 bg-bg-500 <?= $isCartPage ? 'max-md:px-4 md:pb-4 md:border-t md:border-b md:-mx-4 md:px-4' : 'px-4 pointer-events-none' ?> pt-4 [.popup\_\_wrapper--visible_&]:pointer-events-auto [.resizable--visible_&]:pointer-events-auto"
             :inert="<?= $isCartPage ? '$store.main.isMobile && ' : '' ?>!isTotalsExpanded"
        >
            <?php if ($isCartPage): ?>
                <?= $template->render('Magento_Checkout::cart/shipping.phtml') ?>
            <?php endif; ?>

            <div class="flex items-center justify-between pt-2">
                <h2 class="text-text-500"><?= __('Order summary') ?></h2>
                <button type="button"
                        class="button button--outline-secondary icon-button icon-button--size-xs <?= $isCartPage ? 'md:hidden' : '' ?>"
                        :aria-label="isTotalsExpanded ? '<?= __('Collapse') ?>' : '<?= __('Expand') ?>'"
                        @click="isTotalsExpanded = !isTotalsExpanded"
                        @transitionend.stop
                >
                    <span :class="{ 'rotate-180': isTotalsExpanded }">
                        <?= $hyvaicons->renderHtml('chevron-up') ?>
                    </span>
                </button>
            </div>

            <div class="flex flex-col gap-3">
                <template x-for="segment in cartTotals.total_segments"
                          :key="segment.code"
                >
                    <div class="contents">
                        <template x-if="segment.code === 'subtotal'">
                            <?= $template->render('Magento_Theme::html/header/cart/totals/subtotal.phtml') ?>
                        </template>

                        <template x-if="segment.code === 'shipping'">
                            <?= $template->render('Magento_Theme::html/header/cart/totals/shipping.phtml') ?>
                        </template>

                        <template x-if="segment.code === 'tax'">
                            <?= $template->render('Magento_Theme::html/header/cart/totals/tax.phtml') ?>
                        </template>

                        <template x-if="segment.code === 'grand_total'">
                            <?= $template->render('Magento_Theme::html/header/cart/totals/grand-total.phtml') ?>
                        </template>

                        <template x-if="segment.code === 'discount'">
                            <div class="flex justify-between items-center">
                                <p x-text="segment.title"></p>
                                <p x-text="hyva.formatPrice(segment.value)" class="whitespace-nowrap"></p>
                            </div>
                        </template>
                    </div>
                </template>
            </div>
            <?php if (!$isCartPage): ?>
                <hr class="divider -mx-4">
            <?php endif; ?>
        </div>
    </div>

    <div class="<?= !$isCartPage ? 'pointer-events-none px-3' : 'p-4' ?>  relative -mx-4 rounded-b-md bg-bg-500 transition-opacity duration-300 md:pb-4 max-md:px-3 max-md:pb-5 [.popup\_\_main_&]:pb-3 [.popup\_\_wrapper--visible_&]:pointer-events-auto [.resizable--visible_&]:pointer-events-auto"
         :class="{
            'opacity-0': isCartEmpty,
            'opacity-1': !isCartEmpty,
            'hidden': isRemoveContent
        }"
    >
        <div class="flex items-center justify-between overflow-x-hidden bg-bg-500 pb-2 <?= !$isCartPage ? 'px-2 pt-4' : '' ?> text-text-500 max-md:px-3"
        >
            <h2><?= __('Grand total') ?></h2>
            <div class="flex translate-x-0 items-center gap-5 transition-transform delay-200 duration-300 motion-reduce:transition-none"
                 :class="{
                    'translate-x-11': isTotalsExpanded,
                    'translate-x-0 delay-200': !isTotalsExpanded
                }"
            >
                <div>
                    <p class="font-bold"
                       x-text="hyva.formatPrice(cartTotals.grand_total || 0)"
                    ></p>
                </div>

                <button type="button"
                        class="button button--outline-secondary icon-button icon-button--size-xs <?= $isCartPage ? 'md:hidden' : '' ?>"
                        :aria-label="isTotalsExpanded ? `<?= __('Collapse') ?>` : `<?= __('Expand') ?>`"
                        @click="isTotalsExpanded = !isTotalsExpanded"
                        @transitionend.stop
                >
                    <span :class="{ 'rotate-180': isTotalsExpanded }">
                        <?= $hyvaicons->renderHtml('chevron-up') ?>
                    </span>
                </button>
            </div>
        </div>

        <div class="mt-2 flex flex-col gap-4 rounded-b-xl bg-bg-500 max-md:px-3">
            <a href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
               class="button button--filled-primary h-11 w-full"
               :class="{ 'button--disabled': $store.cart.isLoading }"
            >
                <?= __('Secure checkout') ?>
                <span class="button__icon ml-3">
                    <?= $hyvaicons->renderHtml('lock') ?>
                </span>
            </a>
        </div>
    </div>
</div>
