<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

?>

<button
  type="button"
  class="button button--outline-secondary icon-button icon-button--size-sm bg-white text-secondary-600 transition-opacity duration-300 active:bg-secondary-100"
  :aria-label="item.qty < 2 ? `{$escaper->escapeHtml(__('Remove from cart'))}` : `{$escaper->escapeHtml(__('Decrease quantity'))}`"
  @click.prevent.stop="$store.cart.decreaseQty(item.item_id);"
  @transitionend.stop
  :aria-busy="$store.cart.isLoading"
>
  <span
    class="[&_svg]:contrast-more:text-secondary-700"
    :class="{ 'hidden': item.qty > 1 }"
    x-show="item.qty < 2"
  >
    <?= $hyvaicons->renderHtml('remove') ?>
  </span>
  <span
    :class="{ 'hidden': item.qty < 2 }"
    x-show="item.qty > 1"
  >
    <?= $hyvaicons->renderHtml('minus') ?>
  </span>
</button>
<label
  :for="'quantity_' + item.item_id"
  class="sr-only tracking-widest"
>
  <?= $escaper->escapeHtml(__('Quantity')) ?>
</label>
<input
  type="number"
  name="quantity"
  class="input__field h-9 min-w-14 basis-14 text-center"
  min="0"
  :id="'quantity_' + item.item_id"
  x-model="item.qty"
  @click.prevent.stop=""
  @change="$store.cart.setQty($event.target.value, item.item_id)"
  aria-label="{$escaper->escapeHtml(__('Quantity'))}"
  :aria-busy="$store.cart.isLoading"
>
<button
  type="button"
  class="button button--outline-secondary icon-button icon-button--size-sm bg-white text-secondary-600 transition-opacity duration-300 active:bg-secondary-100"
  aria-label="{$escaper->escapeHtml(__('Increase'))}"
  @click.prevent.stop="$store.cart.increaseQty(item.item_id)"
  :aria-busy="$store.cart.isLoading"
>
  <?= $hyvaicons->renderHtml('plus') ?>
</button>