<?php
declare(strict_types=1);

use Hyva\Theme\ViewModel\SvgIcons;
use Satoshi\Theme\ViewModel\Cart\Cart;

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Cart $cartItems */
$cart = $viewModels->require(Cart::class);
$cartItemsCount = $cart->getCartItemsQty();
?>

<span
    <?php if($cartItemsCount != 0): ?>
        style="display: none"
    <?php endif; ?>
    x-show="$store.main.totalCartQty === 0"
>
    <?= $hyvaicons->renderHtml('cart-empty'); ?>
</span>
<span
    <?php if($cartItemsCount != 1): ?>
        style="display: none"
    <?php endif; ?>
    x-show="$store.main.totalCartQty === 1"
>
    <?= $hyvaicons->renderHtml('cart'); ?>
</span>
<span
    <?php if($cartItemsCount < 2): ?>
        style="display: none"
    <?php endif; ?>
    x-show="$store.main.totalCartQty > 1"
    class="-scale-x-100"
>
    <?= $hyvaicons->renderHtml('carts'); ?>
</span>