<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$isContain = false;
$mixBackground = true;
$productName = $block->getProduct()->getName();
$images = $block->getGalleryImages()->getItems();
$isMobile = $block->getData('is_mobile') ?? false;
?>

<div
    class="flex w-full flex-col gap-4 md:grid md:grid-cols-[repeat(auto-fit,1fr)] md:gap-5 md:pb-7 lg:grid-cols-[repeat(auto-fit,minmax(300px,1fr))] max-md:-mt-8"
    x-data="{ fadingIn: false }"
    x-init="$nextTick(() => { fadingIn = true })"
>
    <!-- Images  -->
    <template x-for="(image, index) in images" :key="index">
        <div class="contents">
            <template x-if="index === 0">
                <div
                    class="relative flex aspect-product flex-shrink-0 items-center justify-center overflow-hidden bg-[--fade-in-bg] md:rounded-2xl max-md:hidden"
                    :class="{
                        'cursor-zoom-in': image.type === 'image'
                    }"
                    x-data="ImageZoom"
                    @click.stop="image.type === 'image' && zoomImage"
                >
                    <div
                        x-data="
                            TransitionImage({
                                src: image.img,
                                imageId: `main-image-${image.position}`
                            })
                        "
                        x-show="!!src"
                        class="<?= $isContain ? 'p-[4%]' : 'size-full' ?> hide-unless-transition absolute inset-0 z-10 flex items-center justify-center bg-[--fade-in-bg] transition-opacity delay-1000 duration-300"
                        :class="{ 'opacity-0 pointer-events-none': isImgLoaded }"
                    >
                        <img
                            height="100%"
                            width="100%"
                            class="transition-image object-center <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?> <?= $mixBackground ? 'mix-blend-darken' : '' ?>"
                            :src="src"
                            :alt="image.caption"
                            alt=""
                            src=""
                        >
                    </div>

                    <div
                        class="flex items-center justify-center size-full bg-[--fade-in-bg] <?= $isContain ? 'p-[4%]' : '' ?>">
                        <img
                            class="object-center no-fade <?= $mixBackground ? 'mix-blend-darken' : '' ?> <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?>"
                            :src="image.img"
                            :alt="image.caption"
                            :id="`main-image-${image.position}`"
                            src=""
                            alt=""
                        >

                        <!-- Play button -->
                        <button
                            x-show="image.type === 'video'"
                            type="button"
                            class="group absolute inset-0 grid place-items-center"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Play video')) ?>"
                            @click="activateVideo(image.position)"
                            @keydown.enter="activateVideo(image.position)"
                            x-cloak
                        >
                            <?= $heroiconsSolid->playHtml(
                                'stroke-white/75 fill-black/20 transition ease-in group-hover:scale-110 md:w-24 md:h-24',
                                44,
                                44,
                                ['aria-hidden' => 'true']
                            ); ?>
                        </button>

                        <!-- Youtube container -->
                        <div class="absolute inset-0 hidden size-full bg-bg-400"
                             :class="{ 'hidden': activeVideoType !== 'youtube' }"
                             x-transition.opacity.duration.500ms
                             x-show="image.type === 'video' && activeVideoType === 'youtube'"
                        >
                            <div :id="`desktop-youtube-player-${image.position}`"
                                 class="size-full"></div>
                        </div>

                        <!-- Video container -->
                        <div class="absolute inset-0 hidden size-full bg-bg-400"
                             :class="{ 'hidden': activeVideoType !== 'vimeo' }"
                             x-transition.opacity.duration.500ms
                             x-show="image.type === 'video' && activeVideoType === 'vimeo'"
                        >
                            <div :id="`desktop-vimeo-player-${image.position}`"
                                 class="size-full"></div>
                        </div>
                    </div>
                </div>
            </template>
            <template x-if="index !== 0">
                <div
                    class="animate-on-transition relative aspect-product flex-shrink-0 overflow-hidden border-black md:rounded-2xl"
                    x-data="ImageZoom"
                    @click.stop="image.type === 'image' && zoomImage"
                    @touchstart="image.type === 'image' && onTouchStart"
                    @touchmove="image.type === 'image' && onTouchMove"
                    @touchend="image.type === 'image' && onTouchEnd"
                    @wheel="image.type === 'image' && onWheel"
                    :style="`transform: translate(${translate.x}px, ${translate.y}px) scale(${scale})`"
                    :class="{
                        'transition-all duration-300': reset,
                        'z-50': scale > 1,
                        'cursor-zoom-in': image.type === 'image'
                    }"
                >
                    <div
                        class="flex items-center justify-center size-full bg-[--fade-in-bg] <?= $isContain ? 'p-[4%]' : '' ?>">
                        <img
                            :alt="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                            :title="image.caption || '<?= $escaper->escapeJs($productName) ?>'"
                            class="object-center <?= $mixBackground ? 'mix-blend-darken' : '' ?> <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?>"
                            :src="image.img"
                            alt=""/>

                        <!-- Play button -->
                        <button
                            x-show="image.type === 'video'"
                            type="button"
                            class="group absolute inset-0 grid place-items-center"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Play video')) ?>"
                            @click="activateVideo(image.position)"
                            @keydown.enter="activateVideo(image.position)"
                            x-cloak
                        >
                            <?= $heroiconsSolid->playHtml(
                                'stroke-white/75 fill-black/20 transition ease-in group-hover:scale-110 md:w-24 md:h-24',
                                44,
                                44,
                                ['aria-hidden' => 'true']
                            ); ?>
                        </button>

                        <!-- Youtube container -->
                        <div class="absolute inset-0 hidden size-full bg-bg-400"
                             :class="{ 'hidden': activeVideoType !== 'youtube' }"
                             x-transition.opacity.duration.500ms
                             x-show="image.type === 'video' && activeVideoType === 'youtube'"
                        >
                            <div :id="`<?= $isMobile ? 'mobile' : 'desktop' ?>-youtube-player-${image.position}`"
                                 class="size-full"></div>
                        </div>

                        <!-- Video container -->
                        <div class="absolute inset-0 hidden size-full bg-bg-400"
                             :class="{ 'hidden': activeVideoType !== 'vimeo' }"
                             x-transition.opacity.duration.500ms
                             x-show="image.type === 'video' && activeVideoType === 'vimeo'"
                        >
                            <div :id="`<?= $isMobile ? 'mobile' : 'desktop' ?>-vimeo-player-${image.position}`"
                                 class="size-full"></div>
                        </div>
                    </div>
                </div>
            </template>
        </div>
    </template>

    <!-- Placeholder for on-reload -->
    <?php foreach ($images as $image): ?>
        <div
            class="animate-on-transition relative aspect-product flex-shrink-0 overflow-hidden border-black md:rounded-2xl"
            :class="'hidden'"
        >
            <div class="flex items-center justify-center size-full bg-[--fade-in-bg] <?= $isContain ? 'p-[4%]' : '' ?>">
                <img
                    alt="<?= $escaper->escapeHtmlAttr($image['label'] || $productName) ?>"
                    title="<?= $escaper->escapeHtmlAttr($image['label'] || $productName) ?>"
                    class="object-center <?= $mixBackground ? 'mix-blend-darken' : '' ?> <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?>"
                    src="<?= $escaper->escapeUrl($image['medium_image_url']) ?>"
                />
            </div>
        </div>
    <?php endforeach; ?>
</div>
