<?php

declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Satoshi\Catalog\Block\Product\View;

/** @var View $block */
/** @var Escaper $escaper */

/** @var Product $product */
$product = $block->getProduct();
$productType = $product->getTypeId();
$productId = $product->getId();

/**
 * @see \Magento\Checkout\Block\Cart\Item\Configure::_prepareLayout
 */
$productInfoBlock = $block->getLayout()->getBlock('product.info');
$isPopup = $block->getData('is_popup') ?? false;

?>

<form method="post"
      action="<?= $escaper->escapeUrl($productInfoBlock->getSubmitUrl($product)) ?>"
      id="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
      class="animate-on-transition"
      @submit.prevent="addToCart($event)"
    <?php if ($product->getOptions()): ?>
        enctype="multipart/form-data"
    <?php endif; ?>
>
    <input type="hidden" name="product" value="<?= (int)$product->getId() ?>"/>
    <input type="hidden" name="selected_configurable_option" value=""/>
    <input type="hidden" name="related_product" id="related-products-field" value=""/>
    <input type="hidden" name="item" value="<?= (int)$block->getRequest()->getParam('id') ?>">
    <?= $block->getBlockHtml('formkey') ?>

    <?php foreach ($block->getChildNames() as $name): ?>
        <?= $block->getLayout()->getBlock($name)->setData('is_popup', $isPopup)->toHtml() ?>
    <?php endforeach; ?>
</form>
