<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Checkout\Helper\Cart;
use Magento\Framework\Escaper;


/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Product $product */
$product = $block->getProduct();
$productId = $product->getId();
$productType = $product->getTypeId();

/** @var ProductStockItem $stockItemViewModel */
$stockItemViewModel = $viewModels->require(ProductStockItem::class);
$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$defaultQty = $block->getProductDefaultQty() * 1;

$step = $stockItemViewModel->getQtyIncrements($product) ? $stockItemViewModel->getQtyIncrements($product) : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $defaultQty = ceil($defaultQty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string)$maxSalesQty) : 4) + (/* add one if decimal for separator */
    (int)$stockItemViewModel->isQtyDecimal($product));

$isPopup = $block->getData('is_popup') ?? false;
$isSmall = $block->getData('is_small') ?? false;

$isProductInCart = false;
if (in_array($productType, ['simple', 'virtual', 'downloadable'])) {
    $items = $this->helper(Cart::class)->getQuote()->getAllItems();

    foreach ($items as $item) {
        if ($item->getProductId() == $productId) {
            $isProductInCart = $item->getQty();
            break;
        }
    }
}

$hasVariants = $productType === 'configurable';
$isGroup = $productType === 'grouped';
$inStock = $product->isSaleable();

$isVariantsPopup = $isPopup && $hasVariants;

// hide on mobile always when out of stock, if in stock then hide on mobile when not popup & product is configurable, if popup hide if variant in cart
$hideOnMobile = false;
if (!$inStock) {
    $hideOnMobile = true;
} elseif ($isPopup) {
    $hideOnMobile = $isProductInCart;
} else {
    $hideOnMobile = $isGroup ?? $hasVariants;
}

?>
<div
    class="
        relative md:rounded-b-md max-md:px-3 w-full
        <?= ($isPopup) ? 'pb-2 max-md:px-4' : '' ?>
        <?= ($isPopup && $productType !== 'bundle') ? 'pt-4 shadow-fadeTop' : '' ?>
    "
>
    <?php if ($isPopup && $productType === 'bundle'): ?>
        <?= $block->getBlockHtml('bundle.summary') ?>
    <?php endif; ?>

    <div class="flex flex-grow flex-wrap justify-stretch gap-3 bg-bg-500 relative">
        <!-- Quantity Controls -->
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="contents <?= !$isPopup ? 'max-md:hidden' : '' ?>">
                <!-- Minus or remove -->
                <button
                    type="button"
                    class="
                        animate-on-transition button button--outline-secondary icon-button select-none
                        <?= $isSmall ? 'icon-button--size-sm' : 'icon-button--size-md md:icon-button--size-lg' ?>
                        <?= (!$isProductInCart || !$inStock) ? 'button--disabled' : '' ?>
                    "
                    :class="{
                        'button--disabled': (!isVariantInCart && variantQty === 1) || !<?= (int)$inStock ?>
                    }"
                    :aria-label="variantQty > 1 ? '<?= __('Decrease quantity') ?>' : '<?= __('Remove from cart') ?>'"
                    disabled="<?= (int)(!$isProductInCart || !$inStock) ?>"
                    :disabled="(!isVariantInCart && variantQty === 1) || !<?= (int)$inStock ?>"
                    @click.prevent.stop="decreaseQty()"
                >
                    <span class="sr-only">
                        <?= __('Decrease quantity for %1', $product->getName()) ?>
                    </span>
                    <span
                        x-show="variantQty < 2"
                        <?php if ($isProductInCart > 1): ?>
                            style="display: none"
                        <?php endif; ?>
                    >
                        <?= $hyvaicons->renderHtml('remove'); ?>
                    </span>
                    <span
                        x-show="variantQty > 1"
                        <?php if ($isProductInCart < 2): ?>
                            style="display: none"
                        <?php endif; ?>
                    >
                        <?= $hyvaicons->renderHtml('minus'); ?>
                    </span>
                </button>

                <label for="quantity <?= $isPopup ? 'mobile' : 'desktop' ?>" class="sr-only tracking-widest">
                    <?= __('Quantity') ?>
                </label>
                <input
                    <?php if ($stockItemViewModel->isQtyDecimal($product)): ?>
                        type="text"
                        pattern="[0-9]+(\.[0-9]{1,<?= /** @noEscape */
                        $maxSalesQtyLength ?>})?"
                        inputmode="decimal"
                    <?php else: ?>
                        type="number"
                        pattern="[0-9]{0,<?= /** @noEscape */
                        $maxSalesQtyLength ?>}"
                        inputmode="numeric"
                        <?php if ($minSalesQty): ?>min="<?= /** @noEscape */
                        $minSalesQty ?>"<?php endif; ?>
                        <?php if ($maxSalesQty): ?>max="<?= /** @noEscape */
                        $maxSalesQty ?>"<?php endif; ?>
                        <?php if ($step): ?>step="<?= /** @noEscape */
                        $step ?>"<?php endif; ?>
                    <?php endif; ?>
                    name="qty"
                    value="<?= $isProductInCart >= 1 ? $isProductInCart : ($block->getProductDefaultQty() * 1) ?>"
                    :value="variantQty"
                    class="animate-on-transition input__field flex-shrink-0 basis-11 px-3 text-center md:h-auto bg-transparent <?= $isSmall ? 'h-9' : '' ?>"
                    min="1"
                    @change.lazy="setQuantity($event.target.value)"
                    aria-label="<?= __('Quantity') ?>"
                    id="quantity <?= $isPopup ? 'mobile' : 'desktop' ?>"
                    :disabled="!<?= (int)$inStock ?>"
                    form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
                >

                <button
                    type="button"
                    class="animate-on-transition button button--outline-secondary icon-button select-none <?= $isSmall ? 'icon-button--size-sm' : 'icon-button--size-md md:icon-button--size-lg' ?>"
                    aria-label="<?= __('Increase quantity') ?>"
                    @click.prevent.stop="increaseQty()"
                    :class="{
                        'button--disabled': !<?= (int)$inStock ?>
                    }"
                    :disabled="!<?= (int)$inStock ?>"
                >
                    <span class="sr-only">
                        <?= __('Increase quantity') ?>
                    </span>
                    <?= $hyvaicons->renderHtml('plus'); ?>
                </button>
            </div>
        <?php endif; ?>


        <!-- Add to cart button -->
        <button
            <?php if ($isProductInCart || !$inStock): ?>
                style="display: none"
            <?php endif; ?>
            x-show="<?= (int)$inStock ?> && !isVariantInCart"
            class="
                <?= (in_array($productType, ['configurable', 'downloadable', 'grouped', 'bundle']) && !$isPopup) ? 'max-md:hidden' : '' ?>
                <?= $isSmall ? 'button--size-sm' : '' ?>
                animate-on-transition button button--filled-primary flex-grow
                <?= $isPopup ? 'max-sm:px-3' : '' ?>
            "
            :class="{
                'md:hidden': isVariantInCart || <?= (int)!$inStock ?>,
                'max-md:hidden': <?= (int)!$inStock ?> || (<?= (int)(!$isPopup && in_array($productType, ['configurable', 'downloadable', 'grouped', 'bundle'])) ?>) || (<?= (int)$isPopup ?> && isVariantInCart),
                'button--disabled': isProductBeingAdded || isProductBeingRemoved
            }"
            type="submit"
            form="product_addtocart_form_<?= $productId ?>_<?= $isPopup ? 'mobile' : 'desktop' ?>"
            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
            data-addto="cart"
            x-a11y-trap-target.end="$store.popup.currentPopup === productActionsPopup"
            :disabled="isProductBeingAdded || isProductBeingRemoved"
        >
            <span
                class="flex"
                x-show="!isProductBeingAdded && !isProductBeingRemoved"
            >
                <?= __('Add to cart') ?>
                <span class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>">
                    <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                </span>
            </span>
            <span style="display: none" x-show="isProductBeingRemoved">
                <?= __('Removing from cart...') ?>
            </span>
            <span style="display: none" x-show="isProductBeingAdded">
                <?= __('Adding...') ?>
            </span>
        </button>

        <!-- Select items, only for grouped products -->
        <button
            <?php if ($productType !== 'grouped'): ?>
                style="display: none"
            <?php endif; ?>
            class="animate-on-transition button button--filled-primary w-full md:hidden <?= $isSmall ? 'button--size-sm' : '' ?> <?= ($isPopup || $productType !== 'grouped') ? 'max-md:hidden' : '' ?>"
            @click.prevent="showProductActions()"
            :class="{
                'button--disabled': isProductBeingAdded || isProductBeingRemoved
            }"
            :disabled="isProductBeingAdded || isProductBeingRemoved"
            type="button"
        >
            <span
                x-show="!isProductBeingAdded && !isProductBeingRemoved"
                class="inline-flex items-center"
            >
                <?= __('Select items') ?>
                <span
                    class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>"
                >
                    <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                </span>
            </span>

            <span style="display: none" x-show="isProductBeingRemoved">
                <?= __('Removing from cart...') ?>
            </span>

            <span style="display: none" x-show="isProductBeingAdded">
                <?= __('Adding...') ?>
            </span>
        </button>

        <!-- Select options, for configurable product when variant not in cart -->
        <button
            <?php if ($isProductInCart): ?>
                style="display: none"
            <?php endif; ?>
            x-show="!isVariantInCart"
            class="animate-on-transition button button--filled-primary w-full md:hidden <?= $isSmall ? 'button--size-sm' : '' ?> <?= ($isPopup || !$hasVariants) ? 'max-md:hidden' : '' ?>"
            @click.prevent="showProductActions()"
            :class="{
                'button--disabled': isProductBeingAdded || isProductBeingRemoved
            }"
            :disabled="isProductBeingAdded || isProductBeingRemoved"
            type="button"
        >
            <span
                x-show="!isProductBeingAdded && !isProductBeingRemoved"
                class="inline-flex items-center"
            >
                <?= __('Select options') ?>
                <span
                    class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>"
                >
                    <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                </span>
            </span>

            <span style="display: none" x-show="isProductBeingRemoved">
                <?= __('Removing from cart...') ?>
            </span>

            <span style="display: none" x-show="isProductBeingAdded">
                <?= __('Adding...') ?>
            </span>
        </button>

        <!-- Select another option, for configurable when variant is in cart -->
        <button
            <?php if (!$isProductInCart || $isPopup || !$hasVariants): ?>
                style="display: none"
            <?php endif; ?>
            x-show="<?= (int)$hasVariants ?> && isVariantInCart && !<?= (int)$isPopup ?>"
            class="animate-on-transition button button--filled-primary w-full md:hidden <?= $isSmall ? 'button--size-sm' : '' ?>"
            @click.prevent="showProductActions()"
            type="button"
        >
            <span
                x-show="!isProductBeingAdded && !isProductBeingRemoved"
                class="inline-flex items-center"
            >
                <?= __('Select another option') ?>
                <span
                    class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>"
                >
                    <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                </span>
            </span>

            <span style="display: none" x-show="isProductBeingRemoved">
                <?= __('Removing from cart...') ?>
            </span>

            <span style="display: none" x-show="isProductBeingAdded">
                <?= __('Adding...') ?>
            </span>
        </button>

        <!-- Show links, for downloadable products -->
        <?php if ($productType === 'downloadable'): ?>
            <button
                <?php if ($isProductInCart || !$inStock || $isPopup): ?>
                    style="display: none"
                <?php endif; ?>
                x-show="<?= (int)!$isPopup ?> && !isVariantInCart"
                class="animate-on-transition button button--filled-primary w-full md:hidden <?= $isSmall ? 'button--size-sm' : '' ?>"
                @click.prevent="showProductActions()"
                type="button"
            >
                <span
                    x-show="!isProductBeingAdded && !isProductBeingRemoved"
                    class="inline-flex items-center"
                >
                    <?= __('Show links') ?>
                    <span
                        class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>"
                    >
                        <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                    </span>
                </span>

                <span style="display: none" x-show="isProductBeingRemoved">
                    <?= __('Removing from cart...') ?>
                </span>

                <span style="display: none" x-show="isProductBeingAdded">
                    <?= __('Adding...') ?>
                </span>
            </button>
        <?php endif; ?>

        <!-- Customize bundle, for bundle products -->
        <?php if ($productType === 'bundle'): ?>
            <button
                <?php if (!$inStock | $isPopup): ?>
                    style="display: none"
                <?php endif; ?>
                x-show="<?= (int)!$isPopup ?>"
                class="animate-on-transition button button--filled-primary w-full md:hidden <?= $isSmall ? 'button--size-sm' : '' ?>"
                @click.prevent="showProductActions()"
                type="button"
            >
                <span
                    x-show="!isProductBeingAdded && !isProductBeingRemoved"
                    class="inline-flex items-center"
                >
                    <?= __('Customize bundle') ?>
                    <span
                        class="button__icon button__icon--right <?= $isSmall ? 'text-lg' : '' ?>"
                    >
                        <?= $hyvaicons->renderHtml('shopping-bag'); ?>
                    </span>
                </span>

                <span style="display: none" x-show="isProductBeingRemoved">
                    <?= __('Removing from cart...') ?>
                </span>

                <span style="display: none" x-show="isProductBeingAdded">
                    <?= __('Adding...') ?>
                </span>
            </button>
        <?php endif; ?>

        <!-- Already in cart -->
        <button
            <?php if (!$isProductInCart): ?>
                style="display: none"
            <?php endif; ?>
            x-show="isVariantInCart"
            class="
                animate-on-transition button button--disabled button--outline-secondary flex-grow
                <?= $isSmall ? 'button--size-sm' : '' ?>
                <?= ($hasVariants || $productType === 'bundle') ? 'max-md:hidden' : '' ?>
                <?= $isPopup ? 'max-sm:px-3' : '' ?>
            "
            @click.prevent="$store.cart.showCart()"
            x-a11y-trap-target.end="$store.popup.currentPopup === productActionsPopup"
            type="button"
        >
        <span>
            <?= __('Already in cart') ?>
        </span>
        </button>

        <!-- Out of stock button -->
        <button
            <?php if ($isProductInCart || !$inStock): ?>
                style="display: none"
            <?php endif; ?>
            x-show="!isVariantInCart || <?= (int)$isPopup ?>"
            class="
                animate-on-transition button button--disabled button--outline-secondary flex-grow
                <?= $isSmall ? 'button--size-sm' : '' ?>
                <?= ($inStock || (!$isPopup && ($hasVariants || $productType === 'grouped'))) ? 'max-md:hidden' : '' ?>
                <?= $inStock ? 'md:hidden' : '' ?>
                <?= $isPopup ? 'max-sm:px-3' : '' ?>
            "
            disabled
            type="button"
        >
            <?= __('Out of stock') ?>
        </button>

        <!-- Show product button -->
        <a
            <?php if (!$isPopup || !$isProductInCart || $productType === 'downloadable'): ?>
                style="display: none"
            <?php endif; ?>
            x-show="<?= (int)($productType !== 'downloadable') ?> && (!isVariantInCart || <?= (int)$isPopup ?>)"
            class="animate-on-transition button button--outline-primary flex-grow md:hidden <?= $isPopup ? 'max-sm:px-3' : '' ?>"
            :class="{
                'max-md:hidden': !isVariantInCart || !<?= (int)$isPopup ?>
            }"
            href="#"
            @click.prevent="hideProductActions()"
        >
            <?= __('Show product') ?>
        </a>
    </div>
</div>

<?php
// TODO: Implement add to wishtlist / add to compare
// echo $block->getChildHtml('product.info.addtowishlist');
// echo $block->getChildHtml('product.info.addtocompare');
?>
<?php
// TODO: Implement email to a friend
// $block->getChildHtml('product.info.emailtofriend')
?>
