<?php

use Hyva\Theme\ViewModel\SvgIcons;

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

?>

<div x-data="Shipping()">
    <div
        @private-content-loaded.window="receiveCustomerData($event.detail.data)"
        x-data="Accordion(showEstimateShipping, 700)"
    >
        <button
            class="group flex w-full justify-between"
            x-ref="AccordionButton"
            :aria-expanded="isExpanded"
            aria-controls="estimation-panel"
            aria-labelledby="estimation-label"
            @click="toggleEstimateShipping()"
        >
            <h2
                class="grow text-start"
                id="estimation-label"
                x-text="cartTotals.is_virtual ? `<?= __('Estimate Tax') ?>` : `<?= __('Estimate Shipping and Tax') ?>`"
            >
            </h2>
            <div class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable">
                <span x-ref="AccordionIcon">
                    <?= $hyvaicons->renderHtml('chevron-up') ?>
                </span>
            </div>
        </button>
        <div
            x-cloak
            x-ref="AccordionPanel"
            class="overflow-hidden px-2 -mx-2"
            :class="{
                'transition-none': $store.main.isReducedMotion,
                'transition': $store.main.isReducedMotion,
            }"
            id="estimation-panel"
            role="region"
            aria-labelledby="estimation-label"
        >
            <div class="mt-3 text-text-500">
                <p x-text="cartTotals.is_virtual ? `<?= __('Enter your billing address to get a tax estimate.') ?>` : `<?= __('Enter your destination to get a shipping estimate.') ?>`"></p>

                <div
                    class="my-3 flex flex-col gap-3"
                    :class="{'md:flex-row': hasAvailableRegions()}"
                >
                    <div class="w-full">
                        <label
                            for="country_id"
                            class="sr-only tracking-widest"
                        ><?= __('Country') ?></label>
                        <select
                            name="country_id"
                            placeholder="<?= __('Country') ?>"
                            id="country_id"
                            class="input__field"
                            @change.debounce="setCountry($event.target.value)"
                        >
                            <option value=""><?= __('Country') ?></option>
                            <template
                                x-for="country in getSortedCountries()"
                                :key="country.id"
                            >
                                <option
                                    :value="country.id"
                                    x-text="country.name"
                                    :selected="cartData.address && country.id == cartData.address.countryId"
                                ></option>
                            </template>
                        </select>
                    </div>
                </div>

                <div
                    class="my-3 flex flex-col gap-3 md:flex-row"
                >
                    <template x-if="hasAvailableRegions()">
                        <div class="w-full">
                            <label
                                for="region_id"
                                class="sr-only tracking-widest"
                            >
                                <?= __('State/Province') ?>
                            </label>
                            <select
                                name="region_id"
                                placeholder="<?= __('State/Province') ?>"
                                id="region_id"
                                class="input__field"
                                @change.debounce="setRegion($event.target.value, 'select')"
                            >
                                <option value=""><?= __('State/Province') ?></option>
                                <template
                                    x-for="region in getAvailableRegions()"
                                    :key="region.id"
                                >
                                    <option
                                        :data-code="region.code"
                                        :value="region.id"
                                        x-text="region.name"
                                        :selected="cartData.address && region.id == cartData.address.regionId"
                                    ></option>
                                </template>
                            </select>
                        </div>
                    </template>

                    <template x-if="directoryData && !hasAvailableRegions()">
                        <div class="w-full">
                            <label
                                for="region"
                                class="sr-only tracking-widest"
                            ><?= __('State/Province') ?></label>
                            <input
                                type="text"
                                name="region"
                                placeholder="<?= __('State/Province') ?>"
                                id="region"
                                class="input__field"
                                @change.debounce="setRegion($event.target.value)"
                                :value="cartData.address && cartData.address.region"
                            >
                        </div>
                    </template>

                    <div class="w-full">
                        <label
                            for="postcode"
                            class="sr-only tracking-widest"
                        ><?= __('Zip/Postal Code') ?></label>
                        <input
                        type="text"
                        name="postcode"
                        placeholder="<?= __('Zip/Postal Code') ?>"
                        id="postcode"
                        class="input__field"
                        @input.debounce.1000ms="setPostcode($event.target.value)"
                        :value="cartData.address && cartData.address.postcode"
                        >
                    </div>
                </div>

                <template x-if="getEstimatedShippingRateCarriers().length > 0">
                    <div
                        class="pt-2 relative"
                        role="radiogroup"
                        aria-label="<?= __('Shipping Methods') ?>"
                    >
                        <template
                            x-for="carrier in getEstimatedShippingRateCarriers()"
                            :key="carrier"
                        >
                            <div>
                                <h4 class="font-semibold" x-text="carrier"></h4>
                                <template
                                    x-for="(rate, index) in getRatesForCarrier(carrier)"
                                    :key="index"
                                >
                                    <label class="flex items-center px-2 gap-2 cursor-pointer">
                                        <input
                                            class="mr-2 cursor-pointer"
                                            type="radio"
                                            :id="'shipping_method_' + rate.method_code"
                                            :value="rate.carrier_code + '_' + rate.method_code"
                                            x-model="shippingMethod"
                                            @change="updateShippingMethod()"
                                        />
                                        <span
                                            x-text="rate.method_title"
                                            class="break-words shrink hyphens-auto"
                                        ></span>
                                        <div class="flex flex-col justify-end ml-auto">
                                            <template
                                                x-if="$store.cart.cartTotals.review_shipping_display_mode === 'including' || $store.cart.cartTotals.review_shipping_display_mode === 'both'"
                                            >
                                                <span
                                                    x-text="`${hyva.formatPrice(rate.price_incl_tax)}`"
                                                    class="price-including-tax text-right"
                                                    data-label="<?= __('Incl. Tax') ?>"
                                                ></span>
                                            </template>
                                            <template
                                                x-if="$store.cart.cartTotals.review_shipping_display_mode === 'excluding' || $store.cart.cartTotals.review_shipping_display_mode === 'both'"
                                            >
                                                <span
                                                    x-text="`${hyva.formatPrice(rate.price_excl_tax)}`"
                                                    x-show="$store.cart.cartTotals.review_shipping_display_mode !== 'both' || rate.price_excl_tax !== rate.price_incl_tax"
                                                    class="price-excluding-tax"
                                                    data-label="<?= __('Excl. Tax') ?>"
                                                ></span>
                                            </template>
                                        </div>
                                    </label>
                                </template>
                            </div>
                        </template>
                    </div>
                </template>
            </div>
        </div>
    </div>
</div>
<hr class="divider -mx-4 contrast-more:bg-secondary-700">