<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Downloadable\Block\Customer\Products\ListProducts;
use Magento\Downloadable\Model\Link\Purchased\Item;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/** @var ListProducts $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php $items = $block->getItems(); ?>
<?php if (count($items)): ?>
    <div class="max-md:pt-7 max-md:border-t max-md:border-bg-600" data-content-wrapper>
        <!-- pagination-content -->
        <?php foreach ($items as $item): ?>
            <div class="overflow-x-auto card mb-5 bg-white p-5 rounded-xl break-words">
                <div class="grid gap-4 grid-cols-1 lg:grid-cols-6">
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Order')) ?></div>
                        <a
                            id="downloadableProduct<?= $escaper->escapeHtmlAttr($item->getPurchased()->getOrderId()) ?>"
                            href="<?= $escaper->escapeUrl($block->getOrderViewUrl($item->getPurchased()->getOrderId()))?>"
                            title="<?= $escaper->escapeHtml(__('View Order')) ?>"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . $item->getPurchased()->getOrderIncrementId()) ?>"
                            class="inline-block lg:mt-2 max-w-full"
                            x-element-transition-trigger
                        ><?= $escaper->escapeHtml('#' . $item->getPurchased()->getOrderIncrementId()) ?></a>
                    </div>
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Date')) ?></div>
                        <?php
                            $date = $item->getPurchased()->getCreatedAt();
                            $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
                            $formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
                            $formattedDate = $block->formatDate($date, $formatLong);
                            if (!$block->getDateFormat()) {
                                $formattedDate = (new DateTime($date))->format('M d, Y');
                            }
                        ?>
                        <time class="inline-block lg:mt-2 max-w-full" datetime="<?= $escaper->escapeHtmlAttr($block->formatDate($date, $format)); ?>">
                            <span aria-hidden="true"><?= $escaper->escapeHtml($formattedDate); ?></span>
                            <span class="sr-only">
                                <?= $escaper->escapeHtml($block->formatDate($date, $formatLong)); ?>
                            </span>
                        </time>
                    </div>
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Title')) ?></div>
                        <div class="lg:mt-2 max-lg:text-right">
                            <?= $escaper->escapeHtml($item->getPurchased()->getProductName()) ?>
                        </div>
                    </div>
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Download')) ?></div>
                        <?php if ($item->getStatus() == Item::LINK_STATUS_AVAILABLE): ?>
                            <a
                                href="<?= $escaper->escapeUrl($block->getDownloadUrl($item)) ?>"
                                class="inline-block lg:mt-2 text-sm underline text-secondary-darker max-lg:flex max-lg:items-center"
                                id="download_<?= /* @noEscape */ $item->getPurchased()->getProductId() ?>"
                                title="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                            >
                                <?= $heroicons->documentDownloadHtml(); ?>
                            </a>
                            <?php if ($block->getIsOpenInNewWindow()): ?>
                                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                    'onclick',
                                    "this.target='_blank'",
                                    'a#download_' . $item->getPurchased()->getProductId()
                                ) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Status')) ?></div>
                        <div class="lg:mt-2">
                            <?= $escaper->escapeHtml(__(ucfirst($item->getStatus()))) ?>
                        </div>
                    </div>
                    <div class="p-2 flex lg:block justify-between">
                        <div class="font-bold text-text-500 max-lg:mr-2"><?= $escaper->escapeHtml(__('Remaining downloads')) ?></div>
                        <div class="lg:mt-2">
                            <?= $escaper->escapeHtml($block->getRemainingDownloads($item)) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <!-- end-pagination-content -->
    </div>
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="toolbar downloadable-products-toolbar bottom">
            <?= $block->getChildHtml('pager') ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty mb-5">
        <span><?= $escaper->escapeHtml(__('You have no downloadable products.')) ?></span>
    </div>
<?php endif; ?>

<div>
    <a class="inline-block w-full md:w-auto text-center bg-primary-500 py-2.5 px-5 secondary rounded-lg text-white"
       :href="$store.main.getBackURL('<?= $escaper->escapeJs($block->getUrl('customer/account')) ?>')"
       x-element-transition-trigger
    >
        <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
    </a>
</div>
