<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Satoshi\SatoshiUi\Block\RichText;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Satoshi\SatoshiUi\Helper\Link as LinkHelper;

/** @var RichText $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
/** @var LinkHelper */
$linkHelper = $this->helper(LinkHelper::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$link_url = $decodeHelper->decodeJSONHTMLEntity($block->getData('button_link'));
$linkHref = $linkHelper->getLinkHref($block, $link_url);
?>
<div>
    <h2 class="heading mb-3 text-lg text-text-500 md:mb-5">
        <?= $escaper->escapeHtml($block->getData('heading')) ?>
    </h2>

    <?php if(!empty($block->getData('caption'))): ?>
        <p class="mb-3 text-base">
            <?= $escaper->escapeHtml($block->getData('caption')) ?>
        </p>
    <?php endif; ?>

    <div class="rte mb-7 text-text-500">
        <?= /* @noEscape */ str_replace('&quote;', '"', html_entity_decode($block->getData('content'))) ?>
    </div>

    <?php if(!empty($block->getData('button_label'))): ?>
        <a
            <?php if ($linkHref): ?>
                href="<?= $escaper->escapeUrl($linkHref); ?>"
                target="<?= $escaper->escapeHtmlAttr($linkHelper->getLinkTarget($link_url)); ?>"
            <?php endif; ?>
            class="text-text-500"
            x-element-transition-trigger
        >
            <span class="underline"><?= $escaper->escapeHtml($block->getData('button_label')) ?></span>
            <?= $hyvaicons->renderHtml('button-link', 'inline text-primary-500'); ?>
        </a>
    <?php endif; ?>
</div>