<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\SatoshiUi\Block\VideoHero;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Satoshi\SatoshiUi\Helper\Link as LinkHelper;

/** @var VideoHero $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
/** @var LinkHelper $linkHelper */
$linkHelper = $this->helper(LinkHelper::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$link_url = $decodeHelper->decodeJSONHTMLEntity($block->getData('button_link'));
$linkHref = $linkHelper->getLinkHref($block, $link_url);
$linkType = $block->getData('button_type');
$category = $block->getCategory() ?? null;

$videoUrl = $block->getData('video_source');
$heading = $block->getData('heading');
$description = $block->getData('description');
$overlayOpacity = $block->getData('overlay_opacity');
$autoplay = $block->getData('autoplay') == 'true';
$muted = $block->getData('muted') == 'true';
$loop = $block->getData('loop') == 'true';

$hasHeading = !empty($heading);
$hasDescription = !empty($description);
$hasButton = !empty($block->getData('button_label'));

$bannerHeight = $block->getData('banner_height');
$desktopAlignment = $block->getData('desktop_content_position');
$mobileAlignment = $block->getData('mobile_content_alignment');

?>
<div class="relative overflow-hidden">
    <div class="absolute left-0 top-0 z-10 h-full w-full bg-black" style="opacity: <?= $escaper->escapeHtmlAttr($overlayOpacity) ?>"></div>
    <?php if(str_ends_with($videoUrl, '.mp4')): ?>
        <video
            class="absolute left-0 top-0 z-0 h-full w-full object-cover object-center bg-cover bg-center"
            <?php if($block->getData('image')): ?>
                style="background-image: url('<?= $escaper->escapeUrl($block->getData('image')) ?>');"
            <?php endif; ?>
            <?= $muted ? 'muted' : '' ?>
            <?= $autoplay ? 'autoplay' : 'false' ?>
            <?= $loop ? 'loop' : '' ?>
            playsinline
        >
            <source src="<?= $escaper->escapeUrl($videoUrl) ?>" type="video/mp4">
        </video>
    <?php else: ?>
        <iframe
            src="<?= $escaper->escapeUrl($videoUrl) ?>"
            autoplay="<?= $autoplay ? 'true' : 'false' ?>"
            muted="<?= $muted ? 'true' : 'false' ?>"
            loop="<?= $loop ? 'true' : 'false' ?>"
            controls="false"
            class="absolute left-0 top-0 z-0 h-full w-full object-cover object-center"
            allow="autoplay; encrypted-media"
            allowfullscreen
            title="<?= $escaper->escapeHtml($heading) ?>"
        ></iframe>
    <?php endif; ?>
    <div
        class="content-wrapper relative z-20 m-auto flex
            <?= match($bannerHeight) {
                'small' => 'pb-12 pt-20 md:py-[5vh] h-[40vh]',
                'medium' => 'pb-12 pt-20 md:py-[10vh] h-[60vh]',
                'large' => 'pb-12 pt-20 md:py-[20vh] h-[calc(100svh-34px)] md:h-[80vh]',
                default => ''
            } ?>
            <?= match($mobileAlignment) {
                'top-left' => 'items-start justify-start',
                'top-center' => 'items-start justify-center',
                'top-right' => 'items-start justify-end',
                'middle-left' => 'items-center justify-start',
                'middle-center' => 'items-center justify-center',
                'middle-right' => 'items-center justify-end',
                'bottom-left' => 'items-end justify-start',
                'bottom-center' => 'items-end justify-center',
                'bottom-right' => 'items-end justify-end',
                default => ''
            } ?>
            <?= match($desktopAlignment) {
                'top-left' => 'md:items-start md:justify-start',
                'top-center' => 'md:items-start md:justify-center',
                'top-right' => 'md:items-start md:justify-end',
                'middle-left' => 'md:items-center md:justify-start',
                'middle-center' => 'md:items-center md:justify-center',
                'middle-right' => 'md:items-center md:justify-end',
                'bottom-left' => 'md:items-end md:justify-start',
                'bottom-center' => 'md:items-end md:justify-center',
                'bottom-right' => 'md:items-end md:justify-end',
                default => ''
            } ?>
        "
    >
        <div
            class="
                flex max-w-[335px] md:max-w-[510px] flex-col justify-center
                <?php if(str_contains($mobileAlignment, 'left')): ?>
                    items-start text-start
                <?php elseif(str_contains($mobileAlignment, 'right')): ?>
                    items-end text-end
                <?php else: ?>
                    items-center text-center
                <?php endif; ?>
                <?php if(str_contains($desktopAlignment, 'left')): ?>
                    md:items-start md:text-start
                <?php elseif(str_contains($desktopAlignment, 'right')): ?>
                    md:items-end md:text-end
                <?php else: ?>
                    md:items-center md:text-center
                <?php endif; ?>
            "
        >
            <?php if($hasHeading): ?>
                <h2
                    class="heading text-4xl leading-tight md:text-6xl md:leading-tight text-black"
                >
                    <?= $escaper->escapeHtml($heading) ?>
                </h2>
            <?php endif; ?>
            <?php if($hasDescription): ?>
                <p
                    class="text-lg font-medium text-primary-600 <?= $hasHeading ? 'mt-5' : '' ?>"
                >
                    <?= $escaper->escapeHtml($description) ?>
                </p>
            <?php endif; ?>
            <?php if($hasButton): ?>
                <a
                    <?php if ($linkHref): ?>
                        href="<?= $escaper->escapeUrl($linkHref); ?>"
                        target="<?= $escaper->escapeHtmlAttr($linkHelper->getLinkTarget($link_url)); ?>"
                    <?php endif; ?>
                    class="button button--filled-secondary <?= ($hasHeading || $hasDescription) ? 'mt-16' : '' ?>"
                    <?php if($linkType === 'category'): ?>
                        x-element-transition-trigger:category.animate="{
                            'title': `<?= $category['name'] ?? '' ?>`,
                            'url': `<?= $category['url'] ?? '' ?>`,
                            'img': `<?= $category['image'] ?? '' ?>`
                        }"
                    <?php else: ?>
                        x-element-transition-trigger
                    <?php endif; ?>
                >
                    <?= $escaper->escapeHtml($block->getData('button_label')) ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>
