<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\ProductAlert;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductAlert $productAlertViewModel */
$productAlertViewModel = $viewModels->require(ProductAlert::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId() || !$productAlertViewModel->showStockAlert($product)) {
    return;
}

$signupLabel = __("Notify me when this product is in stock");
?>
<div role="alert" class="flex items-center gap-2">
    <svg xmlns="http://www.w3.org/2000/svg" class="text-primary-800" viewBox="0 0 24 24">
        <path
            d="M12 22a2.98 2.98 0 0 0 2.818-2H9.182A2.98 2.98 0 0 0 12 22zm7-7.414V10c0-3.217-2.185-5.927-5.145-6.742C13.562 2.52 12.846 2 12 2s-1.562.52-1.855 1.258C7.185 4.074 5 6.783 5 10v4.586l-1.707 1.707A.996.996 0 0 0 3 17v1a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-1a.996.996 0 0 0-.293-.707L19 14.586z"/>
    </svg>

    <a href="<?= $escaper->escapeUrl($productAlertViewModel->getSaveUrl($currentProduct->get(), 'stock')) ?>"
       title="<?= $escaper->escapeHtml($signupLabel) ?>"
       x-element-transition-trigger
    ><?= $escaper->escapeHtml($signupLabel) ?></a>
</div>
