<?php

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var AbstractProduct $block */

$product = $block->getData('product') ?? null;
$class = $block->getData('class') ?? '';
$isSearch = $block->getData('is_search') ?? false;
?>

<?php if ($product): ?>
    <?php
        $price = $product->getPrice();
        $finalPrice = $product->getFinalPrice();
    ?>
    <?php if ($price > $finalPrice): ?>
        <div class="card-product__badge-container z-10 rounded-[40px] bg-bg-500 px-3 text-sm <?= $class ?>" x-element-transition-skip='{"transformOrigin": "left bottom"}'>
            <span class="font-semibold">
                -<?= round((($price - $finalPrice) * 100.0) / $price) ?>% <?= $escaper->escapeHtml(__('OFF')) ?>
            </span>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div
        x-data="
            {
                <?php if($isSearch): ?>
                    finalPrice: product.price_range.minimum_price.final_price.value,
                    regularPrice: product.price_range.minimum_price.regular_price.value
                <?php else: ?>
                    finalPrice: $store['transition'].pageData?.finalPrice,
                    regularPrice: $store['transition'].pageData?.regularPrice
                <?php endif; ?>
            }
        "
        class="card-product__badge-container z-10 rounded-[40px] bg-bg-500 px-3 text-sm <?= $class ?>"
        x-show="regularPrice>finalPrice && regularPrice"
    >
        <span x-text="'-' + Math.round(((regularPrice - finalPrice) * 100.0) / regularPrice) + '% OFF'" class="font-semibold">
        </span>
    </div>
<?php endif; ?>