<?php

declare(strict_types=1);

use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Catalog\Block\Product\View as ProductView;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ProductView $block */
/** @var ViewModelRegistry $viewModels */

$hyvaicons = $viewModels->require(SvgIcons::class);
$product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()): ?>
  <div id="bundleSummary">
    <?= $block->getChildHtml('product.info.form') ?>
    <?= $block->getChildHtml("product.price.tier") ?>
    <div x-data="initBundleSummary()"
         x-bind="eventListeners"
    >
      <div x-show="selectedOptions.length">
        <ul class="bundle items">
          <template x-for="option in selectedOptions">
            <li class="mb-3" x-show="option.products.length">
              <span class="font-semibold" x-html="option.label"></span>
              <template x-for="product in option.products">
                <div><span x-html="product.qty"></span> x <span x-html="product.name"></span></div>
              </template>
            </li>
          </template>
        </ul>
      </div>
      <div class="flex items-center justify-between gap-5">
        <h2 class="font-semibold text-text-500" id="bundle_summary_label">
          <?= $escaper->escapeHtml(__('Total')) ?>
        </h2>

        <div class="font-semibold">
          <?= $block->getChildHtml("product.info.bundle.price") ?>
        </div>
      </div>
    </div>
    <script>
      // TODO: Move to alpine files
      function initBundleSummary() {
        return {
          selectedOptions: [],
          eventListeners: {
            ['@update-bundle-option-selection.window'](event) {
              this.selectedOptions = event.detail;
            }
          }
        }
      }
    </script>
  </div>
<?php endif; ?>
