<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);


if (!$product->getId() || !$wishlistViewModel->isEnabled()) {
    return;
}
/**
 * When visiting wishlist/index/configure, the current class is Magento\Wishlist\Block\Item\Configure
 * In that case we take the form parameters from the existing wishlist item
 */
$updateParams = $block->getUpdateParams() ?: null;
?>

<button x-data="Wishlist('<?= $updateParams ?>', '<?= $product->getSku(); ?>')"
        @click.prevent="!currentWishListItem || !Object.keys(currentWishListItem).length ? addToWishlist(<?= (int)$product->getId() ?>) : removeFromWishlist()"
        title="<?= $escaper->escapeHtmlAttr(
            ($updateParams) ? __('Update Wish List') : __('Add to Wish List')
        ) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(
            ($updateParams) ? __('Update Wish List') : __('Add to Wish List')
        ) ?>"
        id="add-to-wishlist"
        data-addto="wishlist"
>
    <span x-show="!currentWishListItem || !Object.keys(currentWishListItem).length">
        <?= $hyvaicons->renderHtml('wishlist-plus', 'text-3xl'); ?>
    </span>
    <span x-show="Object.keys(currentWishListItem).length">
        <?= $hyvaicons->renderHtml('wishlist-minus', 'text-3xl'); ?>
    </span>

</button>
