<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div x-data="{
        isVariantInCart: false,
        isVariantAvailable: true,
        isProductBeingAdded: false,
        isProductBeingRemoved: false,
        variantCount: 1,
        isPopup: false
    }">

    <button
        type="button"
        x-show="isVariantAvailable && (variantCount > 1) && isVariantInCart && !isPopup"
        class="animate-on-transition button button--filled-primary w-full md:hidden"
        @click.prevent="showProductActions()"
    >
        <span>
            <?= $escaper->escapeHtml(__('Select Another Option')) ?>
        </span>
        <span class="button__icon button__icon--right">
            <?= $hyvaicons->renderHtml('cart-empty'); ?>
        </span>
    </button>

    <button
        type="button"
        x-show="(!isVariantInCart || isPopup) && isVariantAvailable"
        class="animate-on-transition button button--filled-primary flex-grow max-md:hidden"
        @click.prevent="addToCart()"
        x-a11y-trap-target.end="$store.popup.currentPopup === productActionsPopup"
        :class="{
            'max-md:hidden': (variantCount > 1) && (!isPopup || (isPopup && isVariantInCart)),
            'button--disabled': isProductBeingAdded || isProductBeingRemoved
        }"
        :disabled="isProductBeingAdded || isProductBeingRemoved"
    >
        <span class="flex" x-show="!isProductBeingAdded && !isProductBeingRemoved">
            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
            <span class="button__icon button__icon--right">
                <?= $hyvaicons->renderHtml('cart-empty'); ?>
            </span>
        </span>
        <span x-show="isProductBeingRemoved">
            <?= $escaper->escapeHtml(__('Removing from cart...')) ?>
        </span>
        <span x-show="isProductBeingAdded">
            <?= $escaper->escapeHtml(__('Adding...')) ?>
        </span>
    </button>
</div>

<?= $block->getChildHtml('', true) ?>
