<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Catalog\Model\Product;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var CatalogOutputHelper $output */
/** @var Attributes $block */
/** @var ViewModelRegistry $viewModels */

$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var Product $product */
$product = $block->getProduct();
?>


<?php if ($attributes = $block->getAdditionalData()): ?>
    <div x-data="Accordion('true', 300)">
        <div
            class="align-start animate-on-transition flex flex-col"
        >
            <button class="flex items-center justify-between"
                    type="button"
                    x-ref="AccordionButton"
                    :aria-expanded="isExpanded"
                    aria-controls="attributes_panel"
                    aria-labelledby="attributes_label">
                <p class="text-base font-semibold leading-tight text-text-500">
                    <?= $block->getTitle() ? $escaper->escapeHtml($block->getTitle()) : '&nbsp;' ?>
                </p>
                <span x-ref="AccordionIcon" class="button button--outline-secondary icon-button icon-button--size-xs">
                <?= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
            </span>
            </button>
        </div>
        <div x-ref="AccordionPanel"
             :inert="!isExpanded"
             class="overflow-hidden"
             x-cloak
             id="attributes_panel"
             role="region"
             aria-labelledby="attributes_label">
            <div class="mt-3 overflow-hidden text-text-100 contrast-more:text-secondary-700">
                <div class="table-wrapper max-w-prose overflow-x-auto" id="product-attributes">
                    <table class="additional-attributes w-full">
                        <?php foreach ($attributes as $attribute): ?>
                            <tr class="border-b border-gray-300 last:border-b-0">
                                <th class="col label w-1/2 py-2 text-left text-gray-700 font-normal product-attribute-label"
                                    scope="row"><?= $escaper->escapeHtml($attribute['label']) ?></th>
                                <td class="col data w-1/2 py-2 pl-2 text-left text-gray-900 product-attribute-value"
                                    data-th="<?= $escaper->escapeHtmlAttr($attribute['label']) ?>"
                                ><?= /* @noEscape */
                                    $catalogOutputHelper->productAttribute($product, $attribute['value'], $attribute['code']) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
