<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Catalog\Helper\Image;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

$images = $block->getGalleryImages()->getItems();


$smallWidth = $block->getImageAttribute('product_page_image_small', 'width', 90);
$smallHeight = $block->getImageAttribute('product_page_image_small', 'height', 90);
$mediumWidth = $block->getImageAttribute('product_page_image_medium', 'width', 700);
$mediumHeight = $block->getImageAttribute('product_page_image_medium', 'height', 700);

$productName = $block->getProduct()->getName();
?>

<div
    class="flex w-full flex-col gap-4 md:grid md:grid-cols-[repeat(auto-fit,1fr)] md:gap-5 md:pb-7 lg:grid-cols-[repeat(auto-fit,minmax(300px,1fr))] max-md:-mt-8 "
>


    <?php foreach ($block->getGalleryImages() as $index => $image): ?>
        <div
            class="animate-on-transition relative flex-shrink-0 overflow-hidden border-black rounded-xl border-opacity-[var(--media-border-opacity)]"
        >
            <div class="aspect-product w-full object-cover object-center">
                <img
                    src="<?= $image['url'] ?>"
                    alt="<?= $this->escapeHtmlAttr($image['caption']) ?: $this->escapeHtmlAttr(__('%1 thumbnail', $productName)) ?>"
                    title="<?= $this->escapeHtmlAttr($image['caption']) ?: $this->escapeHtmlAttr(__('%1 thumbnail', $productName)) ?>"
                    class="w-full object-contain"
                    loading="lazy"

                />
            </div>
        </div>
    <?php endforeach; ?>
    <?php // TODO: Implement videos in gallery ?>
</div>
