<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productName = $block->getProduct()->getName();
$images = json_decode($block->getGalleryImagesJson(), true);
?>

<div
    id="gallery"
    x-data='Gallery(<?= json_encode($block->getGalleryImagesJson()) ?>)'
    class="flex w-full flex-col gap-4 md:grid md:grid-cols-[repeat(auto-fit,1fr)] md:gap-5 md:pb-7 lg:grid-cols-[repeat(auto-fit,minmax(300px,1fr))] max-md:-mt-8"
>
    <?php foreach ($images as $index => $image): ?>
        <div
            class="bg-white animate-on-transition relative flex-shrink-0 overflow-hidden border-black rounded-xl">
            <div class="aspect-product w-full object-cover object-center">
                <img
                    alt="<?= $escaper->escapeHtmlAttr($image['caption'] ?? $productName) ?>"
                    title="<?= $escaper->escapeHtmlAttr($image['caption'] ?? $productName) ?>"
                    class="absolute inset-0 object-contain object-center w-full m-auto max-h-screen-75"
                    loading="lazy"
                    src="<?= $image['img'] ?>"
                />
                <?php if ($image['type'] === 'video' && !in_array($index, $playingVideoIndexes ?? [])): ?>
                    <button
                        type="button"
                        class="group absolute inset-0 outline-offset-2 grid place-items-center"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Play video')) ?>"
                        @click="activateVideo(<?= $index ?>)"
                    >
                        <?= $heroiconsSolid->playHtml(
                            'stroke-white/75 fill-black/20 transition ease-in group-hover:scale-110 md:w-24 md:h-24',
                            44,
                            44,
                            ['aria-hidden' => 'true']
                        ); ?>
                    </button>
                <?php endif; ?>
                <?php if ($image['type'] === 'video'): ?>
                    <div class="absolute inset-0 hidden w-full h-full bg-black nonmobile"
                         :class="{ 'hidden': activeVideoType !== 'youtube' }"
                         x-transition.opacity.duration.500ms
                         x-show="activeVideoType === 'youtube' && playingVideoIndexes.includes(<?= $index ?>)"
                    >
                        <div id="youtube-player-<?= $index ?>" class="w-full h-full"></div>
                    </div>
                    <div class="absolute inset-0 hidden w-full h-full bg-white"
                         :class="{ 'hidden': activeVideoType !== 'vimeo' }"
                         x-transition.opacity.duration.500ms
                         x-show="activeVideoType === 'vimeo'"
                    >
                        <div id="vimeo-player-<?= $index ?>" class="w-full h-full"></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
