<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productName = $block->getProduct()->getName();
$images = json_decode($block->getGalleryImagesJson(), true);
$firstImage = array_shift($images);

$isContain = false;

?>

<div
    id="gallery"
    x-data='Gallery(<?= json_encode($block->getGalleryImagesJson()) ?>)'
    class="flex w-full flex-col gap-4 md:grid md:grid-cols-[repeat(auto-fit,1fr)] md:gap-5 md:pb-7 lg:grid-cols-[repeat(auto-fit,minmax(300px,1fr))] max-md:-mt-8"
>
    <div
        class="relative flex aspect-product flex-shrink-0 items-center justify-center overflow-hidden border-black bg-[--fade-in-bg] md:rounded-2xl max-md:hidden"
    >
        <div
            x-data="
          TransitionImage({
            src: '<?= $firstImage['img'] ?>',
            imageId: 'firstImage'
          })
        "
            x-show="!!src"
            class="<?= $isContain ? 'p-[4%] size-full' : 'size-full' ?> hide-unless-transition absolute inset-0 z-10 flex items-center justify-center bg-[--fade-in-bg] {% if is_contain %}p-[4%]{% endif %} transition-opacity delay-1000 duration-300"
            :class="{ 'opacity-0': isImgLoaded }"
        >
            <img
                height="100%"
                width="100%"
                class="
                <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?>
                "
                :src="src"
            >
        </div>
        <div class="
                flex items-center justify-center
                <?= $isContain ? 'p-[4%] size-full' : 'size-full' ?>
              ">
            <img
                class="
                object-center no-fade
                <?= $isContain ? 'object-contain rounded-2xl max-h-full w-auto' : 'object-cover size-full' ?>
              "
                src="<?= $firstImage['img'] ?>"
                alt=""
                id="firstImage"

            >
        </div>
        <?=
            $template
                ->setData(['image' => $firstImage, 'index' => 0])
                ->render('Magento_Catalog::product/view/video.phtml');
        ?>
    </div>

    <?php foreach ($images as $index => $image): ?>
        <div
            class="animate-on-transition relative aspect-product flex-shrink-0 overflow-hidden border-black md:rounded-2xl">
            <div class="flex items-center justify-center size-full">
                <img
                    alt="<?= $escaper->escapeHtmlAttr($image['caption'] ?? $productName) ?>"
                    title="<?= $escaper->escapeHtmlAttr($image['caption'] ?? $productName) ?>"
                    class="object-cover size-full"
                    loading="lazy"
                    src="<?= $image['img'] ?>"
                />
                <?=
                    $template
                        ->setData(['image' => $image, 'index' => $index + 1])
                        ->render('Magento_Catalog::product/view/video.phtml');
                ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
