<?php

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var View $block */

$images = $block->getGalleryImages()->getItems();
$productName = $block->getProduct()->getName();
$product = $block->getData('product');
if ($product) {
    $price = $product->getPrice();
    $finalPrice = $product->getData('final_price');
    if ($price && $finalPrice) {
        $difference = $price - $finalPrice;
        $discountPercentage = round(($difference * 100.0) / $price);
    }
}
?>

<div
    class="md:content-wrapper relative z-30 mx-auto flex w-full flex-col justify-center gap-4 md:grid md:grid-cols-[1fr_250px] md:items-start md:gap-8 lg:grid-cols-[1fr_330px] xl:grid-cols-[1fr_400px] xl:gap-16"
>
    <!-- Desktop gallery -->
    <div class="contents max-md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>


    <!-- Product details -->
    <div
        class="product-details md:sticky md:top-[--scroll-top] md:pb-7"
        x-sticky-scroll="
      {
        container: $refs.scrollContainer,
        top: $refs.scrollContainer ? (window.innerHeight > 1080 ? 24 : 72) : 90,
        bottom: $refs.scrollContainer ? (window.innerHeight > 1080 ? 300 : 100) : 24,
      }
    "
    >
        <div class="mb-4 md:hidden">
            <?php if ($images): ?>
                <div class="relative flex aspect-product min-h-0 justify-center p-[4%]">
                    <div
                        class="hide-unless-transition absolute inset-0 z-10 flex items-center justify-center transition-opacity delay-1000 duration-300"
                        x-data="TransitionImage({
                            src: ($store['transition'].pageData?.productImg || $store['transition'].pageData?.variantImg),
                            imageId: 'id'
                        })"
                        x-show="!!src"
                        :class="{ 'opacity-0': isImgLoaded }"
                    >
                        <img
                            height="100%"
                            width="100%"
                            class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                            :src="src"
                        >
                    </div>
                    <img
                        height="100%"
                        width="100%"
                        class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                        alt="<?= $escaper->escapeJs($productName) ?>"
                        title="<?= $escaper->escapeJs($productName) ?>"
                        class=" inset-0 object-contain object-center w-full h-full m-auto"
                        loading="lazy"
                        src="<?= reset($images)['medium_image_url'] ?>"
                    >
                    <div>
                        <?=
                        $template
                            ->setData([
                                'product' => $product,
                            ])
                            ->render('Magento_Catalog::/product/list/discount-badge.phtml')
                        ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <?= $block->getChildHtml('product.details.info') ?>
    </div>

    <!-- Mobile Gallery -->
    <div class="contents md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>
</div>
