<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;
use Magento\Catalog\Helper\Image;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var View $block */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);


$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, [$block, 'isMainImage']));
if (!empty($images) && empty($mainImage)) {
    $mainImage = reset($images);
}
$helper = $this->helper(Image::class);
$mainImageUrl = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$galleryOptionVideoLoop = $storeConfig->getStoreConfig('catalog/product_video/video_auto_restart') ?? false;

$product = $block->getProduct();
$productName = $product->getName();
if ($product) {
    $price = $product->getPrice();
    $finalPrice = $product->getData('final_price');
    if ($price && $finalPrice) {
        $difference = $price - $finalPrice;
        $discountPercentage = round(($difference * 100.0) / $price);
    }
}
?>

<div
    class="md:content-wrapper relative z-30 mx-auto flex w-full flex-col justify-center gap-4 md:grid md:grid-cols-[1fr_250px] md:items-start md:gap-8 lg:grid-cols-[1fr_330px] xl:grid-cols-[1fr_400px] xl:gap-16"
    x-data='Gallery(<?= json_encode($block->getGalleryImagesJson()) ?>, <?= (int) !!($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct') === 'append') ?>, <?= (int) !!$galleryOptionVideoLoop ?>)'
    x-bind="eventListeners"
>
    <!-- Desktop gallery -->
    <div class="contents max-md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>


    <!-- Product details -->
    <div
        class="product-details md:sticky md:top-[--scroll-top] md:pb-7"
        x-sticky-scroll="
            {
                container: $refs.scrollContainer,
                top: $refs.scrollContainer ? (window.innerHeight > 1080 ? 24 : 72) : 90,
                bottom: $refs.scrollContainer ? (window.innerHeight > 1080 ? 300 : 100) : 24,
            }
        "
    >
        <!-- Mobile main image -->
        <div class="mb-4 md:hidden">
            <div class="relative flex aspect-product min-h-0 justify-center">
                <div
                    class="hide-unless-transition absolute inset-0 z-10 flex items-center justify-center transition-opacity delay-1000 duration-300"
                    x-data="TransitionImage({
                        src: '<?= $mainImageUrl ?>',
                        imageId: 'mobile-image'
                    })"
                    x-show="!!src"
                    :class="{ 'opacity-0': isImgLoaded }"
                >
                    <img
                        height="100%"
                        width="100%"
                        class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                        :src="src"
                    >
                </div>
                <img
                    id="mobile-image"
                    height="100%"
                    width="100%"
                    class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                    alt="<?= $escaper->escapeHtmlAttr($mainImage ? $mainImage->getData('label') : $productName) ?>"
                    class=" inset-0 object-contain object-center w-full h-full m-auto"
                    loading="lazy"
                    src="<?= $mainImageUrl ?>"
                >
                <div>
                    <?=
                    $template
                        ->setData([
                            'product' => $product,
                        ])
                        ->render('Magento_Catalog::/product/list/discount-badge.phtml')
                    ?>
                </div>

                <?php if($mainImage->getData('media_type') && str_contains($mainImage->getData('media_type'), 'video')): ?>
                    <template x-if="$store.main.isMobile">
                        <div class="contents">
                            <!-- Play button -->
                            <button
                                type="button"
                                class="group absolute inset-0 grid place-items-center"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Play video')) ?>"
                                @click="activateVideo(<?= $mainImage->getData('position') ?>)"
                                @keydown.enter="activateVideo(<?= $mainImage->getData('position') ?>)"
                                x-cloak
                            >
                                <?= $heroiconsSolid->playHtml(
                                    'stroke-white/75 fill-black/20 transition ease-in group-hover:scale-110 md:w-24 md:h-24',
                                    44,
                                    44,
                                    ['aria-hidden' => 'true']
                                ); ?>
                            </button>
        
                            <!-- Youtube container -->
                            <div class="absolute inset-0 hidden size-full bg-white"
                                :class="{ 'hidden': activeVideoType !== 'youtube' }"
                                x-transition.opacity.duration.500ms
                                x-show="activeVideoType === 'youtube'"
                            >
                                <div id="youtube-player-<?= $mainImage->getData('position') ?>" class="size-full"></div>
                            </div>
        
                            <!-- Video container -->
                            <div class="absolute inset-0 hidden size-full bg-white"
                                :class="{ 'hidden': activeVideoType !== 'vimeo' }"
                                x-transition.opacity.duration.500ms
                                x-show="activeVideoType === 'vimeo'"
                            >
                                <div id="vimeo-player-<?= $mainImage->getData('position') ?>" class="size-full"></div>
                            </div>
                        </div>
                    </template>
                <?php endif; ?>

            </div>
        </div>
        <?= $block->getChildHtml('product.details.info') ?>
    </div>

    <!-- Mobile Gallery -->
    <div class="contents md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>
</div>
