<?php

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */
?>

<div>
    <div class="flex flex-wrap justify-between mb-8">
        <?= $block->getChildHtml('product.title') ?>
        <?= $block->getChildHtml('product.info') ?>
    </div>
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
    <?= $block->getChildHtml('product.info.details') ?>
    <?= $block->getChildHtml('product.share') ?>
    <?= $block->getChildHtml('product.hide') ?>
</div>
