<?php

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var View $block */

$images = $block->getGalleryImages()->getItems();
$productName = $block->getProduct()->getName();
?>

<div
    class="md:content-wrapper relative z-30 mx-auto flex w-full flex-col justify-center gap-4 md:grid md:grid-cols-[1fr_250px] md:items-start md:gap-8 lg:grid-cols-[1fr_330px] xl:grid-cols-[1fr_400px] xl:gap-16"
>
    <!-- Desktop gallery -->
    <div class="contents max-md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>


    <!-- Product details -->
    <div
        class="product-details md:sticky md:top-[--scroll-top] md:pb-7"
        x-sticky-scroll="
      {
        container: $refs.scrollContainer,
        top: $refs.scrollContainer ? (window.innerHeight > 1080 ? 24 : 72) : 90,
        bottom: $refs.scrollContainer ? (window.innerHeight > 1080 ? 300 : 100) : 24,
      }
    "
    >
        <div class="mb-4 md:hidden">
            <?php if ($images): ?>
                <div class="relative flex aspect-product min-h-0 justify-center">
                    <div
                        class="hide-unless-transition absolute inset-0 z-10 flex items-center justify-center transition-opacity delay-1000 duration-300"
                        x-data="TransitionImage({
                            src: ($store['transition'].pageData?.productImg || $store['transition'].pageData?.variantImg),
                            imageId: 'id'
                        })"
                        x-show="!!src"
                        :class="{ 'opacity-0': isImgLoaded }"
                    >
                        <img
                            height="100%"
                            width="100%"
                            class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                            :src="src"
                        >
                    </div>
                    <img
                        height="100%"
                        width="100%"
                        class="max-h-full w-auto object-center object-cover h-full mix-blend-darken"
                        alt="<?= $escaper->escapeJs($productName) ?>"
                        title="<?= $escaper->escapeJs($productName) ?>"
                        class=" inset-0 object-contain object-center w-full h-full m-auto"
                        loading="lazy"
                        src="<?= reset($images)['medium_image_url'] ?>"
                    >
<!--                    --><?php //if ($product): ?>
<!--                        --><?php
//                        $badgeClass = 'md:hidden ' . $settings->getBadgePosition();
//                        ?>
<!--                        <div class="--><?php //= $badgeClass ?><!--">-->
<!--                            --><?php //= $this->render('_discount-badge.phtml', ['product' => $product->getSelectedOrFirstAvailableVariant()]) ?>
<!--                        </div>-->
<!--                    --><?php //endif; ?>
<!--                </div>-->
<!--            --><?php //else: ?>
<!--                --><?php //= $this->render('_product-missing-image.phtml', ['is_gift' => $product->isGiftCard()]) ?>
            <?php endif; ?>
        </div>
        <?= $block->getChildHtml('product.details.info') ?>
    </div>

    <!-- Mobile Gallery -->
    <div class="contents md:hidden">
        <?= $block->getChildHtml('product.media') ?>
    </div>
</div>
