<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Product $product */
$product = $block->getProduct();

/** @var ProductStockItem $stockItemViewModel */
$stockItemViewModel = $viewModels->require(ProductStockItem::class);
$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$defaultQty = $block->getProductDefaultQty() * 1;

$step = $stockItemViewModel->getQtyIncrements($product)
    ? $stockItemViewModel->getQtyIncrements($product)
    : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $defaultQty = ceil($defaultQty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string)$maxSalesQty) : 4)
    + (/* add one if decimal for separator */
    (int)$stockItemViewModel->isQtyDecimal($product));

?>
<?php if ($block->shouldRenderQuantity()): ?>
    <script>
        function initQtyField() {
            function findPathParam(key) {
                // get all path pairs after BASE_URL/front_name/action_path/action
                const baseUrl = (BASE_URL.substring(0, 2) === '//' ? 'http:' : '') + BASE_URL;
                const baseUrlParts = (new URL(baseUrl)).pathname.replace(/\/$/, '').split('/');
                const pathParts = window.location.pathname.split('/').slice(baseUrlParts.length + 3);
                for (let i = 0; i < pathParts.length; i += 2) {
                    if (pathParts[i] === key && pathParts.length > i) {
                        return pathParts[i + 1];
                    }
                }
            }

            return {
                qty: <?= /** @noEscape */ $defaultQty ?>,
                itemId: (new URLSearchParams(window.location.search)).get('id') || findPathParam('id'),
                productId: '<?= (int)$product->getId() ?>',
                step: <?= $step ?: '1' ?>, // Add step to the data
                min: <?= $minSalesQty ?: '0' ?>, // Add min to the data
                max: <?= $maxSalesQty ?: 'Infinity' ?>, // Add max to the data

                increaseQty() {
                    if (this.qty + this.step <= this.max) {
                        this.qty = Math.min(this.qty + this.step, this.max);
                        this.$dispatch('update-qty-' + this.productId, this.qty);
                    }
                },
                decreaseQty() {
                    if (this.qty - this.step >= this.min) {
                        this.qty = Math.max(this.qty - this.step, this.min);
                        this.$dispatch('update-qty-' + this.productId, this.qty);
                    }
                },
                onGetCartData(data, $dispatch) {
                    const cart = data && data.data && data.data.cart;
                    if (this.itemId && cart && cart.items) {
                        const cartItem = cart.items.find((item) => {
                            return item.item_id === this.itemId && item.product_id === this.productId;
                        });
                        if (cartItem && cartItem.qty) {
                            this.qty = cartItem.qty;
                            $dispatch('update-qty-' + this.productId, this.qty);
                        }
                    }
                }
            };
        }
    </script>
    <div x-data="initQtyField()"
         x-init="$dispatch('update-qty-<?= (int)$product->getId() ?>', qty)"
    >
        <?php if ($product->isSaleable()): ?>
            <button type="button"
                    class="animate-on-transition h-full w-12 input__field flex-shrink-0 basis-14 text-center"
                    :class="{ 'cursor-not-allowed opacity-50': qty <= min }"
                    @click="decreaseQty"
                    :disabled="qty <= min">
                -
            </button>
            <label for="qty[<?= (int)$product->getId() ?>]"
                   class="sr-only">
                <?= $escaper->escapeHtml(__('Quantity')) ?>
            </label>
            <input name="qty"
                   @private-content-loaded.window="onGetCartData($event.detail, $dispatch)"
                   id="qty[<?= (int)$product->getId() ?>]"
                   form="product_addtocart_form"
                <?php if ($stockItemViewModel->isQtyDecimal($product)): ?>
                    type="text"
                    pattern="[0-9]+(\.[0-9]{1,<?= /** @noEscape */
                    $maxSalesQtyLength ?>})?"
                    inputmode="decimal"
                <?php else: ?>
                    type="number"
                    pattern="[0-9]{0,<?= /** @noEscape */
                    $maxSalesQtyLength ?>}"
                    inputmode="numeric"
                    <?php if ($minSalesQty): ?>min="<?= /** @noEscape */
                    $minSalesQty ?>"<?php endif; ?>
                    <?php if ($maxSalesQty): ?>max="<?= /** @noEscape */
                    $maxSalesQty ?>"<?php endif; ?>
                    <?php if ($step): ?>step="<?= /** @noEscape */
                    $step ?>"<?php endif; ?>
                <?php endif; ?>
                   :value="qty"
                   value="<?= $block->getProductDefaultQty() * 1 ?>"
                   class="animate-on-transition h-full w-14 input__field flex-shrink-0 basis-14 text-center"
                   x-model.number="qty"
                   @input="$dispatch('update-qty-<?= (int)$product->getId() ?>', qty)"
            />
            <button type="button"
                    class="animate-on-transition h-full w-12 input__field flex-shrink-0 basis-14 text-center"
                    :class="{ 'cursor-not-allowed opacity-50': qty >= max }"
                    @click="increaseQty"
                    :disabled="qty >= max">
                +
            </button>
        <?php endif; ?>
    </div>
<?php endif; ?>
