<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Product $product */
$product = $block->getProduct();

/** @var ProductStockItem $stockItemViewModel */
$stockItemViewModel = $viewModels->require(ProductStockItem::class);
$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$defaultQty = $block->getProductDefaultQty() * 1;

$step = $stockItemViewModel->getQtyIncrements($product)
    ? $stockItemViewModel->getQtyIncrements($product)
    : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $defaultQty = ceil($defaultQty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string) $maxSalesQty) : 4)
    + (/* add one if decimal for separator */ (int) $stockItemViewModel->isQtyDecimal($product));

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$isPopup = $block->getData('is_popup') ?? false;
$isSmall = $block->getData('is_small') ?? false;
?>
<?php if ($block->shouldRenderQuantity()): ?>
  <div class="contents <?= !$isPopup ? 'max-md:hidden' : '' ?>">
    <button
      type="button"
      class="animate-on-transition button button--outline-secondary icon-button select-none <?= $isSmall ? 'icon-button--size-sm' : 'icon-button--size-md md:icon-button--size-lg' ?>"
      :class="
        {
          'button--disabled': (!isVariantInCart && variantQty === 1) || !<?= $product->isSaleable() ?>
        }
      "
      :aria-label="
        variantQty > 1
        ? '<?= __('Decrease quantity') ?>'
        : '<?= __('Remove from cart') ?>'
      "
      :disabled="(!isVariantInCart && variantQty === 1) || !<?= $product->isSaleable() ?>"
      @click.prevent.stop="decreaseQty()"
    >
      <span class="sr-only">
        <?= __('Decrease quantity for %1', $product->getName()) ?>
      </span>
      <span
        x-show="variantQty < 2"
        x-cloak <?php // Replace this with auto display none if variant qty > 1 ?>
      >
        <?= $hyvaicons->renderHtml('remove'); ?>
      </span>
      <span
        x-show="variantQty > 1"
        x-cloak <?php // Replace this with auto display none if variant qty < 2 ?>
        >
        <?= $hyvaicons->renderHtml('minus'); ?>
      </span>
    </button>

    <label for="quantity" class="sr-only tracking-widest">
      <?= __('Quantity') ?>
    </label>
    <input
      <?php if ($stockItemViewModel->isQtyDecimal($product)): ?>
        type="text"
        pattern="[0-9]+(\.[0-9]{1,<?= /** @noEscape */ $maxSalesQtyLength ?>})?"
        inputmode="decimal"
      <?php else: ?>
        type="number"
        pattern="[0-9]{0,<?= /** @noEscape */ $maxSalesQtyLength ?>}"
        inputmode="numeric"
        <?php if ($minSalesQty): ?>min="<?= /** @noEscape */ $minSalesQty ?>"<?php endif; ?>
        <?php if ($maxSalesQty): ?>max="<?= /** @noEscape */ $maxSalesQty ?>"<?php endif; ?>
        <?php if ($step): ?>step="<?= /** @noEscape */ $step ?>"<?php endif; ?>
      <?php endif; ?>
      name="qty"
      :value="variantQty || <?= $block->getProductDefaultQty() * 1 ?>"
      class="animate-on-transition input__field flex-shrink-0 basis-14 text-center md:h-auto bg-transparent <?= $isSmall ? 'h-9 px-3' : '' ?> <?= $isPopup ? 'max-sm:basis-8 max-sm:px-2' : '' ?>"
      min="1"
      @change.lazy="setQuantity($event.target.value)"
      aria-label="<?= __('Quantity') ?>"
      id="quantity"
      :disabled="!<?= $product->isSaleable() ?>"
      form="product_addtocart_form"
    >

    <button
      type="button"
      class="animate-on-transition button button--outline-secondary icon-button select-none <?= $isSmall ? 'icon-button--size-sm' : 'icon-button--size-md md:icon-button--size-lg' ?>"
      aria-label="<?= __('Increase quantity') ?>"
      @click.prevent.stop="increaseQty()"
      :class="
        {
          'button--disabled': !<?= $product->isSaleable() ?>
        }
      "
      :disabled="!<?= $product->isSaleable() ?>"
    >
      <span class="sr-only">
        <?= __('Increase quantity') ?>
      </span>
      <?= $hyvaicons->renderHtml('plus'); ?>
    </button>
  </div>
<?php endif; ?>
