<?php

use Satoshi\Theme\Block\Template;
/** @var Template $block */

$url = $block->getUrl();
?>

<div x-transition>
    <div class="flex flex-col gap-4 max-md:mb-3">
        <div class="flex items-center justify-between px-2 md:hidden">
            <span class="mb-2 block md:mb-3 max-md:font-semibold"><?= __('Share') ?></span>

        </div>

        <div class="flex gap-2">
            <label for="url_product" class="sr-only tracking-widest"><?= __('Share') ?></label>
            <input
                type="text"
                class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                id="url_product"
                value="<?= $url ?>"
                placeholder="<?= __('Share') ?>"
                onclick="this.select();"
                readonly
            >
        </div>

        <div class="flex gap-3">
            <button
                type="button"
                class="button button--outline button--outline-primary max-md:hidden"
                @click="open = !open"
            >
                <?= __('Close') ?>
            </button>

            <button @click.prevent="navigator.clipboard.writeText('<?= $url ?>'); copied = true;"
                    class="button button--filled button--filled-primary flex-1" type="button">
                <span><?= __('Copy link') ?></span>
            </button>
        </div>
    </div>
</div>
