<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$fieldType = $escaper->escapeHtml($block->getData('type') ?? 'text');
$fieldName = $escaper->escapeHtml($block->getData('name') ?? 'input_name');
$fieldId = $escaper->escapeHtml($block->getData('id') ?? $fieldName);
$fieldLabel = $escaper->escapeHtml($block->getData('label') ?? ucfirst($fieldName));
$fieldValue = $escaper->escapeHtml($block->getData('value') ?? '');
$placeholder = $escaper->escapeHtml($block->getData('placeholder') ?? $fieldLabel);
$isRequired = (bool)($block->getData('required') ?? false);
$autofocus = (bool)($block->getData('autofocus') ?? false);
$additionalClasses = 'input__field input__field--outline h-auto px-5 py-4 ' . $escaper->escapeHtml($block->getData('classes') ?? '');

?>

<label for="<?= $fieldId ?>" class="sr-only tracking-widest">
    <?= $escaper->escapeHtml(__($fieldLabel)) ?>
</label>
<input
    type="<?= $fieldType ?>"
    name="<?= $fieldName ?>"
    id="<?= $fieldId ?>"
    placeholder="<?= $escaper->escapeHtml(__($placeholder)) ?>"
    value="<?= $fieldValue ?>"
    <?= $isRequired ? 'required' : '' ?>
    <?= $autofocus ? 'autofocus' : '' ?>
    class="<?= $additionalClasses ?>"
/>

<label for="last_name" class="sr-only tracking-widest"><?= __('Last Name') ?></label>
<input
    type="text"
    name="lastname"
    placeholder="<?= __('Last Name') ?>"
    value="<?= $block->escapeHtml($block->getLastname()) ?>"
    id="last_name"
    required
    class="input__field input__field--outline h-auto px-5 py-4"
/>
