<?php
declare(strict_types=1);

use Magento\Store\Block\Switcher;
use Satoshi\Theme\Block\Template;

/** @var Switcher $block */
/** @var Template $template */

if (count($block->getStores()) > 1):
    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    $currentStoreId = $block->getCurrentStoreId();
    $currentStoreCode = $block->getCurrentStoreCode();
    $currentLabel = $block->escapeHtml($block->getStoreName());

    $options = array_map(static function ($store) use ($block, $currentStoreId) {
        $isCurrent = $store->getId() === $currentStoreId;
        return [
            'value' => $block->escapeHtml($store->getCode()),
            'label' => $block->escapeHtml($store->getName()),
            'on_click' => $isCurrent ? 'return false;' : 'window.location.href=`' . $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($store)) . '`',
            'is_active' => $isCurrent,
        ];
    }, $block->getStores());
    ?>

    <?= $template->setData([
            'id' => 'store-selector' . $block->escapeHtmlAttr($id),
            'label' => $currentLabel,
            'options' => $options,
            'placement' => 'top',
        ])->render('Magento_Theme::html/components/dropdown.phtml'); ?>

<?php endif; ?>
