<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $template */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;

$name = (string) $block->getName();
$title = (string) $block->getTitle();
$headingTag = $block->getData('heading_tag') ?: 'h3';
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return;
}

$sliderIndex = 1;
$sliderItemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
        ?: $block->getLayout()->createBlock(Template::class);

$hideRatingSummary = (bool) $block->getData('hide_rating_summary');
$hideDetails       = (bool) $block->getData('hide_details');

$sliderItemRenderer->setData('hide_details', $hideDetails);
$sliderItemRenderer->setData('hide_rating_summary', $hideRatingSummary);

// The slider item renderer block is often a shared instance.
// If a specific item template is set for this slider, the previously set template must be reset later
// so the item template is only replaced for the one slider it is specified on.
$sharedItemRendererTemplate = null;
$isSharedItemRenderer = $sliderItemRenderer !== $block->getChildBlock('slider.item.template');
if ($isSharedItemRenderer && $block->getChildBlock('slider.item.template')) {
    $sharedItemRendererTemplate = $sliderItemRenderer->getTemplate();
    $sliderSpecificItemTemplate = $block->getChildBlock('slider.item.template')->getTemplate();
    $sliderItemRenderer->setTemplate($sliderSpecificItemTemplate);
}

?>

<div
    class="slider slider--full-width"
    x-init="
      configureAndStart({
        slidesAmountInView: '{xs: 1, sm: 2, md: 3, lg: 4, xl: 5, xxl: 6}',
        gap: 16,
        isAutoplay: false,
        autoplaySpeed: 0
      })
    "
    x-data="Slider()"
    id="related-products-slider"
    style="
      --slide-gap: 16px;
      --slide-count-xs: 2.2;
      --slide-count-sm: 2.5;
      --slide-count-md: 3;
      --slide-count-lg: 4;
      --slide-count-xl: 5;
      --slide-count-xxl: 5
    "
>
    <div class="slider__header">
        <?php if ($title): ?>
            <h1 class="slider__title">
                <?= $escaper->escapeHtml($title); ?>
            </h1>
        <?php endif; ?>

        <div class="slider__actions">
            <button
                class="button button--outline-primary icon-button icon-button--size-sm rotate-180"
                :class="isPrevBtnDisabled && 'button--disabled'"
                @click.prevent="showPrevSlide()"
                :disabled="isPrevBtnDisabled"
                aria-label="<?=__('Slide right')?>"
                role="button"
            >
                <?= $hyvaicons->renderHtml('chevron'); ?>
            </button>

            <button
                class="button button--outline-primary icon-button icon-button--size-sm"
                @click.prevent="showNextSlide()"
                :class="isNextBtnDisabled && 'button--disabled'"
                :disabled="isNextBtnDisabled"
                aria-label="<?=__('Slide right')?>"
                role="button"
            >
                <?= $hyvaicons->renderHtml('chevron'); ?>
            </button>
        </div>
    </div>
    <div class="slider__slides"
         x-ref="slider"
         @scroll="handleManualScroll"
    >
        <?php foreach ($items as $product): ?>
            <div class="slider__slide"
            >
                <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer(
                    $sliderItemRenderer,
                    $product,
                    $block,
                    $viewMode,
                    ProductReviewRenderer::SHORT_VIEW,
                    $imageDisplayArea,
                    $showDescription
                ) ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
