<?php

declare(strict_types=1);

use Hyva\Theme\Model\LocaleFormatter;
use Magento\Catalog\Helper\Data;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation\FilterRenderer;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var SvgIcons $hyvaicons */
/** @var FilterRenderer $block */
/** @var Escaper $escaper */
/** @var LocaleFormatter $localeFormatter */
/** @var array $filterItems */
/** @var string $attribute_code */

$hyvaicons = $viewModels->require(SvgIcons::class);
$catalogHelper = $this->helper(Data::class);


$filters = $block->getParentBlock('catalog.leftnav')->getFilters() ?? [];
$availableFilters = array_filter($filters, function ($filter) {
    return $filter->getItemsCount();
});

?>
<div>
    <!-- Filters popup header on mobile -->
    <div class="sticky start-0 top-0 z-10 flex flex-col gap-3 bg-bg-500 px-2 md:pt-2 md:hidden">
        <div class="flex justify-between">
            <div
                class="relative flex gap-3 items-center"
                :class="{
                    '-translate-x-[34px]': isTopLevel,
                    'translate-x-0': !isTopLevel,
                }"
            >
                <button
                    type="button"
                    class="button button--ghost-primary icon-button icon-button--size-xs text-xxl transition-transform duration-300 motion-reduce:transition-none"
                    aria-label="<?= __('Go back to all filters') ?>"
                    @click="isTopLevel = true; currentName = ''"
                    :tabindex="isTopLevel ? -1 : 0"
                >
                    <?= $hyvaicons->renderHtml('chevron-left'); ?>
                </button>
                <h2
                    class="text-md text-text-500 transition-transform duration-300 motion-reduce:transition-none"
                    x-text="isTopLevel ? '<?= $escaper->escapeHtmlAttr(__('Filters')) ?>' : currentName"
                >
                </h2>
            </div>
            <button
                type="button"
                class="button button--outline-secondary icon-button icon-button--size-xs"
                aria-label="<?= __('Close') ?>"
                @click="$store.popup.hidePopup('<?= $attribute_code ?>')"
            >
                <?= $hyvaicons->renderHtml('close'); ?>
            </button>
        </div>
        <hr class="divider -mx-3">
    </div>

    <!-- Filter options -->
    <article
        class="relative px-2"
        :aria-label="isTopLevel ? 'All filters' : 'Filter by ' + currentName?.toLowerCase()"
    >
        <nav class="flex flex-col gap-3 py-3 md:hidden" x-show="isTopLevel" aria-label="<?= $escaper->escapeHtmlAttr(__('Available filters')) ?>">
            <?php foreach($availableFilters as $availableFilter): ?>
                <button
                    type="button"
                    class="flex min-h-10 items-center justify-between py-1"
                    @click="isTopLevel = false; currentName = '<?= $availableFilter->getName() ?>'"
                >
                    <span
                        class="mr-4 <?= $availableFilter['attribute_model']['attribute_code'] !== $attribute_code ? 'hidden' : '' ?>"
                    >
                        <?= $hyvaicons->renderHtml('dot'); ?>
                    </span>
                    <p
                        class="grow text-left <?= $availableFilter['attribute_model']['attribute_code'] === $attribute_code ? 'text-primary-500 font-semibold' : '' ?>"
                    >
                        <?= $availableFilter->getName() ?>
                    </p>
                    <p class="icon-button">
                        <?= $hyvaicons->renderHtml('chevron'); ?>
                    </p>
                </button>
            <?php endforeach; ?>
        </nav>

        <div
            class="flex flex-col gap-4 pt-3 md:pb-5 md:pt-4"
            :class="{
                'max-md:hidden': isTopLevel
            }"
        >
            <div role="radiogroup" aria-label="<?= $escaper->escapeHtmlAttr(__('%1 filter options', $block->getFilterTitle())) ?>">
                <?php foreach ($filterItems as $filterItem): ?>
                    <div class="relative h-11 w-full">
                        <?php if ($filterItem->getCount() > 0): ?>
                            <label class="radio mb-0 h-full w-full py-1 justify-between" for="filter-<?= $escaper->escapeHtmlAttr($filterItem->getValueString()) ?>">
                                <div class="flex items-center">
                                    <input
                                        type="radio"
                                        class="radio__input"
                                        id="filter-<?= $escaper->escapeHtmlAttr($filterItem->getValueString()) ?>"
                                        name="<?= $attribute_code ?>"
                                        value="<?= $escaper->escapeHtmlAttr($filterItem->getValueString()) ?>"
                                        aria-label="<?= $escaper->escapeHtmlAttr($filterItem->getLabel()) ?>"
                                        @change="updateSelectedFilters('<?= $escaper->escapeUrl($filterItem->getUrl()) ?>')"
                                    >
                                    <span class="radio__control " aria-hidden="true"></span>
                                    <span class="radio__label"><?= $filterItem->getLabel() ?></span>
                                </div>
                                <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()): ?>
                                    <span class="count text-primary">(<?= $localeFormatter->formatNumber((int)$filterItem->getCount()) ?>)</span>
                                <?php endif; ?>
                            </label>
                            <?php else: ?>
                            <span><?= $filterItem->getLabel() ?> </span>

                            <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()): ?>
                                <span class="count text-primary">(<?= $localeFormatter->formatNumber((int)$filterItem->getCount()) ?>)</span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </article>

    <!-- Filters popup footer on mobile -->
    <div class="md:hidden mb-3">
        <div class="-top-10 end-0 start-0 h-10 bg-gradient-to-t from-bg-500 to-transparent"></div>
        <div class="flex items-center gap-3 bg-bg-500 px-2 pb-2">
            <button
                type="button"
                class="button button--outline-secondary"
                @click="$store.popup.hidePopup('<?= $attribute_code ?>')"
            >
                <?= __('Reset') ?>
            </button>

            <button
                type="button"
                class="button button--filled-primary grow"
                @click="() => {
                    _fetchPage(selectedFiltersUrl);
                    $store.popup.hidePopup('<?= $attribute_code ?>');
                    window.scrollTo({
                        top: 0,
                        behavior: 'smooth'
                    });
                }"
            >
                <?= __('Apply') ?>
            </button>
        </div>
    </div>
</div>
