<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation\State;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var State $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class); ?>


<?php $filters = $block->getActiveFilters() ?>
<div class="overflow-x-scroll overscroll-x-contain">
    <div>
        <div>
            <div class="mb-5 hidden items-center justify-between md:flex">
                <h2 class="text-text-500"><?= __('Selected filters') ?></h2>
                <button
                    x-show="<?= !empty($filters) ? 'true' : 'false' ?> || <?= $block->getLayer()->getState()->getFilters() ? 'true' : 'false' ?> || !getIsFilterValueSelected('product_list_order', defaultSort) || !getIsFilterValueSelected('product_list_dir', 'asc')"
                    class="link link--primary"
                    @click="() => {
                        _fetchPage('<?= $escaper->escapeUrl($block->getClearUrl()) ?>');
                        setSortDir('asc');
                        resetCurrent('filter-sort-by');
                    }"
                >
                    <?= $escaper->escapeHtml(__('Reset All')) ?>
                </button>
            </div>
            <?php if (empty($filters)): ?>
                <div class="hidden md:block">
                    <p class="pr-3 text-center md:pr-0 md:text-left">
                        <?= __('The selected filters will appear here.') ?>
                    </p>
                </div>
            <?php endif; ?>
            <div
                x-show="<?= !empty($filters) ? 'true' : 'false' ?> || !getIsFilterValueSelected('product_list_order', defaultSort) || !getIsFilterValueSelected('product_list_dir', 'asc')"
                class="flex flex-row md:flex-col gap-3 md:pb-7 md:pt-2">
                <button
                    type="button"
                    aria-label="<?= __('Clear all') ?>"
                    class="md:hidden button min-w-[44px] px-0 text-xl button--filled-primary opacity-100"
                    :tabindex="getIsDefault() ? -1 : 0"
                    @click="() => {
                        _fetchPage('<?= $escaper->escapeUrl($block->getClearUrl()) ?>');
                        setSortDir('asc');
                        resetCurrent('filter-sort-by');
                    }"
                >
                    <span><?= $hyvaicons->renderHtml('remove'); ?></span>
                </button>
                <div
                    x-show="!getIsFilterValueSelected('product_list_order', defaultSort) || !getIsFilterValueSelected('product_list_dir', 'asc')">
                    <button
                        type="button"
                        :class="$store.main.isMobile ? 'button duration-300 button--outline-primary' : 'button button--outline-secondary button--size-sm mr-3 shrink-0 md:mr-0'"
                        @click="setSortDir('asc'); resetCurrent('filter-sort-by')"
                    >
                            <span x-text="() => {
                                selectedPos = getSelectedSortOption();
                                return selectedPos.name;
                            }" class="mr-2">

                            </span>
                        <span class="ml-3 text-lg">
                                <?= $hyvaicons->renderHtml('close'); ?>
                            </span>
                    </button>
                </div>
                <?php foreach ($filters as $filter): ?>
                    <div>
                        <button
                            type="button"
                            :class="$store.main.isMobile ? 'button duration-300 button--outline-primary' : 'button button--outline-secondary button--size-sm mr-3 shrink-0 md:mr-0'"
                            @click="_fetchPage('<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>')"
                        >
                            <span class="mr-2">
                                <?= $escaper->escapeHtml(__($filter->getName())) ?>:
                            </span>
                            <span>
                                <?= $escaper->escapeHtml($block->stripTags($filter->getLabel())) ?>
                            </span>
                            <span class="ml-3 text-lg">
                                <?= $hyvaicons->renderHtml('close'); ?>
                            </span>
                        </button>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
