<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Layer\Filter\Item;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;
use Hyva\Theme\ViewModel\SvgIcons;
use Satoshi\Theme\Block\Popup;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Popup $popup */
/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */


/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$filters = $block->getFilters();

$filteredFilters = array_filter($filters, function ($filter) {
    return $filter->getItemsCount();
});

$sortVariable = $block->getSortVariable();

$productCollection = $block->getLayer()->getProductCollection();

?>
<div x-data="Filters()">
    <?php if ($productCollection->getSize() > 0): ?>
        <template x-portal="document.getElementById('toolbar-filters')">
            <nav
                class="overflow-x-scroll pb-4 pt-2 md:hidden" aria-label="<?= __('Available filters') ?>">
                <div
                    class="flex w-max gap-3 transition-transform duration-300"
                >
                    <?= $block->getChildHtml('state') ?>
                    <button
                        @click="$store.popup.showPopup('sort-popup')"
                        type="button"
                        aria-label="<?= __('Clear all') ?>"
                        class="button duration-300 button--outline-secondary"
                    >
                        <?= __('Sort by') ?>
                    </button>
                    <?=
                    $popup
                        ->setData([
                            'id' => 'sort-popup',
                            'isFocused' => true,
                            'isFullScreen' => false,
                            'desktopTarget' => 'menu-desktop',
                        ])
                        ->setChildHtml($block->getChildHtml('sort'))
                        ->render()
                    ?>
                    <?php foreach ($filteredFilters as $filter): ?>
                        <button
                            @click="$store.popup.showPopup('<?= $filter->getName() ?>')"
                            type="button"
                            aria-label="<?= __('Clear all') ?>"
                            class="button duration-300 button--outline-secondary"
                        >
                            <?= $filter->getName() ?>
                        </button>
                        <?=
                        $popup
                            ->setData([
                                'id' => $filter->getName(),
                                'isFocused' => true,
                                'isFullScreen' => false,
                                'desktopTarget' => 'menu-desktop',
                            ])
                            ->setChildHtml($block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter))
                            ->render()
                        ?>
                    <?php endforeach; ?>
                </div>
            </nav>
        </template>
        <div
            role="region"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
            class="overflow-hidden w-[275px] hidden md:block"
        >
            <div class="w-[275px] min-w-[275px] translate-x-0 transition-transform motion-reduce:transition-none"
                 :class="$store.productList.isFiltersSidebarExpanded ? 'translate-x-0' : 'translate-x-full'"
            >
                <div
                    id="filters-content"
                    class="block-content filter-content hidden md:block pt-4"
                >
                    <?= $block->getChildHtml('state') ?>

                    <?= $block->getChildHtml('sort') ?>

                    <?php foreach ($filteredFilters as $filter): ?>
                        <div
                            class="flex-1 md:border-t md:border-bg-600 md:py-5"
                            x-data="Accordion(true, 300)"
                        >
                            <div
                                class="group hidden h-11 w-full cursor-pointer items-center rounded-md py-3 md:flex md:px-2"
                                x-ref="AccordionButton"
                            >
                                <h2 class="grow text-left text-text-500">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('filter')) ?>
                                    </span>
                                </h2>
                                <button
                                    class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable"
                                    aria-label="<?= __('Sort by') ?>">
                                        <span style="rotate: -180deg;" x-ref="AccordionIcon">
                                            <?= $hyvaicons->renderHtml('chevron-up'); ?>
                                        </span>
                                </button>
                            </div>
                            <div
                                x-cloak x-ref="AccordionPanel" class="overflow-hidden md:px-2"
                                :class="{
                                    'transition-none': $store.main.isReducedMotion,
                                    'transition': $store.main.isReducedMotion
                                }"
                            >
                                <?= /* @noEscape */
                                $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
