<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<?php if ($block->canShowBlock()): ?>
    <!-- Show / Hide filters button -->
    <div class="absolute right-0 top-[-68px] ml-8 md:pl-2 max-md:hidden">
        <button
            type="button"
            class="button button--filled-primary w-[275px] min-w-[275px]"
            @click="$store.productList.toggleFiltersSidebar()"
        >
            <span
                x-text="$store.productList.isFiltersSidebarExpanded ? '<?= __('Hide filter') ?>' : '<?= __('Show filter') ?>'"
            >
                <?= __('Hide filter') ?>
            </span>
            <span class="button__icon ml-3 text-xl">
                <?= $hyvaicons->renderHtml('filter'); ?>
            </span>
        </button>
    </div>


    <!-- Desktop filters -->
    <div
        class="hidden w-[275px] min-w-[275px] overflow-hidden transition-[width,min-width] motion-reduce:transition-none md:sticky md:top-[--scroll-top] md:block"
        :class="{
            'w-[275px] min-w-[275px]': $store.productList.isFiltersSidebarExpanded,
            'w-0 min-w-0 ml-0': !$store.productList.isFiltersSidebarExpanded
        }"
        x-sticky-scroll="{
            top: 90,
            bottom: 24,
        }"
    >
        <div
            id="filters-sidebar"
            class="w-[275px] min-w-[275px] translate-x-0 transition-transform motion-reduce:transition-none"
            :class="{
                'translate-x-full': !$store.productList.isFiltersSidebarExpanded,
                'translate-x-0': $store.productList.isFiltersSidebarExpanded
            }"
            :inert="!$store.productList.isFiltersSidebarExpanded"
        >
            <template x-portal="document.getElementById($store.main.isMobile ? 'selected-filters-mobile' : 'filters-sidebar')">
                <div
                    x-data="Filters()"
                    role="region"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
                >
                    <?= $block->getChildHtml('state') ?>
                    <?php foreach ($block->getFilters() as $filter): ?>
                        <?php if ($filter->getItemsCount()): ?>

                            <!-- Desktop filters -->
                            <fieldset class="flex-1 md:border-t md:border-bg-600 md:py-5 max-md:hidden" x-data="Accordion(true, 300)">
                                <div class="group hidden h-11 w-full cursor-pointer items-center rounded-md py-3 md:flex md:px-2" x-ref="AccordionButton">
                                    <h2 class="grow text-left text-text-500"><?= $escaper->escapeHtml(__($filter->getName())) ?></h2>
                                    <button class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable" type="button" aria-label="<?= $escaper->escapeHtml(__($filter->getName())) ?>">
                                        <span x-ref="AccordionIcon">
                                            <?= $hyvaicons->renderHtml('chevron', '-rotate-90'); ?>
                                        </span>
                                    </button>
                                </div>

                                <div
                                    class="overflow-hidden md:px-2"
                                    x-ref="AccordionPanel"
                                    :class="{
                                        'transition-none': $store.main.isReducedMotion,
                                        'transition': $store.main.isReducedMotion
                                    }"
                                >
                                    <div class="md:pb-3 md:pt-2">
                                        <div class="flex flex-col gap-4 py-3">
                                            <?= /* @noEscape */ $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </template>
        </div>
    </div>
    <?php // Needed to offset bottom filters at the bottom ?>
    <div class="h-[60px] md:hidden"></div>

    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
                }
            }
        }
    </script>
<?php endif; ?>
