<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;
use Hyva\Theme\ViewModel\SvgIcons;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php if ($block->canShowBlock()): ?>
    <div
        x-data="initLayeredNavigation()"
        x-init="checkIsMobileResolution()"
        @resize.window.debounce="checkIsMobileResolution()"
        @visibilitychange.window.debounce="checkIsMobileResolution()"
        role="region"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
        class="overflow-hidden w-[275px]"
    >
        <div class="w-[275px] min-w-[275px] translate-x-0 transition-transform motion-reduce:transition-none"
             :class="$store.productList.isFiltersSidebarExpanded ? 'translate-x-0' : 'translate-x-full'"
        >
            <h2
                id="filters-heading"
                class="block-title"
            >
                <button
                    type="button"
                    @click="blockOpen = !blockOpen"
                    class="block-title flex items-center justify-between w-full text-start"
                    aria-controls="filters-content"
                    :aria-expanded="blockOpen"
                    :aria-disabled="!isMobile"
                    :disabled="!isMobile ? '' : null"
                >
                <span class="text-primary text-md md:text-3xl font-medium uppercase">
                    <?= $escaper->escapeHtml(__('Shop By')) ?>
                </span>
                    <span
                        class="py-1 px-1 bg-container-lighter rounded border border-container-darker md:hidden"
                        x-ref="LayeredNavigationMobileToggleIcon"
                    >
                    <?= $heroicons->chevronDownHtml(
                        'transition-transform transform duration-300 ease-in-out',
                        24,
                        24,
                        [
                            ":class" => "{ 'rotate-180': blockOpen }",
                            "aria-hidden" => "true",
                            "focusable" => "false"
                        ]
                    ); ?>
                </span>
                </button>
            </h2>
            <div
                id="filters-content"
                class="block-content filter-content hidden md:block pt-4"
                :class="{ 'hidden': !blockOpen }"
            >
                <?= $block->getChildHtml('state') ?>
                <a
                    href="#product-list"
                    class="sr-only focus:not-sr-only bg-blue-600 text-white px-12 py-4 text-center block rounded-sm"
                >
                    <?= $escaper->escapeHtml(__('Skip to product list')) ?>
                </a>
                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <div
                            class="flex-1 md:border-t md:border-bg-600 md:py-5"
                            x-data="Accordion(true, 300)"
                        >
                            <div
                                class="group hidden h-11 w-full cursor-pointer items-center rounded-md py-3 md:flex md:px-2"
                                x-ref="AccordionButton"
                            >
                                <h2 class="grow text-left text-text-500">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('filter')) ?>
                                    </span>
                                </h2>
                                <button
                                    class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable"
                                    aria-label="<?=__('Sort by')?>">
                                        <span style="rotate: -180deg;" x-ref="AccordionIcon">
                                            <?= $hyvaicons->renderHtml('chevron-up'); ?>
                                        </span>
                                </button>
                            </div>
                            <div
                                x-cloak x-ref="AccordionPanel" class="overflow-hidden md:px-2"
                                :class="{
                                    'transition-none': $store.main.isReducedMotion,
                                    'transition': $store.main.isReducedMotion
                                }"
                                :id="`${id}-content`"
                            >
                                <?= /* @noEscape */
                                $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
                }
            }
        }
    </script>
<?php endif; ?>
