<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LogoSizeResolver $logoSizeResolver */

$storeName = $block->getThemeName() ?? 'Satoshi theme';

$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();

$logoSrc = $block->getLogoSrc();

$logoOriginalWidth = $block->getOriginalLogoWidth();
$logoOriginalHeight = $block->getOriginalLogoHeight();

$text_length = strlen($storeName);
$estimated_width = $text_length * 12;

$logoWidth = $logoWidth ?? 100;
$logoHeight = $logoHeight ?? 150;
$logoRatio = 0;
if ($logoOriginalWidth) {
    $logoRatio = $logoOriginalWidth / $logoWidth;
}
?>


<?php if ($logoSrc): ?>
    <img
        src="<?= $escaper->escapeUrl($logoSrc) ?>"
        alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt() ? $block->getLogoAlt() : __('Store logo')) ?>"
        width="<?= $escaper->escapeHtmlAttr($logoWidth) ?>"
        height="<?= $escaper->escapeHtmlAttr($logoHeight) ?>"
        style="filter:url(#border); --max-logo-width: <?= $logoWidth ?>px"
        <?php if ($logoRatio && ($logoOriginalHeight / $logoRatio) > 56): ?>
            :style="{
                '--logo-height': $store.main.isHeaderShadowVisible ? '56px' : '<?= $escaper->escapeHtmlAttr($logoOriginalHeight / $logoRatio) ?>px',
            }"
        <?php endif ?>
        class="w-auto max-md:height-[56px] transition-all md:max-w-full <?php if ($logoRatio && ($logoOriginalHeight / $logoRatio) > 56): ?>md:h-[--logo-height]<?php endif ?>"
    />
<?php else: ?>
    <svg
        viewBox="0 0 <?= $estimated_width ?> 25"
        class="m-auto h-[40px] w-2/3"
    >
        <text
            text-anchor="middle"
            x="50%"
            y="20"
            filter="url(#border)"
        >
            <?= $escaper->escapeHtml($storeName) ?>
        </text>
    </svg>
<?php endif; ?>
