<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LogoSizeResolver $logoSizeResolver */

$storeName = $block->getThemeName() ?? 'Satoshi theme';

$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();

/** @var \Hyva\Theme\ViewModel\Logo\LogoPathResolver $logoPathResolver */
$logoPathResolver = $block->getData('logoPathResolver');
$logoSrc = $logoPathResolver && method_exists($logoPathResolver, 'getLogoSrc')
    ? $logoPathResolver->getLogoSrc($block->getData('logo_file'))
    : $block->getLogoSrc();

$text_length = strlen($storeName);
$estimated_width = $text_length * 12;

$logoWidth = $logoWidth ?? 100;
$logoHeight = $logoHeight ?? 150;

?>

<?php if ($logoSrc): ?>
<img
  src="<?= $escaper->escapeUrl($logoSrc) ?>"
  alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt() ? $block->getLogoAlt() : __('Store logo')) ?>"
  width="<?= $escaper->escapeHtmlAttr($logoWidth) ?>"
  height="<?= $escaper->escapeHtmlAttr($logoHeight) ?>"
  class="max-md:height-[56px] transition-all"
  style="filter:url(#border);
  <?php if($logoHeight > 56): ?>
  :style="{
    'height': $store.main.isHeaderShadowVisible ? '56px' : '<?= $escaper->escapeHtmlAttr($logoHeight) ?>px'
  }"
  <?php endif; ?>
/>
<?php else: ?>
<svg
  viewBox="0 0 <?= $estimated_width ?> 25"
  class="m-auto h-[40px] w-2/3"
>
  <text
    text-anchor="middle"
    x="50%"
    y="20"
    filter="url(#border)"
  ><?= $escaper->escapeHtml($storeName)?></text>
</svg>
<?php endif; ?>
