<?php
declare(strict_types=1);

/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<div class="price__element flex items-center gap-2 text-text-500">
    <?php if ($block->hasSpecialPrice()) :?>
        <span class="sr-only"><?= __('Sale Price') ?></span>
        <span>
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
        <s class="old-price">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </s>
    <?php else :?>
        <span class="sr-only"><?= __('Regular Price') ?></span>
        <span>
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()) :?>
        <?php if ($block->getUseLinkForAsLowAs()) :?>
            <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </a>
        <?php else :?>
            <span class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </span>
        <?php endif?>
    <?php endif; ?>
</div>
