<?php

use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

// TODO: Make dynamic
$isAlpineTemplate = false;

$pageType = $this->getRequest()->getFullActionName();
$mobilePageTypes = ['catalog_category_view', 'catalog_product_view', 'catalogsearch_result_index'];
$hideOnMobile = in_array($pageType, $mobilePageTypes);
?>

<?php if (!empty($crumbs) && is_array($crumbs)): ?>
    <nav
        class="breadcrumbs content-wrapper mx-auto my-8 px-4 <?= $hideOnMobile ? 'hidden' : '' ?> md:block"
        role="navigation"
        aria-label="<?= __('Breadcrumbs') ?>"
    >
        <div role="list" class="truncate px-2">
            <?php if ($isAlpineTemplate): ?>
                <div role="listitem" class="inline font-bold">
                    <a class="inline-flex hover:underline" x-element-transition-trigger href="<?= $escaper->escapeUrl($block->getUrl('/')) ?>">
                        <?= __('Home') ?>
                    </a>
                </div>

                <div role="listitem" class="mx-4 inline-block" aria-hidden="true">
                    <?= $hyvaicons->renderHtml('breadcrumb-chevron'); ?>
                </div>

                <template x-if="$store['transition'].pageType === 'category'">
                    <div class="contents">
                        <div role="listitem" class="breadcrumb text-text-500" x-text="$store['transition'].pageData?.title"></div>
                    </div>
                </template>

                <template x-if="$store['transition'].pageType === 'product'">
                    <div class="contents">
                        <div role="listitem" class="breadcrumb text-text-500" x-text="$store['transition'].pageData?.title"></div>
                    </div>
                </template>

                <template x-if="$store['transition'].pageType === 'search'">
                    <div class="contents">
                        <div
                            x-data="{
                                searchTerm: $store['transition'].pageData?.search,
                                resultCount: $store['transition'].pageData?.resultCount,
                                text: '<?= __('%1 result found for "%2"') ?>',
                            }"
                            role="listitem"
                            class="breadcrumb text-text-500"
                            x-text="hyva.strf(text, resultCount, searchTerm)"
                        ></div>
                    </div>
                </template>
            <?php else: ?>
                <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                    <?php if (!empty($crumbInfo['link'])): ?>
                        <div role="listitem" class="breadcrumb" data-crumb-name="<?= $escaper->escapeHtmlAttr($crumbName) ?>">
                            <a x-element-transition-trigger class="inline-flex hover:underline" href="<?= $escaper->escapeUrl($crumbInfo['link']) ?>" aria-current="page">
                                <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        </div>
                        <div role="listitem" class="mx-4 inline-block" aria-hidden="true">
                            <?= $hyvaicons->renderHtml('breadcrumb-chevron'); ?>
                        </div>
                    <?php elseif (!empty($crumbInfo['last'])): ?>
                        <div role="listitem" class="breadcrumb text-text-500">
                            <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </nav>
<?php endif; ?>
