<?php

use Hyva\Theme\ViewModel\SvgIcons;

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

// TODO: Make dynamic
$isAlpineTemplate = false;
$condition = false;
$isNoMobile = false;
$template = [];
$t = 'page';
if (in_array($template, ['index', 'cart', 'list-collections', '404', 'customers/account', 'customers/addresses', 'customers/order', 'gift_card'])) {
    $condition = true;
}
if (in_array($template, ['collection', 'product', 'search'])) {
    $isNoMobile = true;
}
?>

<?php if ($crumbs && is_array($crumbs) && !$condition): ?>
    <nav
        class="breadcrumbs content-wrapper mx-auto my-8 px-4 <?php if ($isNoMobile): ?>hidden<?php endif; ?>"
        role="navigation"
        aria-label="<?= __('general.breadcrumbs.aria_label') ?>"
    >
        <div role="list" class="truncate">
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <div role="listitem" class="breadcrumb <?= $block->escapeHtmlAttr($crumbName) ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <div role="listitem" class="inline font-bold text-neutral-500 contrast-more:text-secondary-700">
                            <a x-element-transition-trigger href="">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        </div>
                        <div
                            role="listitem"
                            class="mx-4 inline-block text-neutral-500 contrast-more:text-secondary-700"
                            aria-hidden="true"
                        >
                            <?= $hyvaicons->renderHtml('breadcrumb-chevron'); ?>
                        </div>

                        <!-- TODO: Many non existent variables must be implemented -->
                    <?php elseif ($crumbInfo['last']) : ?>
                        <?php if ($isAlpineTemplate): ?>
                            <?php if ($pageType === 'category'): ?>
                                <div class="contents">
                                    <div role="listitem" class="breadcrumb">

                                    </div>
                                </div>
                            <?php endif; ?>

                            <?php if ($pageType === 'article'): ?>
                                <div class="contents">
                                    <div role="listitem" class="breadcrumb">
                                        <a x-element-transition-trigger href=""
                                           aria-current="page">
                                        </a>
                                    </div>
                                    <div role="listitem"
                                         class="mx-4 inline-block text-neutral-500 contrast-more:text-secondary-700"
                                         aria-hidden="true">
                                        <?= $hyvaicons->renderHtml('breadcrumb-chevron'); ?>
                                    </div>
                                    <div role="listitem" class="breadcrumb">
                                        <?= htmlspecialchars($pageData['title'] ?? '', ENT_QUOTES, 'UTF-8') ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <?php if ($pageType === 'product'): ?>
                                <div class="contents">
                                    <div role="listitem" class="breadcrumb">
                                        <?= htmlspecialchars($pageData['title'] ?? '', ENT_QUOTES, 'UTF-8') ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <?php if ($pageType === 'search'): ?>
                                <div class="contents">
                                    <div role="listitem" class="breadcrumb">>
                                    </div>
                                </div>
                            <?php endif; ?>

                        <?php else: ?>
                            <div role="listitem" class="breadcrumb">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </nav>
<?php endif; ?>

