<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$id = $escaper->escapeHtml($block->getData('id') ?? 'dropdown');
$label = $block->getData('label') ?? '';
$options = $block->getData('options') ?? [];
$withSearch = $block->getData('withSearch') ?? false;
$placement = $block->getData('placement') ?? 'bottom';

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div x-data="Dropdown()" x-ref="DropdownWrapper" class="relative">
    <button
        @click="toggleDropdown(); $nextTick(() => { const searchRef = $refs['<?= $id ?>-search']; if (searchRef) { setTimeout(() => { searchRef.focus(); }, 250); } });"
        id="<?= $id ?>-button"
        data-dropdown-toggle="<?= $id ?>"
        data-dropdown-placement="<?= $placement ?>"
        class="inline-flex items-center justify-between gap-6 whitespace-nowrap rounded-sm border bg-white px-6 py-3"
        type="button"
        :aria-expanded="isDropdownVisible"
        aria-controls="<?= $id ?>"
    >
        <?= $escaper->escapeHtml(__($label)) ?>
        <span
            :class="isDropdownVisible ? '-rotate-90' : 'rotate-90'"
            class="transition-transform motion-reduce:transition-none">
            <?= $hyvaicons->renderHtml('chevron'); ?>
        </span>
    </button>
    <div
        id="<?= $id ?>"
        x-cloak
        x-a11y-trap="isDropdownVisible"
        x-show="isDropdownVisible"
        class="absolute z-10 hidden min-w-full rounded-sm border border-gray-300 bg-white p-2 pt-3
            <?= $placement === 'top' ? 'bottom-full' : '' ?>
            <?= $placement === 'bottom' ? 'top-full' : '' ?>
            <?= $placement === 'right' ? 'left-full' : '' ?>
            <?= $placement === 'left' ? 'right-full' : '' ?>"
        :class="{ 'block': isDropdownVisible, 'hidden': !isDropdownVisible }"
    >
        <?php if ($withSearch): ?>
            <div class="p-2">
                <label for="<?= $id ?>-search" class="sr-only">
                    <?= __('Search') ?>
                </label>
                <input type="text" id="<?= $id ?>-search"
                       class="w-full rounded-xs border p-3 placeholder:text-gray-500 contrast-more:border-secondary-700"
                       x-ref="<?= $id ?>-search"
                       placeholder="<?= __('Search') ?>" @input.debounce.300ms="search($event.target.value)">
            </div>
        <?php endif; ?>
        <ul class="max-h-48 overflow-y-auto p-2 text-sm text-gray-700"
            aria-labelledby="<?= $id ?>-button">
            <?php foreach ($options as $option): ?>
                <li>
                    <a tabindex="0"
                       data-value="<?= $escaper->escapeHtml($option['value']) ?>"
                       class="flex cursor-pointer justify-between p-3 gap-x-6 text-nowrap rounded-xs hover:underline<?= $option['is_active'] ? ' bg-primary-50' : '' ?>"
                       @click.prevent='<?= $option['on_click'] ?>'>
                        <?= $option['label'] ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
