<?php

declare(strict_types=1);

use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Html\Footer;

/** @var Footer $block */
/** @var Escaper $escaper */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<template x-portal="document.getElementById('footer-portal')">
  <div class="contents">
    <footer
      class="footer rounded-t-2xl md:bg-secondary-400"
      x-cloak
      :class="{ 'hidden': $store.main.isMobile && '<?= $block->getIsHomePage() ?>' !== '1' }"
    >
      <div class="content-wrapper mx-auto flex w-full flex-col items-stretch gap-5 pb-5 md:gap-8 md:py-8">
        <hr class="divider md:hidden">
        <div class="flex w-full flex-col gap-5 md:flex-row md:gap-12">
          <?= $block->getBlockHtml('form.subscribe') ?>
          <nav class="pb-5 md:flex md:w-full md:justify-between md:gap-5" aria-label="<?= $escaper->escapeHtmlAttr(__('Additional menu')) ?>">
            <?php foreach($block->getFooterCmsBlockIds() as $index=>$cmsBlockId): ?>
              <?php if ($block->getIsCmsBlockAvailable($cmsBlockId)): ?>
                <div
                  x-data="Accordion(!$store.main.isMobile, 300, true)"
                >
                    <!--                  <button-->
                    <!--                    class="group flex h-11 w-full items-center rounded-md p-3 md:h-auto md:cursor-text md:px-[3px] md:py-0 md:hover:bg-inherit"-->
                    <!--                    x-ref="AccordionButton"-->
                    <!--                    :disabled="!$store.main.isMobile"-->
                    <!--                    :aria-expanded="isExpanded && $store.main.isMobile"-->
                    <!--                    aria-controls="-->
                    <?php //= $escaper->escapeHtmlAttr('footer_column_' . $index+1 . '_panel') ?><!--"-->
                    <!--                    aria-labelledby="-->
                    <?php //= $escaper->escapeHtmlAttr('footer_column_' . $index+1 . '_label') ?><!--"-->
                    <!--                    type="button"-->
                    <!--                  >-->
                    <!--                    <h2-->
                    <!--                      class="grow text-left text-text-500"-->
                    <!--                      id="-->
                    <?php //= $escaper->escapeHtmlAttr('footer_column_' . $index+1 . '_label') ?><!--"-->
                    <!--                    >-->
                    <!--                      --><?php //= $escaper->escapeHtml($block->getCmsBlockTitle($cmsBlockId)) ?>
                    <!--                    </h2>-->
                    <!--                    <div class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable md:hidden">-->
                    <!--                      <span x-ref="AccordionIcon">-->
                    <!--                        --><?php //= $hyvaicons->renderHtml('chevron-up', 'rotate-180'); ?>
                    <!--                      </span>-->
                    <!--                    </div>-->
                    <!--                  </button>-->
                  <div
                    x-cloak
                    x-ref="AccordionPanel"
                    class="overflow-hidden"
                    :class="{
                      'transition-none': $store.main.isReducedMotion,
                      'transition': $store.main.isReducedMotion,
                    }"
                    id="<?= $escaper->escapeHtmlAttr('footer_column_' . $index+1 . '_panel') ?>"
                    role="region"
                    aria-labelledby="<?= $escaper->escapeHtmlAttr('footer_column_' . $index+1 . '_label') ?>"
                  >
                    <div class="px-3 pb-5 pt-2 md:p-[3px]">
                      <?= $block->getBlockHtml('footer-cms-content-' . $index+1) ?>
                    </div>
                  </div>
                </div>
              <?php endif; ?>
            <?php endforeach; ?>
          </nav>
        </div>
        <div class="flex w-full flex-col items-center gap-5 md:flex-row-reverse md:justify-between md:gap-7">
          <div class="flex flex-wrap justify-center gap-5 text-center md:order-1">
            <?= $block->getBlockHtml('store-switcher') ?>
            <?= $block->getBlockHtml('store-language-switcher') ?>
            <?= $block->getBlockHtml('currency-switcher') ?>
          </div>
          <?= $block->getChildHtml('copyright') ?>
        </div>
      </div>
    </footer>
  </div>
</template>
