<?php

declare(strict_types=1);

use Magento\Theme\Block\Html\Pager;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Pager $block */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);
$lastPage = $block->getLastPageNum();
$currentPage = $block->getCurrentPage();

?>

<?php if ($lastPage > 1 && $currentPage < $lastPage): ?>
    <div class="my-7 flex flex-col items-center">
        <a
            href="#"
            x-pagination-trigger="{ 'lastPage': <?= $lastPage ?> }"
            class="button btn--size-md button--ghost-primary w-full cursor-pointer text-center md:w-auto"
        >
            <?= __('Load more products') ?>
            <span class="button__icon button__icon--right top-[1px] text-lg rotate-90">
            <?= $hyvaicons->renderHtml('chevron'); ?>
        </span>
        </a>
    </div>
<?php endif ?>
