<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Review\Block\Product\View as ProductReview;
use Magento\Theme\Block\Html\Pager;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ProductReview $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var Pager $toolbar */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);


$reviewCollection = $block->getReviewsCollection();

// Note: Setting the collection on the toolbar block applies pagination, so it has to happen before collection loading.
if ($toolbar = $block->getChildBlock('review_list.toolbar')) {
    $toolbar->setCollection($reviewCollection);
}
$reviewCollection->load()->addRateVotes();

$items = $reviewCollection->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$headingTag = $block->getData('heading_tag') ?: 'h3';
$productName = $block->getProduct()->getName();

?>
<?php if (count($items)): ?>
    <div
        class="mx-auto mt-8 px-5 content-wrapper"
        id="customer-review-list"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Customer Reviews')) ?>"
        tabindex="-1"
        role="group"
    >
        <div class="flex mb-6 md:flex-row">
            <?php if (!$block->getHideTitle()): ?>
                <h2 class="text-lg font-bold">
                    <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
                </h2>
            <?php endif ?>
        </div>
        <div class="w-full" data-content-wrapper>
            <!-- pagination-content -->
            <?php foreach ($items as $review): ?>
                <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                     class="border-b pb-4 my-4 border-container last:border-0 last:mb-0 mb-5 p-5 rounded-xl bg-bg-400">
                    <?php if (count($review->getRatingVotes())): ?>
                        <div>
                            <?php foreach ($review->getRatingVotes() as $vote): ?>
                                <?php
                                $rating = $vote->getPercent();
                                $ratingSteps = 5;
                                $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                                $starsEmpty = floor($ratingSteps - $starsFilled);
                                ?>
                                <div class="mb-1 md:text-lg">
                                    <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
                                    <strong itemprop="author" itemscope itemtype="https://schema.org/Person">
                                        <span itemprop="name"><?= $escaper->escapeHtml($review->getNickname()) ?></span>
                                    </strong>
                                </div>
                                <div class="mb-3">
                                    <span><?= $escaper->escapeHtml(__('Created at')) ?></span>
                                    <time
                                        itemprop="datePublished"
                                        datetime="<?= $escaper->escapeHtmlAttr($block->formatDate($review->getCreatedAt(), $format)); ?>"
                                    >
                                <span class="sr-only">
                                    <?= $escaper->escapeHtml(
                                        $block->formatDate(
                                            $review->getCreatedAt(),
                                            $formatLong
                                        )
                                    ) ?>
                                </span>
                                        <span aria-hidden="true">
                                    <?= $escaper->escapeHtml(
                                        $block->formatDate($review->getCreatedAt(), $format)
                                    ) ?>
                                </span>
                                    </time>
                                </div>
                                <div class="flex items-center mb-3" itemprop="reviewRating" itemscope
                                     itemtype="http://schema.org/Rating">
                                <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */
                                    $starsFilled; ?></span>
                                    <div class="flex gap-4">
                                        <div class="flex gap-4 items-center">
                                            <div class="flex">
                                                <?php $i = 0; ?>
                                                <?php while ($i < $starsFilled): ?>
                                                    <?= $hyvaicons->renderHtml('star', 'text-xl text-primary-500') ?>
                                                    <?php $i++; ?>
                                                <?php endwhile; ?>
                                                <?php $i = 0; ?>
                                                <?php while ($i < $starsEmpty): ?>
                                                    <?= $hyvaicons->renderHtml('star', 'text-xl text-secondary-700') ?>
                                                    <?php $i++; ?>
                                                <?php endwhile; ?>
                                            </div>
                                            <div>
                                                <p class="text-primary-600"><?= $starsFilled ?>.0</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div>
                        <div class="font-bold md:text-lg mb-3" itemprop="name">
                            <?= $escaper->escapeHtml($review->getTitle()) ?>
                        </div>
                        <div class="mt-2" itemprop="description">
                            <?= /* @noEscape */
                            nl2br($escaper->escapeHtml($review->getDetail())) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <!-- end-pagination-content -->
        </div>
        <?php if ($toolbar): ?>
            <div class="toolbar review-toolbar mt-4">
                <?= $toolbar->toHtml() ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
