<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$title = $block->getLayout()->getBlock('page.main.title') ?
    $block->getLayout()->getBlock('page.main.title')->getPageHeading() :
    __('404');

$content = $block->getChildHtml('cms_page') ?? $block->getChildHtml('cms_noroute');
?>

<div class="flex h-full flex-col items-center justify-center gap-5">
    <p class="text-[80px] leading-none">
        <?= $title; ?>
    </p>

    <?= $content ?>
</div>

<script>
    document.querySelectorAll('.custom-404-container a').forEach(elm => {
        elm.classList.add('button', 'button--filled-primary');
        elm.setAttribute('x-element-transition-trigger', '');
    });

    document.querySelector('.custom-404-container h1').classList.add('text-2xl', 'text-text-500');
</script>
