<?php

declare(strict_types=1);

use Satoshi\Theme\Block\CustomNotFound;
use Magento\Framework\Escaper;

/** @var CustomNotFound $block */
/** @var Escaper $escaper */
?>

<div class="flex h-full flex-col items-center justify-center gap-5">
    <p class="text-[80px] leading-none">
        <?= $block->escapeHtml($block->getNotFoundText()) ?>
    </p>
    <h1 class="text-2xl text-text-500">
        <?= $block->escapeHtml($block->getNotFoundTitle()) ?>
    </h1>
    <a x-element-transition-trigger href="<?= $escaper->escapeUrl($block->getContinueShoppingUrl()) ?>" class="button button--filled-primary">
        <?= $block->escapeHtml($block->getContinueShoppingText()) ?>
    </a>
</div>
