<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<div class="flex h-full flex-col items-center justify-center gap-5">
    <p class="text-[80px] leading-none">
        <?= __('404') ?>
    </p>
    <h1 class="text-2xl text-text-500">
        <?= __('Page not be found.') ?>
    </h1>
    <a x-element-transition-trigger
       href="<?= $escaper->escapeUrl($block->getUrl('/')) ?>"
       class="button button--filled-primary">
        <?= __('Continue Shopping') ?>
    </a>
</div>
