<?php

use Magento\Framework\View\Element\Template as Block;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Pricing\Price\FinalPrice;
use Magento\Catalog\Pricing\Price\RegularPrice;
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Catalog\Pricing\Price\SpecialPrice;
use Magento\Msrp\Pricing\Price\MsrpPrice;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/* @var Block $block */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */
/** @var ProductPrice $productPriceViewModel */

$productViewModel = $viewModels->require(ProductPage::class);
$productPriceViewModel = $viewModels->require(ProductPrice::class);

$product = $block->getData('product');
$customClass = $block->getData('class') ? " {$block->getData('class')}" : '';
$isInline = (bool)$block->getData('isInline');
$isAlpineTemplate = (bool)$block->getData('isAlpineTemplate');
$showBadge = (bool)$block->getData('showBadge');

$regularPrice = $finalPrice = $specialPrice = $tierPrices = $msrpPrice = null;
if ($product) {
    $regularPrice = $productPriceViewModel->getPriceValue(RegularPrice::PRICE_CODE, $product);
    $finalPrice = $productPriceViewModel->getPriceValue(FinalPrice::PRICE_CODE, $product);
    $specialPrice = $productPriceViewModel->getPriceValue(SpecialPrice::PRICE_CODE, $product);
    $tierPrices = $productPriceViewModel->getTierPrices(TierPrice::PRICE_CODE, $product);
    $msrpPrice = iterator_to_array($product->getPriceInfo()->getPrices())[MsrpPrice::PRICE_CODE] ?? null;
}

$specialPriceFrom = $product?->getSpecialFromDate();
$specialPriceTo = $product?->getSpecialToDate();
$currentDate = date('Y-m-d H:i:s');

$isSpecialPriceValid = $specialPrice && $specialPriceFrom <= $currentDate && $specialPriceTo >= $currentDate;
$customOptionPrices = [];

?>

<?php if ($isAlpineTemplate): ?>
    <div class="price__element flex items-center gap-2 text-text-500 <?= $customClass ?>">
        <template x-if="product.price_range.minimum_price.final_price.value < product.price_range.minimum_price.regular_price.value">
            <div>
                <span class="sr-only"><?= __('Sale Price') ?></span>
                <span class="text-primary-500" x-text="parseFloat(product.price_range.minimum_price.final_price.value).toFixed(2) + ' ' + product.price_range.minimum_price.final_price.currency"></span>
                <s x-text="parseFloat(product.price_range.minimum_price.regular_price.value).toFixed(2) + ' ' + product.price_range.minimum_price.regular_price.currency"></s>
            </div>
        </template>
        <template x-if="product.price_range.minimum_price.final_price.value === product.price_range.minimum_price.regular_price.value && product.price_range.minimum_price.value != product.price_range.maximum_price.value">
            <div>
                <span><?= __('From') ?></span>
                <span class="text-primary-500" x-text="parseFloat(product.price_range.minimum_price.final_price.value).toFixed(2) + ' ' + product.price_range.minimum_price.final_price.currency"></span>
            </div>
        </template>
        <template x-if="product.price_range.minimum_price.final_price.value === product.price_range.minimum_price.regular_price.value && product.price_range.minimum_price.value === product.price_range.maximum_price.value">
            <div>
                <span class="sr-only"><?= __('Regular Price') ?></span>
                <span class="text-primary-500" x-text="parseFloat(product.price_range.minimum_price.final_price.value).toFixed(2) + ' ' + product.price_range.minimum_price.final_price.currency"></span>
            </div>
        </template>
    </div>
<?php else: ?>
    <div class="<?= $isInline ? 'flex items-end flex-grow gap-3 mt-3 [&>div]:mt-0' : 'contents' ?>">
        <div
            class="price__element flex items-center gap-x-2 text-text-500 flex-wrap sm:justify-start justify-end sm:text-left text-right<?= $customClass ?>">
            <?php if ($isSpecialPriceValid): ?>
                <span class="sr-only"><?= __('Sale Price') ?></span>
                <span class="text-primary-500">
                <?= /** @noEscape */
                $productViewModel->format($specialPrice) ?>
            </span>
                <s>
                    <?= /** @noEscape */
                    $productViewModel->format($regularPrice) ?>
                </s>
            <?php elseif ($product->getPriceMin() != $product->getPriceMax()): ?>
                <span><?= __('From') ?></span>
                <span>
                <?= /** @noEscape */
                $productViewModel->format($product->getPriceMin()) ?>
            </span>
            <?php else: ?>
                <span class="sr-only"><?= __('Regular Price') ?></span>
                <span class="text-primary-500">
                <?= /** @noEscape */
                $productViewModel->format($regularPrice) ?>
            </span>
            <?php endif; ?>

            <?php if ($tierPrices): ?>
                <span class="sr-only"><?= __('From') ?></span>
                <span class="text-primary-500">
                <?= /** @noEscape */
                $productViewModel->format($productPriceViewModel->getLowestTierPrice($tierPrices)) ?>
            </span>
            <?php endif; ?>

            <?php if ($msrpPrice && $msrpPrice->canApplyMsrp($product) && $msrpPrice->isMinimalPriceLessMsrp($product)): ?>
                <span class="sr-only"><?= __('MSRP') ?></span>
                <span class="text-gray-500">
                <?= /** @noEscape */
                $productViewModel->format($msrpPrice->getAmount()->getValue()) ?>
            </span>
            <?php endif; ?>

            <?php if ($productPriceViewModel->displayPriceIncludingTax()): ?>
                <div class="text-nowrap text-[14px] w-full"><?= __('Tax included.') ?></div>
            <?php elseif ($productPriceViewModel->displayPriceInclAndExclTax()): ?>
                <div class="text-nowrap text-[14px] w-full"><?= __('Tax excluded.') ?></div>
            <?php endif; ?>

            <?php if (!empty($customOptionPrices)): ?>
                <span class="sr-only"><?= __('Custom Options Price') ?></span>
                <span class="text-primary-500">
                <?= /** @noEscape */
                $productViewModel->format($finalPrice + array_sum($customOptionPrices)) ?>
            </span>
            <?php endif; ?>

            <?php if ($showBadge): ?>
                <?=
                $template
                    ->setData([
                        'product' => $product,
                        'isAlpineTemplate' => $isAlpineTemplate,
                        'class' => 'ms-3 static max-md:hidden !bg-secondary-500',
                    ])
                    ->render('Magento_Catalog::product/element/_discount-badge.phtml');
                ?>
            <?php endif; ?>

            <?php if (!$product->isSaleable()): ?>
                <span class="unavailable"><?= __('Out of Stock') ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
