<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image;
use Magento\Wishlist\Model\Item;

/** @var Image $block */
/** @var Escaper $escaper */

/** @var Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$imageUrl = $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->getImageUrl();
?>
<a
    class="flex overflow-hidden rounded-xl bg-[--fade-in-bg] aspect-product mb-5"
    tabindex="-1"
    href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
    title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
    x-element-transition-trigger
>
    <img
        class="mix-blend-darken object-center object-cover h-full w-full"
        src="<?= $escaper->escapeUrl($imageUrl) ?>"
        alt="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
        loading="lazy"
    />
</a>
