<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove;
use Magento\Framework\Escaper;
use Magento\Wishlist\Model\Item;

/** @var Remove $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<a
    href="#"
    data-role="remove"
    @click.prevent='postForm(<?= /* @noEscape */
    $block->getItemRemoveParams($block->getItem()) ?>)'
    title="<?= $escaper->escapeHtmlAttr(__('Remove Item')) ?>"
    class="button button--outline-primary w-11 md:w-12 p-0"
>
    <?= $hyvaicons->renderHtml('remove', 'text-lg', attributes: ['title' => $escaper->escapeHtmlAttr(__('Remove Item'))]) ?>
    <span class="sr-only">
        <?= $escaper->escapeHtml(__('Remove item %1', $product->getName())) ?>
    </span>
</a>
