<style>
    @font-face {
        font-family: 'Satoshi';
        src: url("<?= $this->getViewFileUrl('fonts/Satoshi-Medium.woff2') ?>") format('woff2'),
        url("<?= $this->getViewFileUrl('fonts/Satoshi-Medium.woff') ?>") format('woff');
        font-weight: 500;
        font-display: swap;
        font-style: normal;
    }

    @font-face {
        font-family: 'Satoshi';
        src: url("<?= $this->getViewFileUrl('fonts/Satoshi-Bold.woff2') ?>") format('woff2'),
        url("<?= $this->getViewFileUrl('fonts/Satoshi-Bold.woff') ?>") format('woff');
        font-weight: 700;
        font-display: swap;
        font-style: normal;
    }

    :root {
        --font-body-family: 'Satoshi', sans-serif;
        --font-body-style: 'normal';
        --font-body-weight: 500;

        --font-heading-family: 'Satoshi', sans-serif;
        --font-heading-style: 'normal';
        --font-heading-weight: 700;

        --progress-bar-color: #29d;
        --progress-bar-height: 2px;

        --fade-in-bg: #F3F3F3;

        --color-primary-50: #7e7e7e;
        --color-primary-100: #4b4b4b;
        --color-primary-400: #252525;
        --color-primary-500: #181818;
        --color-primary-600: #0b0b0b;
        --color-primary-700: #3F3F3F;

        --color-background-50: #ffffff;
        --color-background-100: #ffffff;
        --color-background-400: #ffffff;
        --color-background-500: #f9f9f9;
        --color-background-600: #efefef;
        --color-background-700: #e6e6e6;


        /* On dark bg, lighter color is lighter */
        /* On light bg, lighter color is darker */

        /* bg_is_darker: false; */
        --color-primary-800: #181818;
        --color-text-50: #000000;
        --color-text-100: #0f0f0f;
        --color-text-400: #353535;
        --color-text-500: #424242;
        --color-text-600: #4f4f4f;
        --color-text-700: #5c5c5c;
        --color-overlay: #18181833;
        --color-overlay-dark: #18181866;
        --header-shadow: 0 10px 8px rgb(0 0 0 / 0.04);

        --color-secondary-50: #ffffff;
        --color-secondary-100: #ffffff;
        --color-secondary-400: #ffffff;
        --color-secondary-500: #f5f5f5;
        --color-secondary-600: #e8e8e8;
        --color-secondary-700: #dcdcdc;
    }

    /* On dark bg, lighter color should become even lighter */
    /* On light bg, lighter color should become darker */

    @media (prefers-contrast: more) {
        :root {

            /* bg_is_darker: false; */
            --color-text-50: #000000;
            --color-text-100: #000000;
            --color-text-400: #1c1c1c;
            --color-text-500: #292929;
            --color-text-600: #353535;
            --color-text-700: #424242;

            --color-primary-50: #000000;
            --color-primary-100: #000000;
            --color-primary-400: #000000;
            --color-primary-500: #000000;
            --color-primary-600: #0b0b0b;
            --color-primary-700: #181818;
        }
    }

    *,
    *::before,
    *::after {
        box-sizing: inherit;
    }

    html {
        box-sizing: border-box;
        height: 100%;
        text-rendering: optimizeLegibility;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 16px;
    }

    body {
        display: grid;
        grid-template-rows: 1fr auto;
        min-height: 100%;
        margin: 0;
        font-size: 1rem;
    }
</style>
