<style>
:root {
  --font-body-family: 'Satoshi', sans-serif;
  --font-body-style: 'normal';
  --font-body-weight: 500;

  --font-heading-family: 'Satoshi', sans-serif;
  --font-heading-style: 'normal';
  --font-heading-weight: 700;

  --media-border-opacity: 1.0;
  --media-border-width: 0px;
  --media-radius: 16px;
  --media-shadow-opacity: 0.1;
  --media-shadow-horizontal-offset: 0px;
  --media-shadow-vertical-offset: 0px;
  --media-shadow-blur-radius: 0px;

  --page-width: 0rem;
  --page-width-margin: 0rem;

  --card-corner-radius: 0.0rem;
  --card-shadow-vertical-offset: 0.0rem;

  --badges-border-opacity: 1.0;
  --badges-border-width: 0px;
  --badge-corner-radius: 40px;
  --badge-shadow-opacity: 0.1;
  --badge-shadow-horizontal-offset: 0px;
  --badge-shadow-vertical-offset: 0px;
  --badge-shadow-blur-radius: 0px;

  --grid-desktop-vertical-spacing: 16px;
  --grid-desktop-horizontal-spacing: 16px;
  --grid-mobile-vertical-spacing: 8px;
  --grid-mobile-horizontal-spacing: 8px;

  --buttons-border-opacity: 1.0;
  --buttons-border-width: 1px;
  --buttons-radius: 8px;
  --buttons-shadow-opacity: 0.0;
  --buttons-shadow-horizontal-offset: 0px;
  --buttons-shadow-vertical-offset: 0px;
  --buttons-shadow-blur-radius: 0px;

  --inputs-border-width: 1px;
  --inputs-border-opacity: 1.0;
  --inputs-radius: 8px;
  --inputs-shadow-opacity: 0.0;
  --inputs-shadow-horizontal-offset: 0px;
  --inputs-shadow-vertical-offset: 0px;
  --inputs-shadow-blur-radius: 0px;

  --card-border-width: 0px;
  --card-border-opacity: 0.0;
  --card-border-radius: 0px;
  --card-shadow-opacity: 0.1;
  --card-shadow-horizontal-offset: 0px;
  --card-shadow-vertical-offset: 0px;
  --card-shadow-blur-radius: 0px;

  --progress-bar-color: #29d;
  --progress-bar-height: 2px;

  --fade-in-bg: #F3F3F3;

  --color-primary-50: #f1f3f0;
  --color-primary-100: #bcc4b9;
  --color-primary-400: #94a28f;
  --color-primary-500: #879681;
  --color-primary-600: #7a8a73;
  --color-primary-700: #6e7c68;

  --color-background-50: #ffffff;
  --color-background-100: #ffffff;
  --color-background-400: #ffffff;
  --color-background-500: #f5f8f6;
  --color-background-600: #e6ede9;
  --color-background-700: #d7e3db;

  /* On dark bg, lighter color is lighter */
  /* On light bg, lighter color is darker */

  /* bg_is_darker: false; */
  --color-text-50: #000000;
  --color-text-100: #000000;
  --color-text-400: #252421;
  --color-text-500: #32312d;
  --color-text-600: #3f3e39;
  --color-text-700: #4d4b45;

  --color-secondary-50: #ffffff;
  --color-secondary-100: #f6f6f5;
  --color-secondary-400: #d0d2cc;
  --color-secondary-500: #c4c6bf;
  --color-secondary-600: #b8bab2;
  --color-secondary-700: #abaea4;
}

/* On dark bg, lighter color should become even lighter */
/* On light bg, lighter color should become darker */

@media (prefers-contrast: more) {
  :root {

    /* bg_is_darker: false; */
    --color-text-50: #000000;
    --color-text-100: #000000;
    --color-text-400: #0a0a09;
    --color-text-500: #171715;
    --color-text-600: #252421;
    --color-text-700: #32312d;

    --color-primary-50: #0c0d0b;
    --color-primary-100: #3d4539;
    --color-primary-400: #616e5c;
    --color-primary-500: #6e7c68;
    --color-primary-600: #7a8a73;
    --color-primary-700: #879681;

  }
}


*,
*::before,
*::after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
  height: 100%;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-size: 16px;
}

body {
  display: grid;
  grid-template-rows: 1fr auto;
  min-height: 100%;
  margin: 0;
  font-size: 1rem;
  line-height: calc(1 + 0.8 / var(--font-body-scale));
  font-family: var(--font-body-family);
  font-style: var(--font-body-style);
  font-weight: var(--font-body-weight);
}
</style>
