<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Magento\Framework\Escaper;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);
$currencies = $currencyViewModel->getCurrencies();
$currentCurrencyCode = $currencyViewModel->getCurrentCurrencyCode();

$options = [];
foreach ($currencies as $code => $currency) {
    $name = $currency['name'];
    $symbol = $currency['symbol'] ? "({$currency['symbol']})" : '';
    $label = "
        <span>{$escaper->escapeHtml($name)}</span>
        <span>{$escaper->escapeHtml("$code $symbol")}</span>
    ";

    $options[] = [
        'value' => $escaper->escapeHtml($code),
        'label' => $label,
        'on_click' => "hyva.postForm({$currencyViewModel->getSwitchCurrencyPostData($code)})",
        'is_active' => $code === $currentCurrencyCode,
    ];
}

$currentLabel = $currencies[$currentCurrencyCode] ?
    $escaper->escapeHtml("{$currencies[$currentCurrencyCode]['name']} | {$currentCurrencyCode}") :
    $escaper->escapeHtml($currentCurrencyCode);

?>

<?php if ($currencyViewModel->getCurrencyCount() > 1): ?>
    <?=
    $template
        ->setData([
            'id' => 'currency-selector',
            'label' => $currentLabel,
            'options' => $options,
            'currentValue' => $currentCurrencyCode,
            'withSearch' => true,
        ])
        ->render('Magento_Theme::html/dropdown.phtml');
    ?>
<?php endif; ?>
