<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Customer\Block\Account\Dashboard\Address;
use Magento\Framework\Escaper;

/** @var Address $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>

<div class="mt-8">
    <div class="mb-5 flex justify-between items-center">
        <h2 class="text-text-500 text-lg font-bold">
            <?= $escaper->escapeHtml(__('Address Book')) ?>
        </h2>
        <a class="button button--ghost-primary"
           href="<?= $escaper->escapeUrl($block->getAddressBookUrl()) ?>"
        >
            <span><?= $escaper->escapeHtml(__('Manage Addresses')) ?></span>
        </a>
    </div>

    <div class="grid gap-5 md:gap-8 grid-cols-1 md:grid-cols-2">
        <div class="bg-white p-5 rounded-xl">
            <h2 class="text-text-500 text-lg font-bold mb-4">
                <?= $escaper->escapeHtml(__('Default billing address')) ?>
            </h2>
            <div class="mb-7">
                <?= $block->getPrimaryBillingAddressHtml() ?>
            </div>
            <div>
                <a
                    class="button button--outline-primary w-full md:w-auto"
                    href="<?= $escaper->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>"
                    data-ui-id="default-billing-edit-link"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Edit address - billing default')) ?>"
                >
                    <span><?= $escaper->escapeHtml(__('Edit address')) ?></span>
                </a>
            </div>
        </div>
        <div class="bg-white p-5 rounded-xl">
                <h2 class="text-text-500 text-lg font-bold mb-4">
                    <?= $escaper->escapeHtml(__('Default billing address')) ?>
                </h2>
                <div class="mb-7">
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </div>
                <div>
                    <a
                        class="button button--outline-primary w-full md:w-auto"
                        href="<?= $escaper->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>"
                        data-ui-id="default-billing-edit-link"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Edit address - shipping default')) ?>"
                    >
                        <span><?= $escaper->escapeHtml(__('Edit address')) ?></span>
                    </a>
                </div>
            </div>
    </div>
</div>
