<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Satoshi\Customer\Block\Account\Dashboard\Info;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Info $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$successMessage = $block->getSuccessMessage();
$errorMessage = $block->getErrorMessage();
?>

<?php if ($successMessage): ?>
    <div class="field-success -mt-3 mb-3">
        <span><?= $successMessage ?></span>
    </div>
<?php elseif ($errorMessage): ?>
    <div class="field-error -mt-3 mb-3">
        <span class="messages"><?= $errorMessage ?></span>
    </div>
<?php endif; ?>

<h2 class="text-text-500 text-lg font-bold mb-5">
    <?= $escaper->escapeHtml(__('Account Information')) ?>
</h2>
<div class="grid gap-5 lg:gap-8 grid-cols-1 lg:grid-cols-2">
    <div class="bg-bg-400 p-7 rounded-xl flex flex-col md:flex-row gap-4 md:gap-5">
        <div class="self-start flex items-center align-center gap-4">
            <div class="p-4 text-primary-500 bg-bg-500 rounded-xl">
                <?= $hyvaicons->renderHtml('user', 'w-6 h-6') ?>
            </div>

            <h2 class="md:hidden text-text-500 text-lg font-bold">
                <?= $escaper->escapeHtml(__('My Account')) ?>
            </h2>
        </div>
        <div class="grow md:flex md:flex-col md:justify-between">
            <div>
                <h2 class="hidden md:block text-text-500 text-lg font-bold mb-4">
                    <?= $escaper->escapeHtml(__('My Account')) ?>
                </h2>
                <p class="mb-3"><?= $escaper->escapeHtml($block->getName()) ?></p>
                <p class="mb-7"><?= $escaper->escapeHtml($block->getCustomer()->getEmail()) ?></p>
            </div>

            <div class="flex gap-3 flex-col md:flex-row">
                <a
                    class="button button--outline-primary"
                    href="<?= $escaper->escapeUrl($block->getUrl('customer/account/edit')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('Edit contact information')) ?>"
                    x-element-transition-trigger
                >
                    <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
                </a>
                <a
                    class="button button--ghost-primary"
                    href="<?= $escaper->escapeUrl($block->getChangePasswordUrl()) ?>"
                    x-element-transition-trigger
                >
                    <?= $escaper->escapeHtml(__('Edit Password')) ?>
                </a>
            </div>
        </div>
    </div>
    <?php if ($block->isNewsletterEnabled()): ?>
        <div class="bg-bg-400 p-7 rounded-xl flex flex-col md:flex-row gap-4 md:gap-5">
            <div class="self-start flex items-center align-center gap-4">
                <div class="p-4 text-primary-500 bg-bg-500 rounded-xl">
                    <?= $hyvaicons->renderHtml('envelope', 'w-6 h-6') ?>
                </div>

                <h2 class="md:hidden text-text-500 text-lg font-bold">
                    <?= $escaper->escapeHtml(__('My Newsletters')) ?>
                </h2>
            </div>
            <div class="grow md:flex md:flex-col md:justify-between">
                <div>
                    <h2 class="hidden md:block text-text-500 text-lg font-bold mb-4">
                        <?= $escaper->escapeHtml(__('Newsletters')) ?>
                    </h2>
                    <p class="mb-7">
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $escaper->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $escaper->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="flex gap-3 flex-col md:flex-row">
                    <a
                        class="button button--outline-primary mb-5 md:mb-0"
                        href="<?= $escaper->escapeUrl($block->getUrl('newsletter/manage')) ?>"
                        aria-label="<?= $escaper->escapeHtml(__('Edit newsletters')) ?>"
                        x-element-transition-trigger
                    >
                        <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
                    </a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?= $block->getChildHtml('additional_blocks'); ?>
</div>
