<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>

<template x-fallback-template-type="category">
  <!--Breadcrumbs fallback-->
  <div class="mt-[72px] md:mt-[89px]"></div>

  <div class="max-md:hidden">
    <?= $block->getChildHtml('category.breadcrumbs.placeholder') ?>
  </div>

  <article
    aria-label="<?= __('Category details') ?>"
    class="content-wrapper mx-auto flex flex-col items-start gap-3 py-5 pb-6 pt-3"
  >
    <template x-if="$store['transition'].pageData?.img">
      <div class="mb-2 h-[40vh] w-full rounded-md bg-[--fade-in-bg] object-cover">
        <img
          :src="$store['transition'].pageData?.img"
          :alt="$store['transition'].pageData?.title"
          class="no-fade h-[40vh] w-full rounded-md object-cover transition-opacity duration-300"
          width="100%"
          height="100%"
        >
      </div>
    </template>
    <div class="flex flex-col gap-3">
        <h1 class="text-xl md:text-[32px] text-text-500" x-text="$store['transition'].pageData?.title"></h1>
      <div
        class="rte"
        x-html="$store['transition'].pageData?.description"
        x-show="$store['transition'].pageData?.description && $store['transition'].pageData?.description !== ''"
      >
      </div>
    </div>
    <div class="min-h-screen"></div>
  </article>
</template>
