<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// reCaptcha v2 "I'm not a robot" form element

$storeConfig = $viewModels->require(StoreConfig::class);
$recaptcha   = $viewModels->require(ReCaptcha::class);
$siteKey     = $storeConfig->getStoreConfig('recaptcha_frontend/type_recaptcha/public_key');

if (!$siteKey) {
    // No v2 checkbox google API credentials configured
    return;
}

$inputElementId        = $block->getData('input_element_id');
$instanceSuffix        = $recaptcha->calcJsInstanceSuffix($inputElementId ?: $block->getData('form_id') ?: 'x');
$grecaptchaContainerId = "grecaptcha-container-$instanceSuffix";

// Explicitly render the recaptcha, so it doesn't use the first .g-recaptcha on the page
?>
<div
    x-data="Recaptcha({
        containerId: '<?= $escaper->escapeJs($grecaptchaContainerId) ?>',
        siteKey: '<?= $escaper->escapeJs($siteKey) ?>'
    })"
    x-init="initRecaptchaCheckbox"
    id="<?= $escaper->escapeHtmlAttr($grecaptchaContainerId) ?>"
    class="g-recaptcha"
></div>
