<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\ViewModel\Product\Breadcrumbs;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$breadcrumbsViewModel = $viewModels->require(Breadcrumbs::class);
$categoryUrlSuffix = $breadcrumbsViewModel->getCategoryUrlSuffix();

?>
<div
    x-show="searchTerm.length > 2"
    :class="{
        'opacity-0': isLoading && !getIsSearchActive(),
    }"
>
    <div class="relative flex grow flex-col gap-4 p-3 pb-2 md:p-5">
        <div class="pb-2">
            <h2 class="text-lg"><?= __('Categories') ?></h2>
        </div>
        <div class="flex flex-col gap-2">
            <p x-show="!isLoading && !categories.length && searchTerm">
                <b class="font-semibold text-secondary-700"><?= __('Oops!') ?></b>
                <?= __('We could not find any categories matching your search.') ?>
            </p>

            <div
                x-show="categories.length"
                class="-mx-5 flex gap-3 overflow-x-auto px-5 py-1 md:max-w-[--search-width] max-md:pb-3"
            >
                <template x-for="category in categories">
                    <a
                        :href="`/${category.url_path}<?= $escaper->escapeUrl($categoryUrlSuffix) ?>`"
                        class="button button--outline-secondary"
                        x-element-transition-trigger:category.animate="{
                            'title': category.name,
                        }"
                        x-text="category.name"
                    ></a>
                </template>
            </div>
        </div>
    </div>

    <hr
        x-show="searchTerm.length > 2"
        class="divider -mx-3"
        :class="{ 'opacity-0': isLoading }"
    >
</div>

