<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');

$formId = 'user_forgotpassword';

$errorMessage = $block->getErrorMessage();

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>

<div class="container mx-auto flex h-full items-center px-5">
    <div class="mx-auto w-[412px] max-w-full mb-16" x-data="Object.assign(Form('<?= $escaper->escapeHtmlAttr($formId) ?>'), Authentication)">
        <header class="sm:text-center mb-7">
            <h2 class="text-2xl mb-3 md:mb-4"><?= __('Reset your password') ?></h2>
            <p class="mb-7 text-md text-text-500"><?= __('We will send you an email to reset your password') ?></p>
        </header>

        <form
            action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
            method="post"
            id="<?= $escaper->escapeHtmlAttr($formId) ?>"
            @submit.prevent="function($event) {
                // do not rename $form, the variable is the expected name in the recaptcha output
                const $form = $event.target;
                <?= $recaptcha ? $escaper->escapeHtmlAttr($recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD)) : '' ?>
                if (this.errors === 0) {
                    this.submitForm();
                }
            }"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>"/>
            <?= $block->getChildHtml('form_fields_before') ?>

            <template x-if="displayErrorMessage">
                <p class="field-error -mt-3 mb-3">
                    <template x-for="errorMessage in errorMessages">
                        <span class="messages" x-html="errorMessage"></span>
                    </template>
                </p>
            </template>

            <div class="flex flex-col gap-3 mb-4">
                <div class="field field-reserved <?= $errorMessage ? 'field-error' : '' ?>">
                    <label for="email_address" class="sr-only tracking-widest">
                        <?= __('Email') ?>
                    </label>
                    <div>
                        <input
                            type="email"
                            placeholder="Email address"
                            name="email"
                            alt="email"
                            id="email_address"
                            class="input__field input__field--outline bg-bg-500 px-5 py-4"
                            autocomplete="<?= $isAutocompleteEnabled ? 'username' : 'off' ?>"
                            required
                            value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>"
                        />
                    </div>
                    <?php if ($errorMessage): ?>
                        <div class="field-error mt-1">
                            <span class="messages"><?= $errorMessage ?></span>
                        </div>
                    <?php endif; ?>
                </div>

                <?= $block->getChildHtml('form_additional_info') ?>
                <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
            </div>

            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>

            <div class="flex flex-col gap-6 mt-4">
                <button
                    class="button button--filled-primary"
                    :class="isLoading ? 'button--disabled' : ''"
                    :disabled="isLoading"
                    type="submit"
                >
                    <?= __('Reset My Password') ?>
                </button>
                <div class="text-center tracking-wider">
                    <a
                        href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"
                        class="link link--primary"
                        x-element-transition-trigger
                    >
                        <?= __('Go back') ?>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
