<?php

declare(strict_types=1);

use Magento\Customer\Block\Address\Book;
use Satoshi\Theme\Block\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var SvgIcons $hyvaicons */
/** @var ViewModelRegistry $viewModels */
/** @var Template $template */
/** @var Book $block */

$hyvaicons = $viewModels->require(SvgIcons::class);

$deleteId = $block->getRequest()->getParam('id');
?>

<div class="flex items-center justify-between max-md:px-2 max-md:pt-2">
    <span class="mb-2 block md:mb-3 md:px-5 md:text-text-500 max-md:font-bold">
        <?= __('Delete Address') ?>
    </span>

    <button
        class="border-text-text-500 rounded-sm border p-3 md:hidden"
        @click="$store.popup.hidePopup('delete-address')"
    >
        <?= $hyvaicons->renderHtml('close'); ?>
    </button>
</div>

<div class="md:contrast-border rounded-md bg-bg-500 px-2 pb-3 pt-5 md:px-5 md:py-5">
    <p class="text-base">
        <?= __('Are you sure you want to delete this address?') ?>
    </p>

    <div class="mt-5 flex items-center justify-center gap-4">
        <form
            action="<?= $block->getUrl('customer/address/delete', ['id' => $deleteId]) ?>"
            method="post"
            data-confirm-message="<?= __('Are you sure you want to delete this address?') ?>"
            class="contents"
        >
            <input type="hidden" name="_method" value="delete">
            <button type="button" @click="hideForm()"
                    class="button button--outline button--outline-primary max-md:hidden">
                <?= __('Cancel') ?>
            </button>
            <button type="submit" class="button button--filled button--filled-primary inline w-full flex-1">
                <?= __('Delete') ?>
            </button>
        </form>
    </div>
</div>
