<?php

declare(strict_types=1);

use Magento\Customer\Block\Address\Edit;
use Satoshi\Theme\Block\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var ViewModelRegistry $viewModels */
/** @var Template $template */
/** @var Edit $block */

$hyvaicons = $viewModels->require(SvgIcons::class);
$address = $block->getAddress();
?>

<div class="flex items-center justify-between max-md:px-2 max-md:pt-2">
    <span class="mb-2 block md:mb-3 md:px-5 md:text-text-500 max-md:font-bold">
        <?= __('Edit Address') ?>
    </span>

    <button
        class="border-text-text-500 rounded-sm border p-3 md:hidden"
        @click="$store.popup.hidePopup('edit-address')"
    >
        <?= $hyvaicons->renderHtml('close'); ?>
    </button>
</div>

<form action="<?= $block->getUrl('customer/address/formPost', ['id' => $address?->getId()]) ?>" method="post">
    <input type="hidden" name="_method" value="put">

    <div class="md:contrast-border rounded-md bg-bg-500 px-2 pb-3 pt-5 md:px-5 md:py-5">
        <div class="mb-3 flex flex-col gap-3 md:flex-row">
            <label for="first_name" class="sr-only tracking-widest"><?= __('First Name') ?></label>
            <input
                type="text"
                name="firstname"
                placeholder="<?= __('First Name') ?>"
                value="<?= $block->escapeHtml($address?->getFirstname()) ?>"
                id="first_name"
                required
                class="input__field input__field--outline h-auto px-5 py-4"
                autofocus
            />

            <label for="last_name" class="sr-only tracking-widest"><?= __('Last Name') ?></label>
            <input
                type="text"
                name="lastname"
                placeholder="<?= __('Last Name') ?>"
                value="<?= $block->escapeHtml($address?->getLastname()) ?>"
                id="last_name"
                required
                class="input__field input__field--outline h-auto px-5 py-4"
            />
        </div>

        <!-- Additional input fields go here similar to above fields -->

        <label class="mb-7 mt-5 flex items-center gap-3 px-4" for="address_default_address_update">
            <input
                type="checkbox"
                id="address_default_address_update"
                name="default_billing"
                <?= $address?->getIsDefaultBilling() ? 'checked' : '' ?>
                class="checkbox__input"
            />
            <span class="checkbox__control" aria-hidden="true">
                <!--                TODO: change svg-->
                <?= $hyvaicons->renderHtml('coupon'); ?>
            </span>
            <span class="checkbox__label ml-0">
                <?= __('Set as Default Address') ?>
            </span>
        </label>

        <div class="flex gap-4">
            <button type="button" @click="hideForm()"
                    class="button button--outline button--outline-primary max-md:hidden">
                <?= __('Cancel') ?>
            </button>
            <button type="submit" class="button button--filled button--filled-primary flex-1">
                <?= __('Update Address') ?>
            </button>
        </div>
    </div>
</form>
