<?php
declare(strict_types=1);

use Magento\Customer\Block\Address\Book;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Satoshi\Theme\Block\Template;

/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */
/** @var Template $template */
/** @var Book $block */

$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div class="flex items-center justify-between max-md:px-2 max-md:pt-2">
    <span class="mb-2 block md:mb-3 md:px-5 md:text-text-500 max-md:font-bold">
        <?= __('Add New Address') ?>
    </span>

    <button
        class="border-text-text-500 rounded-sm border p-3 md:hidden"
        @click="$store.popup.hidePopup('add-new-address')"
    >
        <?= $hyvaicons->renderHtml('close') ?>
    </button>
</div>

<form action="<?= $block->getUrl('customer/address/formPost') ?>" method="post">
    <div class="md:contrast-border rounded-md bg-bg-500 px-2 pb-3 pt-5 md:px-5 md:py-5">
        <div class="mb-3 flex flex-col gap-3 md:flex-row">
            <?= $template
                ->setData([
                    'type' => 'text',
                    'name' => 'firstname',
                    'id' => 'first_name',
                    'label' => 'First Name',
                    'value' => $block->getFirstname(),
                    'placeholder' => 'Enter your first name',
                    'required' => true,
                    'additional_attributes' => 'autofocus',
                ])
                ->render('Magento_Customer::html/_form-field.phtml');
            ?>

            <?= $template
                ->setData([
                    'type' => 'text',
                    'name' => 'lastname',
                    'id' => 'last_name',
                    'label' => 'Last Name',
                    'value' => $block->getLastname(),
                    'placeholder' => 'Enter your last name',
                    'required' => true,
                ])
                ->render('Magento_Customer::html/_form-field.phtml');
            ?>
        </div>

        <!-- Additional input fields go here similar to above fields -->

        <label class="mb-7 mt-5 flex items-center gap-3 px-4" for="address_default_address_new">
            <input
                type="checkbox"
                id="address_default_address_new"
                name="default_billing"
                class="checkbox__input"
            />
            <span class="checkbox__control" aria-hidden="true">
<!--                TODO: change svg-->
                <?= $hyvaicons->renderHtml('coupon'); ?>
            </span>
            <span class="checkbox__label ml-0">
                <?= __('Set as Default Address') ?>
            </span>
        </label>

        <div class="flex gap-4">
            <!--            TODO: fix hideForm()-->
            <button type="button" @click="hideForm()"
                    class="button button--outline button--outline-primary max-md:hidden">
                <?= __('Cancel') ?>
            </button>
            <button type="submit" class="button button--filled button--filled-primary flex-1">
                <?= __('Add Address') ?>
            </button>
        </div>
    </div>
</form>
