<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Customer\Block\Address\Edit;
use Magento\Customer\ViewModel\Address as AddressViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Edit $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

/** @var ViewModelRegistry $viewModels */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var AddressViewModel $addressViewModel */
$addressViewModel = $block->getViewModel();
$directoryViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Directory::class);

$companyBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class);
$phoneBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class);
$faxBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class);
$streetLabel = $block->getAttributeData()->getFrontendLabel('street');
$regionLabel = $block->getAttributeData()->getFrontendLabel('region');
$showOptionalRegions = $block->getConfig('general/region/display_all');
?>

<section>
    <h2 class="text-text-500 text-lg font-bold mb-5">
        <?= $escaper->escapeHtml(__('Customer Address')) ?>
    </h2>
    <form x-data="Object.assign(hyva.formValidation($root), AddressEdit(
                <?= $showOptionalRegions ? 'true' : 'false' ?>,
                '<?= $block->getCountryId() ?>',
                '<?= $escaper->escapeJs($block->getRegion()) ?>',
                '<?= $escaper->escapeJs($block->getRegion() ?: 0) ?>',
                '<?= $escaper->escapeJs(__('The telephone number is too short.')) ?>',
                <?= $escaper->escapeHtmlAttr($block->getPostCodeConfig()->getSerializedPostCodes() ?? []) ?>,
                [
                    '<?= $escaper->escapeJs(__('Provided Zip/Postal Code seems to be invalid.')) ?>',
                    '<?= $escaper->escapeJs(__(' Example: ')) ?>',
                    '<?= $escaper->escapeJs(__('If you believe it is the right one you can ignore this notice.')) ?>'
                ],
            ))"
          action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
          method="post"
          id="form-validate"
          enctype="multipart/form-data"
          data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
          @submit.prevent="submitForm"
          @private-content-loaded.window="onPrivateContentLoaded($event.detail.data);"
    >
        <div class="bg-bg-400 p-5 rounded-xl mb-7 md:mb-8">
            <h2 class="text-text-500 text-lg font-bold mb-5">
                <?= $escaper->escapeHtml(__('Contact Information')) ?>
            </h2>
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">

            <div class="grid lg:grid-cols-2 gap-3">
                <?= $block->getNameBlockHtml() ?>

                <?php if ($companyBlock->isEnabled()): ?>
                    <?= $companyBlock->setCompany($block->getAddress()->getCompany())->toHtml() ?>
                <?php endif ?>

                <?php if ($phoneBlock->isEnabled()): ?>
                    <?= $phoneBlock->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
                <?php endif ?>

                <?php if ($faxBlock->isEnabled()): ?>
                    <?= $faxBlock->setFax($block->getAddress()->getFax())->toHtml() ?>
                <?php endif ?>
            </div>
        </div>

        <h2 class="text-text-500 text-lg font-bold mb-5">
            <?= $escaper->escapeHtml(__('Customer Address')) ?>
        </h2>

        <div class="bg-bg-400 rounded-xl p-5 mb-5">
            <h2 class="text-text-500 text-lg font-bold mb-5">
                <?= $escaper->escapeHtml(__('Address')) ?>
            </h2>
            <div class="grid lg:grid-cols-2 gap-3">
                <div class="field field-reserved">
                    <label for="street_1" class="sr-only tracking-widest">
                        <span><?= /* @noEscape */
                            $streetLabel ?></span>
                    </label>
                    <div>
                        <input type="text"
                               name="street[]"
                               required
                               value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                               title="<?= /* @noEscape */
                               $streetLabel ?>"
                               id="street_1"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your street address')) ?>"
                               class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                               @input.debounce="onChange"
                        />
                    </div>
                </div>

                <?php for ($i = 1, $n = $addressViewModel->addressGetStreetLines(); $i < $n; $i++): ?>
                    <div class="field field-reserved">
                        <label class="sr-only tracking-widest" for="street_<?= /* @noEscape */
                        $i + 1 ?>">
                            <span><?= $escaper->escapeHtml(__('Street Address %1', $i + 1)) ?></span>
                        </label>
                        <div>
                            <input type="text" name="street[]"
                                   value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($i + 1)) ?>"
                                   title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $i + 1)) ?>"
                                   id="street_<?= /* @noEscape */
                                   $i + 1 ?>"
                                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your street address %1', $i + 1)) ?>"
                                   class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                                   @input.debounce="onChange"
                            />
                        </div>
                    </div>
                <?php endfor; ?>

                <?php if ($addressViewModel->addressIsVatAttributeVisible()): ?>
                    <div class="field field-reserved">
                        <label class="sr-only tracking-widest" for="vat_id">
                        <span><?= /* @noEscape */
                            $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                        </label>
                        <div>
                            <input type="text"
                                   name="vat_id"
                                   value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                                   title="<?= /* @noEscape */
                                   $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your VAT ID')) ?>"
                                   class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                                   id="vat_id"
                                   @input.debounce="onChange"
                            />
                        </div>
                    </div>
                <?php endif; ?>

                <div class="field field-reserved !text-text-500">
                    <label class="sr-only tracking-widest" for="zip">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                    </label>
                    <div>
                        <input type="text"
                               name="postcode"
                               x-ref="postcode"
                               value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                               title="<?= /* @noEscape */
                               $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                               id="zip"
                               :required="isZipRequired"
                               @input.debounce="onChange"
                               data-validate='{"postcode": true}'
                               class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your postcode')) ?>"
                        />
                    </div>
                </div>

                <br class="hidden lg:block"/>

                <div class="field field-reserved">
                    <label class="sr-only tracking-widest" for="city">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('city') ?></span>
                    </label>
                    <div>
                        <input type="text"
                               name="city"
                               required
                               value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                               title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your city')) ?>"
                               class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                               id="city"
                               @input.debounce="onChange"
                        />
                    </div>
                </div>

                <div class="field field-reserved">
                    <label class="sr-only tracking-widest" for="country">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                    </label>
                    <?php $countries = $block
                        ->getCountryCollection()
                        ->setForegroundCountries($directoryViewModel->getTopCountryCodes())
                        ->toOptionArray();
                    ?>
                    <div class="relative">
                        <select name="country_id"
                                id="country"
                                title="Country"
                                required
                                class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                                x-ref="country_id"
                                @input.debounce="changeCountry"
                        >
                            <?php foreach ($countries as $country): ?>
                                <option name="<?= /** @noEscape */
                                $country['label'] ?>"
                                        value="<?= /** @noEscape */
                                        $country['value'] ?>"
                                        data-is-zip-required="<?= (isset($country['is_zipcode_optional'])) ? '0' : '1' ?>"
                                        data-is-region-required="<?= (isset($country['is_region_required'])) ? '1' : '0' ?>"
                                    <?= ($block->getCountryId() === $country['value']) ? 'selected="selected"' : '' ?>
                                >
                                    <?= /** @noEscape */
                                    $country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <div class="absolute inset-y-0 right-5 flex items-center pointer-events-none">
                            <?= $hyvaicons->renderHtml('chevron', 'rotate-90') ?>
                        </div>
                    </div>
                </div>

                <div x-cloak
                     x-show="(hasAvailableRegions() && isRegionRequired) || showOptionalRegions"
                >
                    <label class="sr-only tracking-widest" for="region_id">
                            <span><?= /* @noEscape */
                                $regionLabel ?></span>
                    </label>
                    <div class="field field-reserved">
                        <template x-if="hasAvailableRegions() && (isRegionRequired || showOptionalRegions)">
                            <div class="relative">
                                <select id="region_id" name="region_id"
                                        title="<?= /* @noEscape */
                                        $regionLabel ?>"
                                        class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                                        x-ref="region_id"
                                        x-model="selectedRegion"
                                        :required="isRegionRequired"
                                        @input.debounce="onRegionIdChange"
                                >
                                    <option
                                            value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                    <template x-for="regionId in Object.keys(availableRegions)">
                                        <?php /* in alpine v3, if the bound props update, the template body gets evaluated before the template condition */ ?>
                                        <?php /* because of this it is required to check if availableRegions[regionId] is set */ ?>
                                        <option :value="regionId"
                                                :name="availableRegions[regionId] && availableRegions[regionId].name"
                                                x-text="availableRegions[regionId] && availableRegions[regionId].name"
                                                :selected="selectedRegion === regionId"
                                        >
                                        </option>
                                    </template>
                                </select>
                                <div class="absolute inset-y-0 right-5 flex items-center pointer-events-none">
                                    <?= $hyvaicons->renderHtml('chevron', 'rotate-90') ?>
                                </div>
                            </div>
                        </template>
                        <input :type="hasAvailableRegions() && (isRegionRequired || showOptionalRegions) ? 'hidden' : 'text'"
                               id="region"
                               name="region"
                               x-ref="region"
                               value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                               title="<?= /* @noEscape */
                               $regionLabel ?>"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your region')) ?>"
                               class="input__field input__field--outline h-auto bg-bg-500 px-5 py-2.5"
                               aria-label="<?= /* @noEscape */
                               $regionLabel ?>"
                               :required="!hasAvailableRegions() && !showOptionalRegions ? isRegionRequired : false"
                               @input.debounce="onChange"
                        />
                    </div>
                </div>
            </div>

            <?= $block->getChildHtml('fieldset_address_info_additional') ?>

            <?php if (!$block->isDefaultBilling() && $block->canSetAsDefaultBilling()): ?>
                <label class="flex items-center gap-x-3 mt-5 mx-4" for="primary_billing">
                    <input type="checkbox"
                           class="checkbox__input"
                           id="primary_billing"
                           name="default_billing"
                           value="1">
                    <span class="checkbox__control w-5 h-5" aria-hidden="true">
                        <?= $hyvaicons->renderHtml('checkmark') ?>
                    </span>
                    <span class="checkbox__label ml-0">
                        <?= $escaper->escapeHtml(__('Use as my default billing address')) ?>
                    </span>
                </label>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1"/>
            <?php endif; ?>

            <?php if (!$block->isDefaultShipping() && $block->canSetAsDefaultShipping()): ?>
                <label class="flex items-center gap-x-3 mt-3 mx-4" for="primary_shipping">
                    <input type="checkbox"
                           class="checkbox__input"
                           id="primary_shipping"
                           name="default_shipping"
                           value="1"
                    />
                    <span class="checkbox__control w-5 h-5" aria-hidden="true">
                        <?= $hyvaicons->renderHtml('checkmark') ?>
                    </span>
                    <span class="checkbox__label ml-0">
                        <?= $escaper->escapeHtml(__('Use as my default shipping address')) ?>
                    </span>
                </label>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        </div>

        <div class="flex gap-x-4 flex-col md:flex-row">
            <button type="submit"
                    class="button button--filled-primary"
                    :class="isLoading && 'button--disabled'"
                    :disabled="isLoading"
                    data-action="save-address"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>"
            >
                <span x-text="isLoading ?
                    '<?= $escaper->escapeHtml(__('Saving...')) ?>' :
                    '<?= $escaper->escapeHtml(__('Save Address')) ?>'"
                >
                    <?= $escaper->escapeHtml(__('Save Address')) ?>
                </span>
            </button>
            <a class="button button--ghost-primary"
               href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
               x-element-transition-trigger
            >
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </form>
</section>

