<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Customer\Block\Address\Grid;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Grid $block */
/** @var Escaper $escaper */

/** @var ViewModelRegistry $viewModels */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div class="container mx-auto">
    <h2 class="text-text-500 text-lg font-bold">
        <?= $escaper->escapeHtml(__('Address Book')) ?>
    </h2>
    <div class="block-content" x-data="initAddresses()">
        <?php if ($additionalAddresses = $block->getAdditionalAddresses()): ?>
            <?php $i = 0; ?>
            <?php foreach ($additionalAddresses as $address): ?>
                <?php $i++ ?>
                <div class="card grid md:grid-cols-6 gap-4 my-5 bg-white p-5 rounded-xl">
                    <div class="grid grid-cols-2 md:flex md:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Company')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($address->getCompany()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 md:flex md:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Name')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($address->getLastname()) ?>,
                            <?= $escaper->escapeHtml($address->getFirstname()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 md:flex md:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Street Address')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($block->getStreetAddress($address)) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 md:flex md:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('City')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($address->getCity()) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 md:flex md:flex-col gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Country')) ?>
                        </div>
                        <div>
                            <?= $escaper->escapeHtml($block->getCountryByCode($address->getCountryId())) ?>
                        </div>
                    </div>

                    <div class="grid grid-cols-2 md:flex md:flex-col md:items-end gap-2">
                        <div class="text-text-500 text-[14px] font-bold">
                            <?= $escaper->escapeHtml(__('Edit / Remove')) ?>
                        </div>
                        <div class="flex gap-5">
                            <a
                                class="text-[14px] text-primary-500"
                                title="<?= $escaper->escapeHtmlAttr(__('Edit')) ?>"
                                href="<?= $escaper->escapeUrl($block->getUrl(
                                    'customer/address/edit',
                                    ['id' => $address->getId()]
                                )) ?>">
                                <?= $hyvaicons->renderHtml('edit') ?>
                                <span></span>
                            </a>
                            <a
                                class="text-[14px] text-primary-500"
                                title="<?= $escaper->escapeHtmlAttr(__('Delete')) ?>"
                                @click.prevent="deleteAddressById(<?= $escaper->escapeJs($address->getId()) ?>)" href="#">
                                <?= $hyvaicons->renderHtml('remove') ?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <?php if ($block->getChildHtml('pager')): ?>
                <?= $block->getChildHtml('pager') ?>
            <?php endif; ?>

        <?php else: ?>
            <p>
                <?= $escaper->escapeHtml(__('You have no other address entries in your address book.')) ?>
            </p>
        <?php endif ?>

        <script>
            function initAddresses() {
                return {
                    deleteAddressById(id) {
                        if (window.confirm(
                            '<?= $escaper->escapeJs(__('Are you sure you want to delete this address?')) ?>'
                        )) {
                            hyva.postForm(
                                {
                                    "action": '<?= $escaper->escapeJs($block->getDeleteUrl()) ?>',
                                    "data": {
                                        "id": id
                                    }
                                }
                            );
                        }
                    }
                }
            }
        </script>
    </div>
</div>

<div class="container mx-auto mt-5 pb-16 flex flex-col md:flex-row gap-4">
    <a href="<?= $escaper->escapeUrl($block->getUrl('customer/address/new')) ?>"
       class="button button--filled-primary">
            <span>
                <?= $escaper->escapeHtml(__('Add new address')) ?>
            </span>
    </a>
    <a class="button button--primary"
       href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>">
            <span>
                <?= $escaper->escapeHtml(__('Go back')) ?>
            </span>
    </a>
</div>
