<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<nav class="flex h-full flex-col" aria-label="<?= __('Main menu') ?>" x-data="Search" :inert="$store.main.isMobile ? $store.popup.currentPopup !== 'menu' : !$store.resizable.isVisible('menu-desktop')">
  <template x-portal="document.getElementById($store.main.isMobile ? 'search-mobile' : 'search-desktop')">
    <?=
    $block
      ->getLayout()
      ->createBlock(Template::class)
      ->setTemplate('Magento_Theme::html/header/search/search.phtml')
      ->toHtml();
    ?>
  </template>
  <div class="contents md:hidden" id="search-mobile"></div>
  <div id="menu-sections" class="menu__wrapper" x-data="{
      history: ['all'],
      delayedLevel: 1,
      setHistory(history) {
        this.history = history;

        setTimeout(() => {
          this.delayedLevel = history.length;

          if (history.length) {
            const level = history[history.length - 1]
            document.querySelector(`[data-menu-level='${level}'] a`)?.focus();
          }
        }, 300);
      }
    }" x-show="!$store.main.isMobile || !getIsSearchActive()">
    <?=
    $block
      ->getLayout()
      ->createBlock(Template::class)
      ->setTemplate('Magento_Theme::html/header/menu/menu-items.phtml')
      ->setData([
        'id' => 'all',
        'title' => 'All categories',
        'path' => 'all'
      ])
      ->toHtml();
    ?>
  </div>
</nav>