<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\BlockCache;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var BlockCache $blockCacheViewModel */
$blockCacheViewModel = $viewModels->require(BlockCache::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

// Copy child cache tags to this block so they are added to the block_html cache record
$block->setData('cache_tags', $blockCacheViewModel->collectBlockChildrenCacheTags($block));
?>
<button
  @click="!isMenuVisible ? $store.popup.showPopup('menu') : $store.popup.hidePopup('menu')"
  type="button"
  class="md:button--filled-white button icon-button icon-button--size-lg md:w-auto md:px-4 md:gap-3 md:m-2"
>
  <div
    class="contents"
    x-show="!isMenuVisible"
  >
    <?= $hyvaicons->renderHtml('menu') ?>
  </div>
  <div
    class="contents"
    x-show="isMenuVisible"
    style="display: none;"
  >
    <?= $hyvaicons->renderHtml('close') ?>
  </div>
  <span class="text-md font-bold max-md:hidden"><?= __('Menu') ?></span>
</button>