<nav
  class="flex flex-col h-full"
  aria-label="Main menu and search"
  x-data="Search"
>
  <template x-portal="document.getElementById($store.main.isMobile ? 'search-mobile' : 'search-desktop')">
    <?= $block->getChildHtml('search-field'); ?>
  </template>
  <div class="contents md:hidden" id="search-mobile"></div>
  <div
    id="menu-sections"
    class="menu__wrapper"
    x-data="{
      history: ['all'],
      delayedLevel: 1,
      setHistory(history) {
        this.history = history;

        setTimeout(() => {
          this.delayedLevel = history.length;
        }, 300);
      }
    }"
    x-show="!getIsSearchActive()"
    x-init="
      $watch('$store.popup.currentPopup', (value) => {
        if (value !== 'menu') {
          setHistory(['all']);
        }
      });

      $watch('$store.resizable._current', (value) => {
        if (!value['menu-desktop']) {
          setHistory(['all']);
        }
      })
    "
  >
    <?= $block->getChildHtml('menu-items'); ?>
  </div>
</nav>