<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\BlockCache;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var BlockCache $blockCacheViewModel */
$blockCacheViewModel = $viewModels->require(BlockCache::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

// Copy child cache tags to this block so they are added to the block_html cache record
$block->setData('cache_tags', $blockCacheViewModel->collectBlockChildrenCacheTags($block));
?>
<button
    x-a11y-trap-element="$store.transition.isPreviewActive && !$store.resizable.isVisible()"
    @click="!isMenuVisible ? $store.popup.showPopup('menu') : $store.popup.hidePopup('menu')"
    type="button"
    aria-label="<?= __('Open menu') ?>"
    :aria-controls="$store.main.isMobile ? 'menu' : 'menu-desktop'"
    :aria-expanded="$store.main.isMobile ? $store.popup.currentPopup === 'menu' : $store.resizable.isVisible('menu-desktop')"
    class="contrast-border md:button--filled-secondary button icon-button icon-button--size-lg md:w-auto md:gap-3 md:px-4  "
    :class="{'hidden': !$store.main.isMobile && $store.resizable.isVisible('menu-desktop')}"
    tabindex="2"
>
    <div
        class="contents text-text-50"
        :class="{
            'invisible': isMenuVisible,
        }"
        x-show="!isMenuVisible"
    >
        <?= $hyvaicons->renderHtml('menu') ?>
    </div>
    <div
        class="contents"
        :class="{
            'invisible': !isMenuVisible,
        }"
        x-show="isMenuVisible"
        style="display: none;"
    >
        <?= $hyvaicons->renderHtml('close') ?>
    </div>
    <span class="text-md font-semibold max-md:hidden"><?= __('Menu') ?></span>
</button>