<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>

<div class="main-sidebar">
    <div
        class="md:sticky md:top-[--scroll-top]"
        x-sticky-scroll="{
            top: 90,
            bottom: 24,
        }"
    >
        <?= $block->getChildHtml() ?>
    </div>
</div>
