<div
  class="transition-preview"
  x-data="TransitionPreview()"
  :class="
    {
    'transition-preview--active': isActive,
    'is-transition': $store['transition'].isPreviewAnimating
    }
  "
  style="--scroll-progress: 0; --offset-top: 400;"
  :style="
    {
      '--offset-top': offsetTop
    }
  "
  x-ref="preview"
>
  <div
    class="transition-preview__wrapper"
    @click="
      (e) => {
        if ($refs.transitionContent.contains(e.target)) return;
        if ($refs.transitionBg === e.target) return;

        hidePreview();
      }
    "
  >
    <div class="content-wrapper relative mx-auto">
      <div
        x-ref="transitionBg"
        class="transition-preview__bg"
      ></div>
    </div>
    <div
      x-ref="scrollContainer"
      class="transition-preview__scroll"
      x-a11y-trap="isActive"
    >
      <div class="content-wrapper relative mx-auto">
        <div
          class="transition-preview__content"
          x-ref="transitionContent"
        >
          <div id="PreviewContent"></div>
        </div>
      </div>
    </div>
  </div>
</div>
