<?php

declare(strict_types=1);

use Satoshi\Theme\Block\Template as Block;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Block $block */
/** @var SvgIcons $hyvaicons */
/** @var ViewModelRegistry $viewModels */

$hyvaicons = $viewModels->require(SvgIcons::class);
$lastPage = $block->getData('lastPage');

?>

<div class="my-7 flex flex-col items-center">
    <a
        href="#"
        x-pagination-trigger="{ 'lastPage': <?= $lastPage ?> }"
        class="button btn--size-md button--ghost-primary w-full cursor-pointer text-center md:w-auto"
    >
        <?= __('Load more products') ?>
        <span class="button__icon button__icon--right top-[1px] text-lg rotate-90">
            <?= $hyvaicons->renderHtml('chevron'); ?>
        </span>
    </a>
</div>
