<?php

use Magento\Catalog\Block\Product\AbstractProduct;
use Satoshi\Theme\Block\Template;

/** @var Template $template */
/** @var AbstractProduct $block */
$product = $block->getData('product');

$price = $product->getPrice();
$finalPrice = $product->getData('final_price');
if ($price && $finalPrice) {
    $difference = $price - $finalPrice;
    $discountPercentage = round(($difference * 100.0) / $price);
}

?>

<?php if (isset($discountPercentage) && $discountPercentage > 0) : ?>
    <div class="absolute bottom-4 left-0 rounded-full">
        <span class="card-product__badge bg-white px-3 py-2 text-sm font-bold rounded-r-full">
            -<?php echo $discountPercentage; ?>% OFF
        </span>
    </div>
<?php endif; ?>
