<?php

use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\Wishlist;
use Hyva\Theme\ViewModel\SvgIcons;
use Satoshi\Theme\Block\Template;
use Magento\Catalog\Helper\Image;

/** @var Template $template */

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$productListItemViewModel = $viewModels->require(ProductListItem::class);

$imageLoading = $block->getData('imageLoading');
$isAlpineTemplate = $block->getData('isAlpineTemplate');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$product = $block->getData('product');

$manufacturer = $product?->getAttributeText('manufacturer');
if ($manufacturer === false) {
    $manufacturer = 'N/A';
}

$imageUrl = $this->helper(Image::class)
    ->init($product, 'product_base_image')
    ->getUrl();

?>
<article
    class="z-10 flex h-full w-full flex-col items-stretch justify-start overflow-hidden rounded-xl border-black border-opacity-50 text-start"
    x-data="ProductPage()"

<?php if (!$isAlpineTemplate) : ?>
        x-init="
            () => {
            $data.setProductPageProps({
                productId: <?= $product->getId() ?>,
                isScrollingToTop: false,
                })
            }
        "
<?php endif; ?>
>

<?php if (!$isAlpineTemplate) : // this image is needed to avoid blink in preview on desktop as there, the select variant is shown, not featured image ?>
    <img
        width="0"
        height="0"
        class="pointer-events-none invisible absolute hidden h-0 w-0 md:block"
        src="{{ card_product.selected_or_first_available_variant.image | <?= $imageUrl ?> }}"
        alt=""
    >
<?php endif; ?>

<div
    class="relative overflow-hidden rounded-md"
    x-element-transition-src="img"
>
    <?php if ($isAlpineTemplate) : ?>
        <template x-if="product.featured_image?.url">
            <img
                :src="product.featured_image.url"
                :alt="product.featured_image?.alt"
                class="aspect-product h-full w-full object-cover object-center transition-transform md:group-hover:scale-105"
                loading="<?= $imageLoading ?>"
                width=""
                height=""
            >
        </template>
    <?php else : ?>
        <?php if ($product?->getImage()) : ?>
            <?php // TODO: Create and move into an image snippet/template ?>
            <div
                class="overflow-hidden rounded-md w-full"
                x-element-transition-src="img"
            >
                <img
                    src="<?= $imageUrl ?>"
                    alt="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
                    class="aspect-product h-full w-full object-contain object-center transition-transform md:group-hover:scale-105"
                    loading="<?= $imageLoading ?>"
                >
            </div>
        <?php else : ?>
            <div class="flex aspect-product w-full items-center justify-center bg-secondary-100">
                <?= __('Missing image') ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div class="relative mt-4 flex flex-col gap-1">
    <div class="{{ class }} {% if isLarge %}col-span-2 md:col-auto{% endif %} card-product">
        <article class="z-10 flex h-full w-full flex-col items-stretch justify-start overflow-hidden rounded-xl border-black border-opacity-50 text-start">
            <h2
                class="w-[calc(100%-40px)] text-md truncate mt-2"
                <?php if ($isAlpineTemplate) : ?>
                    x-text="product.name"
                <?php endif; ?>
            >
                <?php if (!$isAlpineTemplate) : ?>
                    <?= $product?->getName(); ?>
                <?php endif; ?>
            </h2>

            <?php // TODO: Make dynamic ?>
            <p class="w-[calc(100%-40px)] truncate text-text-100 contrast-more:text-secondary-700 mt-2">
                <?= $manufacturer ?>
            </p>

            <h2
                class="w-[calc(100%-40px)] text-md truncate mt-2"
                <?php if ($isAlpineTemplate) : ?>
                    x-text="product.price"
                <?php endif; ?>
            >
                <?php if (!$isAlpineTemplate) : ?>
                    <?= /* @noEscape */
                    $productListItemViewModel->getProductPriceHtml($product) ?>
                <?php endif; ?>
            </h2>
        </article>
    </div>

    <?php // TODO: Make Quick buy button work ?>
    <div class="absolute right-0 top-1/2 -translate-y-1/2 text-2xl md:hidden">
        <button
            class="text-xl"
            @click.prevent.stop="quickBuy()"
            aria-label="<?= __('Add to cart') ?>"
        >
            <?= $hyvaicons->renderHtml('cart'); ?>button
        </button>
        <?php if ($product) : ?>
            <?= /* @noEscape */
            $productListItemViewModel->getProductPriceHtml($product) ?>
        <?php endif; ?>
    </div>
</div>
</article>
