<?php

use Hyva\Theme\ViewModel\Wishlist;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Pricing\Helper\Data;
use Magento\Framework\UrlInterface;
use Satoshi\Theme\Block\Template;

/** @var Template $template */

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$imageLoading = $block->getData('imageLoading');
$isAlpineTemplate = $block->getData('isAlpineTemplate');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$objectManager = ObjectManager::getInstance();

if (!$isAlpineTemplate) {
    $product = $block->getData('product');
    $featuredImage = $product?->getImage();
    $title = $product?->getName();

    $storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
    $price = $product->getPrice();
    $finalPrice = $product->getData('final_price');
    $difference = $price - $finalPrice;
    $discountPercentage = round(($difference * 100.0) / $price);

    //TODO: Remove object manager and move to price template
    $pricingHelper = $objectManager->get(Data::class);
    $formattedPrice = floor($price) == $price
        ? strtok($pricingHelper->currency($price, true, false), '.')
        : $pricingHelper->currency($price, true, false);

    $mediaUrl = $storeManager->getStore()->getBaseUrl(UrlInterface::URL_TYPE_MEDIA);
    $imageUrl = $mediaUrl . 'catalog/product' . $product->getImage();
} else {
    $featuredImage = null;
}
?>
<article
    class="z-10 relative flex h-full w-full flex-col items-stretch justify-start text-start"
    x-data="ProductPage()"
    <?php if (!$isAlpineTemplate) : ?>
        <?php // TODO: Create x-init to set correct product data ?>
    <?php endif; ?>
>
    <?php if (!$isAlpineTemplate) : // this image is needed to avoid blink in preview on desktop as there, the select variant is shown, not featured image ?>
        <?php // TODO: Replace with correct image url ?>
        <img
            width="0"
            height="0"
            class="pointer-events-none invisible absolute hidden h-0 w-0 md:block"
            src="{{ card_product.selected_or_first_available_variant.image | image_url }}"
            alt=""
        >
    <?php endif; ?>

    <div
        class="relative overflow-hidden rounded-md"
        x-element-transition-src="img"
    >
        <?php if ($isAlpineTemplate) : ?>
            <template x-if="product.featured_image?.url">
                <img
                    :src="product.featured_image.url"
                    :alt="product.featured_image?.alt"
                    class="aspect-product h-full w-full object-cover object-center transition-transform md:group-hover:scale-105"
                    loading="<?= $imageLoading ?>"
                    width=""
                    height=""
                >
            </template>
            <div
                class="card-product__badge-container z-10 rounded-[20px] bg-white px-3 text-sm"
                x-show="$store['transition'].pageData?.discount_percentage"
            >
                <span
                    class="font-bold"
                    x-text="`-${$store['transition'].pageData?.discount_percentage}% OFF`"
                >
                </span>
            </div>
        <?php else : ?>
            <?php if ($product?->getImage()) : ?>
                <?php // TODO: Create and move into an image snippet/template ?>
                <div
                    class="overflow-hidden rounded-md w-full relative"
                    x-element-transition-src="img"
                >
                    <img
                        <?php // TODO: Update with real dynamic data ?>
                        src="<?php echo $imageUrl; ?>"
                        :alt="product.small_image?.label"
                        class="aspect-product h-full w-full object-contain object-center transition-transform md:group-hover:scale-105"
                        loading="<?= $imageLoading ?>"
                    >
                    <?php if ($discountPercentage) : ?>
                        <div class="absolute bottom-2 left-0 mb-[8px] rounded-full">
                            <span class="card-product__badge bg-white px-3 py-2 text-sm font-bold rounded-r-full">
                                -<?php echo $discountPercentage; ?>% OFF
                            </span>
                        </div>
                    <?php endif; ?>
                </div>
            <?php else : ?>
                <div class="flex aspect-product w-full items-center justify-center bg-secondary-100">
                    <?= __('Missing image') ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

    </div>

    <div class="relative mt-4 flex flex-col gap-1">
        <div class="{{ class }} {% if isLarge %}col-span-2 md:col-auto{% endif %} card-product">
            <article class="z-10 flex h-full w-full flex-col items-stretch justify-start text-start">
                <h2
                    class="w-[calc(100%-40px)] text-md truncate mt-2"
                    <?php if ($isAlpineTemplate) : ?>
                        x-text="product.name"
                    <?php endif; ?>
                >
                    <?php if (!$isAlpineTemplate) : ?>
                        <?= $title ?>
                    <?php endif; ?>
                </h2>

                <?php // TODO: Make dynamic ?>
                <p class="w-[calc(100%-40px)] truncate text-text-100 contrast-more:text-secondary-700 mt-2">
                    Vendor
                </p>

                <h2
                    class="w-[calc(100%-40px)] text-md truncate mt-2"
                    <?php if ($isAlpineTemplate) : ?>
                        x-text="product.price"
                    <?php endif; ?>
                >
                    <?php if (!$isAlpineTemplate) : ?>
                        <?= $formattedPrice ?>
                    <?php endif; ?>
                </h2>
            </article>
        </div>

        <?php // TODO: Make Quick buy button work ?>
        <button
            class="absolute right-0 top-1/2 -translate-y-1/2 text-xl md:hidden"
            @click.prevent.stop="quickBuy()"
            aria-label="<?= __('Add to cart') ?>"
        >
            <?= $hyvaicons->renderHtml('cart'); ?>
        </button>
        <?php // TODO: Create and implement price component ?>
        <?= ''
        // $template
        //   ->setData(['isAlpineTemplate' => true])
        //   ->render('Magento_Catalog::product/view/price.phtml')
        ?>
    </div>
</article>
