<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 *
 * Custom Modifications:
 *       - Implemented a custom "Load More Products" button.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Toolbar $block */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */

$hyvaicons = $viewModels->require(SvgIcons::class);
$lastPage = $block->getCollection()->getLastPageNumber();
$currentPage = $block->getCollection()->getCurPage();

?>

<?php if ($lastPage > 1 && $currentPage < $lastPage): ?>
    <div class="my-7 flex flex-col items-center">
        <a
            href="#"
            x-pagination-trigger="{ 'lastPage': <?= $lastPage ?> }"
            class="button btn--size-md button--ghost-primary w-full cursor-pointer text-center md:w-auto"
        >
            <?= __('Load more products') ?>
            <span class="button__icon button__icon--right top-[1px] text-lg rotate-90">
            <?= $hyvaicons->renderHtml('chevron'); ?>
        </span>
        </a>
    </div>
<?php endif ?>
