<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<section
  id="ProductGridContainer"
  class="content-wrapper animate-on-transition mx-auto"
  x-ref="ProductGridContainer"
  <?php // path set to empty temporarily, will refactored in filters task ?>
  x-data="ProductList('')"
  key="ProductList-someId"
>
  <!-- Filters on mobile goes here -->
  <?= $block->getChildHtml() ?>
</section>