<?php

declare(strict_types=1);
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<div class="flex h-full flex-col items-center justify-center gap-5 text-center px-5">
    <h1 class="heading text-2xl text-text-500"><?= __('You have signed out') ?></h1>
    <p class="font-semibold">
        <?= $escaper->escapeHtml(__('You have signed out and will be redirected to our homepage in 5 seconds.')) ?>
    </p>
    <p class="font-semibold">
        <?= $escaper->escapeHtml(__('Thank you for your visit, we\'re looking forward to see you again soon.')) ?>
    </p>
</div>


<script>
    setTimeout(function () {
        location.href = "<?= $escaper->escapeJs($escaper->escapeUrl($block->getUrl())) ?>"
    }, 5000);
</script>
