name: Push to Readymage
on:
  push:
    branches:
      - production
      - develop

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repos
        shell: bash
        run: |
          # Set Git configuration
          git config --global user.email "bot@satoshi.com"
          git config --global user.name "Satoshi bot"

          # Clone the repository
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/satoshiux/hyva.git
          cd hyva

          # Get the branch name that triggered the workflow
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          # If branch is develop, checkout develop
          if [ "$BRANCH_NAME" = "develop" ]; then
            git fetch --all
            git checkout develop
          fi

          # Remove workflows directory
          rm -rf .github/workflows/

          # Change remote and push
          git remote remove origin
          git remote add origin https://${{ secrets.PAT_TOKEN }}@github.com/scandipwacloud/readymage-satoshi-bmk-1720548019.git
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push -u origin $BRANCH_NAME -f
