name: Push to Readymage
on:
  push:
    branches: develop

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repos
        shell: bash
        run: |
          git config --global user.email "bot@satoshi.com"
          git config --global user.name "Satoshi bot"
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/satoshiux/hyva.git
          cd hyva
          git fetch --all
          git checkout develop
          rm -rf .github/workflows/
          git remote remove origin
          git remote add origin https://${{ secrets.PAT_TOKEN }}@github.com/scandipwacloud/readymage-satoshi-bmk-1720548019.git
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push -u origin develop -f
