<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Satoshi\SatoshiUi\Helper\Link as LinkHelper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
/** @var LinkHelper */
$linkHelper = $this->helper(LinkHelper::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
?>
<!-- TODO: Implement frontend -->