<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Satoshi\SatoshiUi\Block\FAQ;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var FAQ $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$faqs = $block->getData('faqs');
$faqs = $decodeHelper->decodeJSONHTMLEntity($faqs);
$id = uniqid();
?>
<div>
    <h1 class="heading mb-7 text-2xl md:text-4xl"><?= $escaper->escapeHtml($block->getData('heading')) ?></h1>
    <?php if(count($faqs) > 0): ?>
        <div class="flex flex-col gap-7">
            <?php foreach ($faqs as $index => $faq): ?>
                <div x-data="Accordion(<?= (int)($index === 0) ?>, 300)">
                    <button
                        class="group flex w-full justify-between"
                        style="text-align: unset;"
                        x-ref="AccordionButton"
                        :aria-expanded="isExpanded"
                        aria-controls="<?= $escaper->escapeHtmlAttr($id) ?>_panel"
                        aria-labelledby="<?= $escaper->escapeHtmlAttr($id) ?>_label"
                        type="button"
                    >
                        <h2 class="grow text-lg font-semibold" id="<?= $escaper->escapeHtmlAttr($id) ?>_label">
                            <?= $escaper->escapeHtml($faq['question']) ?>
                        </h2>
                        <div
                            class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable"
                        >
                            <span
                                x-ref="AccordionIcon"
                                <?php if ($index === 0): ?>
                                    style="rotate: -180deg"
                                <?php endif; ?>
                            >
                                <?= $hyvaicons->renderHtml('chevron-up') ?>
                            </span>
                        </div>
                    </button>
                    <div
                        x-cloak
                        x-ref="AccordionPanel"
                        class="overflow-hidden"
                        :class="
                            {
                                'transition-none': $store.main.isReducedMotion,
                                'transition': $store.main.isReducedMotion,
                            }
                        "
                        id="<?= $escaper->escapeHtmlAttr($id) ?>_panel"
                        role="region"
                        aria-labelledby="<?= $escaper->escapeHtmlAttr($id) ?>_label"
                    >
                        <div class="rte mt-3 text-text-500 [&>p]:m-0">
                            <?= $escaper->escapeHtml($faq['answer']) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

