<?php

/**
 * @category Scandiweb
 * @author   Scandiweb <info@scandiweb.com>
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Scandiweb\HyvaUi\Helper\Decode as DecodeHelper;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$cols = $block->getData('columns');
$columns = $decodeHelper->decodeJSONHTMLEntity($cols);
?>
<div class="p-6 leading-6">
    <?php if ($columns): ?>
        <div class="mt-8 grid gap-6 md:grid-cols-2">
        <?php foreach ($columns as $column): ?>
            <div class="flex gap-4">
                <div>
                    <div class="w-16 h-16 rounded-full flex justify-center items-center">
                        <img
                            src="<?= $escaper->escapeHtmlAttr($column['column_icon'][0]['url']) ?>"
                            class="rounded-full w-12 h-12"
                            alt=""
                            width="48"
                            height="48"
                            loading="lazy"
                        />
                    </div>
                </div>
                <div>
                    <div class="text-lg text-gray-800 font-medium leading-7 mb-2">
                        <?= $escaper->escapeHtml(__($column['column_title'])) ?>
                    </div>
                    <div>
                        <?= $escaper->escapeHtml(__($column['column_description'])) ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
