<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Satoshi\SatoshiUi\Block\Quotes;
use Satoshi\Theme\Block\Template;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Quotes $block */
/** @var Template $template */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
?>
Slide frontend.phtml