<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Satoshi\SatoshiUi\Block\VideoHero;
use Satoshi\SatoshiUi\Helper\Decode as DecodeHelper;
use Satoshi\SatoshiUi\Helper\Link as LinkHelper;

/** @var VideoHero $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
/** @var LinkHelper $linkHelper */
$linkHelper = $this->helper(LinkHelper::class);

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$link_url = $decodeHelper->decodeJSONHTMLEntity($block->getData('button_link'));
$linkHref = $linkHelper->getLinkHref($block, $link_url);

$videoUrl = $block->getData('video_source');
$imageUrl = $block->getData('image');
$heading = $block->getData('heading');
$description = $block->getData('description');
$overlayOpacity = $block->getData('overlay_opacity');
$autoplay = $block->getData('autoplay') == 'true';
$muted = $block->getData('muted') == 'true';
$loop = $block->getData('loop') == 'true';

$bannerHeight = $block->getData('banner_height') ?? 'large';
$desktopAlignment = $block->getData('desktop_content_position') ?? 'middle-right';
$mobileAlignment = $block->getData('mobile_content_alignment') ?? 'bottom-center';

?>
<div class="relative overflow-hidden">
    <div class="absolute left-0 top-0 z-10 h-full w-full bg-black" style="opacity: <?= $escaper->escapeHtmlAttr($overlayOpacity) ?>"></div>
    <?php if(str_ends_with($videoUrl, '.mp4')): ?>
        <video class="absolute left-0 top-0 z-0 h-full w-full object-cover object-center" muted autoplay loop playsinline>
            <source src="<?= $escaper->escapeUrl($videoUrl) ?>" type="video/mp4">
        </video>
    <?php else: ?>
        <iframe
            src="<?= $escaper->escapeUrl($videoUrl) ?>"
            autoplay="<?= $autoplay ? 'true' : 'false' ?>"
            muted="<?= $muted ? 'true' : 'false' ?>"
            loop="<?= $loop ? 'true' : 'false' ?>"
            controls="false"
            class="absolute left-0 top-0 z-0 h-full w-full object-cover object-center"
            allow="autoplay; encrypted-media"
            allowfullscreen
            title="<?= $escaper->escapeHtml($heading) ?>"
        ></iframe>
    <?php endif; ?>
    <div
        class="content-wrapper relative z-20 m-auto flex
            <?= match($bannerHeight) {
                'small' => 'pb-12 pt-20 md:py-[5vh] h-[40vh]',
                'medium' => 'pb-12 pt-20 md:py-[10vh] h-[60vh]',
                'large' => 'pb-12 pt-20 md:py-[20vh] h-[calc(100svh-34px)] md:h-[80vh]',
                default => ''
            } ?>
            <?= match($mobileAlignment) {
                'top-left' => 'items-start justify-start',
                'top-center' => 'items-start justify-center',
                'top-right' => 'items-start justify-end',
                'middle-left' => 'items-center justify-start',
                'middle-center' => 'items-center justify-center',
                'middle-right' => 'items-center justify-end',
                'bottom-left' => 'items-end justify-start',
                'bottom-center' => 'items-end justify-center',
                'bottom-right' => 'items-end justify-end',
                default => ''
            } ?>
            <?= match($desktopAlignment) {
                'top-left' => 'md:items-start md:justify-start',
                'top-center' => 'md:items-start md:justify-center',
                'top-right' => 'md:items-start md:justify-end',
                'middle-left' => 'md:items-center md:justify-start',
                'middle-center' => 'md:items-center md:justify-center',
                'middle-right' => 'md:items-center md:justify-end',
                'bottom-left' => 'md:items-end md:justify-start',
                'bottom-center' => 'md:items-end md:justify-center',
                'bottom-right' => 'md:items-end md:justify-end',
                default => ''
            } ?>
        "
    >
        <div
            class="
                flex max-w-[335px] md:max-w-[500px] flex-col justify-center gap-7 md:gap-10 text-text-on-primary-bg
                <?php if(str_contains($mobileAlignment, 'left')): ?>
                    items-start text-start
                <?php elseif(str_contains($mobileAlignment, 'right')): ?>
                    items-end text-end
                <?php else: ?>
                    items-center text-center
                <?php endif; ?>
                <?php if(str_contains($desktopAlignment, 'left')): ?>
                    md:items-start md:text-start
                <?php elseif(str_contains($desktopAlignment, 'right')): ?>
                    md:items-end md:text-end
                <?php else: ?>
                    md:items-center md:text-center
                <?php endif; ?>
            "
        >
            <h2
                class="heading text-4xl leading-tight md:text-6xl md:leading-tight"
            >
                <?= $escaper->escapeHtml($heading) ?>
            </h2>
            <?php if(!empty($description)): ?>
                <p>
                    <?= $escaper->escapeHtml($description) ?>
                </p>
            <?php endif; ?>
            <?php if(!empty($block->getData('button_label'))): ?>
                <a
                    <?php if ($linkHref): ?>
                        href="<?= $escaper->escapeUrl($linkHref); ?>"
                        target="<?= $escaper->escapeHtmlAttr($linkHelper->getLinkTarget($link_url)); ?>"
                    <?php endif; ?>
                    class="button button--filled-primary font-normal"
                    x-element-transition-trigger
                >
                    <?= $escaper->escapeHtml($block->getData('button_label')) ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>
