<?php

declare(strict_types=1);

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Review\Block\Form;

/** @var Escaper $escaper */
/** @var Form $block */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

$formId = 'review_form';

/** @var GraphqlViewModel $gqlViewModel */
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on Magento_ReCaptchaReview module
/** @var ReCaptcha $recaptcha */
$recaptcha = $block->getData('viewModelRecaptcha');

$gqlCreateProductReviewMutation = '
mutation createProductReviewMutation(
    $sku: String!,
    $nick: String!,
    $summary: String!,
    $review: String!,
    $ratings: [ProductReviewRatingInput]!
) {
    createProductReview(
        input: {
            sku: $sku,
            nickname: $nick,
            summary: $summary,
            text: $review,
            ratings: $ratings
        }
    ) {
        review {
            nickname
        }
    }
}
';

?>
<div class="mx-auto content-wrapper mt-8">
    <div class="flex flex-col items-center py-7 md:py-8 px-5 md:px-12 rounded-xl bg-secondary-500">
        <div class="mb-4 text-2xl text-text-500">
            <?= $escaper->escapeHtml(__('Write Your Own Review')) ?>
        </div>
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form
                class="w-full max-w-sm"
                id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                @submit.prevent="function($event) {
                    const $form = $event.target;
                    this.validate();
                    <?= $recaptcha ? $escaper->escapeHtmlAttr($recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_PRODUCT_REVIEW)) : '' ?>
                    if (this.errors === 0) {
                      this.placeReview();
                    }
                }"
                action=""
                x-data="Object.assign(Form('<?= $escaper->escapeHtmlAttr($formId) ?>'), ReviewForm({
                    ratings: <?= $escaper->escapeHtmlAttr(json_encode($block->getRatings()->getData())) ?>,
                    messages: {
                        required: '<?= $escaper->escapeJs(__('Please verify you\'ve entered all required information')) ?>',
                        failed: '<?= $escaper->escapeJs(__('Submitting your review failed, please try again.')) ?>'
                    },
                    gqlQuery: `<?= $escaper->escapeHtmlAttr($gqlViewModel->query('create_product_review_mutation', $gqlCreateProductReviewMutation)) ?>`,
                    sku: '<?= $escaper->escapeJs($block->getProductInfo()->getSku()) ?>',
                    fieldName: '<?= $recaptcha ? $escaper->escapeJs($recaptcha->getResultTokenFieldName($formId)) : '' ?>',
                    formId: '<?= $escaper->escapeJs($formId) ?>',
                    storeCode: '<?= $escaper->escapeJs($viewModelStore->getStoreCode()) ?>'
                }))"

            >
                <?= $block->getChildHtml('form_fields_before') ?>
                <fieldset class="w-full flex flex-col items-center justify-center">
                    <legend class="mb-4 text-center text-md">
                        <span>
                            <?= $escaper->escapeHtml(
                                __("You're reviewing:")
                            ) ?>
                        </span>
                        <span class="font-semibold">
                            <?= $escaper->escapeHtml($block->getProductInfo()->getName()) ?>
                        </span>
                    </legend>
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <fieldset name="rating-group">
                            <div class="flex flex-col mb-4">
                                <div
                                    class="text-md <?php if ($block->getRatings()->getSize() <= 1): ?>hidden<?php endif ?>">
                                    <?= $escaper->escapeHtml(__('Your Rating')) ?>:
                                </div>
                                <div id="product-review-table">
                                    <?php foreach ($block->getRatings() as $rating): ?>
                                        <div class="flex items-center">
                                            <h2
                                                class="table-cell pr-6 align-middle text-left"
                                                id="<?= $escaper->escapeHtml($rating->getRatingCode()) ?>_rating_label"
                                            >
                                                <span>
                                                    <?php if ($block->getRatings()->getSize() <= 1): ?>
                                                        <?= $escaper->escapeHtml(__('Your Rating')) ?>:
                                                    <?php else: ?>
                                                        <?= $escaper->escapeHtml($rating->getRatingCode()) ?>
                                                    <?php endif ?>
                                                </span>
                                            </h2>
                                            <div
                                                class="flex grow-0"
                                                x-data="{ clickedRatingId: 0 }"
                                            >
                                                <?php $options = $rating->getOptions(); ?>
                                                <?php $iterator = 1;
                                                foreach ($options as $option): ?>
                                                    <div
                                                        class="relative"
                                                        @click="clickedRatingId = <?= (int)$iterator ?> || 0"
                                                    >
                                                        <label
                                                            class="rating-<?= (int)$iterator ?> m-0 cursor-pointer text-secondary-600"
                                                            for="<?= $escaper->escapeHtmlAttr($rating->getRatingCode() . '_' . $option->getValue()) ?>"
                                                            id="<?= $escaper->escapeHtmlAttr($rating->getRatingCode() . '_' . $option->getValue()) ?>_label"
                                                        >
                                                            <input
                                                                class="peer absolute opacity-0 bottom-0 left-0 cursor-pointer"
                                                                type="radio"
                                                                <?php if ($iterator === 1): ?>required<?php endif; ?>
                                                                name="ratings[<?= $escaper->escapeHtmlAttr($rating->getId()) ?>]"
                                                                id="<?= $escaper->escapeHtmlAttr($rating->getRatingCode() . '_' . $option->getValue()) ?>"
                                                                value="<?= $escaper->escapeHtmlAttr($option->getId()) ?>"
                                                                <?php if ($iterator === 1): ?>
                                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('1 star')) ?>"
                                                                <?php else: ?>
                                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('%1 stars', $iterator)) ?>"
                                                                <?php endif; ?>
                                                            />
                                                            <span
                                                                class="peer-focus:[&>svg]:focus-ring"
                                                                :class="<?= (int)$iterator ?> <= clickedRatingId ? 'text-primary-500' : 'text-secondary-700'"
                                                            >
                                                                <?= $hyvaicons->renderHtml('star', 'text-xl') ?>
                                                            </span>
                                                        </label>
                                                    </div>
                                                    <?php $iterator++; ?>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <input type="hidden" name="validate_rating" value=""/>
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div x-cloak
                         x-show="displaySuccessMessage"
                         class="field-success mb-4">
                        <p>
                            <?= $escaper->escapeHtml(__('You submitted your review for moderation.')) ?>
                        </p>
                    </div>
                    <div class="w-full">
                        <div class="input mb-3">
                            <label for="nickname_field" class="sr-only tracking-widest">
                                <span><?= $escaper->escapeHtml(__('Nickname')) ?></span>
                            </label>
                            <input class="input__field input__field--outline bg-bg-500 px-5 py-4"
                                   required
                                   placeholder="<?= $escaper->escapeHtmlAttr(__('Nickname') . '*') ?>" type="text"
                                   name="nickname" id="nickname_field"/>
                        </div>
                        <div class="input mb-3">
                            <label for="summary_field" class="sr-only">
                                <span><?= $escaper->escapeHtml(__('Summary')) ?></span>
                            </label>
                            <div>
                                <input class="input__field input__field--outline bg-bg-500 px-5 py-4"
                                       required
                                       placeholder="<?= $escaper->escapeHtml(__('Summary') . '*') ?>" type="text"
                                       name="title"
                                       id="summary_field"/>
                            </div>
                        </div>
                        <div class="input mb-4">
                            <label for="review_field" class="sr-only tracking-widest">
                                <span><?= $escaper->escapeHtml(__('Review')) ?></span>
                            </label>
                            <div>
                            <textarea
                                required
                                placeholder="<?= $escaper->escapeHtml(__('Review') . '*') ?>" name="detail"
                                id="review_field" cols="5"
                                rows="5"
                                class="input__field input__field--outline flex h-36 resize-none bg-bg-500 px-5 py-2.5"
                            ></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_PRODUCT_REVIEW) : '' ?>
                <template x-if="displayErrorMessage">
                    <template x-for="errorMessage in errorMessages">
                        <p x-text="errorMessage" class="text-error items-center mt-4">
                        </p>
                    </template>
                </template>
                <button
                    type="submit"
                    class="button button--filled-primary w-full my-4"
                    :class="{
                            '!bg-primary-100': isLoading
                        }"
                >
                    <span>
                        <?= $escaper->escapeHtml(__('Submit Review')) ?>
                    </span>
                </button>
                <?= $block->getChildHtml('form_additional_after') ?>
                <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_PRODUCT_REVIEW) : '' ?>
            </form>
        <?php else: ?>
            <div
                id="review-form"
                class="text-center"
            >
                <?= $escaper->escapeHtml(
                    __(
                        'Only registered users can write reviews. Please <a x-element-transition-trigger href="%1" class="underline">Sign in</a> or <a href="%2" class="underline">create an account</a>',
                        $block->getLoginLink(),
                        $block->getRegisterUrl()
                    ),
                    ['a']
                ) ?>
            </div>
        <?php endif ?>
    </div>
</div>
